# -*- coding: utf-8 -*-
"""App

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1C4bBid_wGYFM64wk402K0SkyLVv0d6tv
"""

import streamlit as st
import pandas as pd
import joblib

# ==========================================
# PAGE CONFIGURATION
# ==========================================

st.set_page_config(
    page_title="Diabetes Prediction",
    page_icon="🩺",
    layout="centered"
)


# ==========================================
# LOAD TRAINED MODEL
# ==========================================

model = joblib.load("model.pkl")


# ==========================================
# TITLE
# ==========================================

st.title("🩺 Diabetes Prediction App")

st.write(
    "Enter the patient information below "
    "to obtain a model-estimated diabetes probability."
)


# ==========================================
# USER INPUTS
# ==========================================

pregnancies = st.number_input(
    "Pregnancies",
    min_value=0,
    max_value=20,
    value=1
)

glucose = st.number_input(
    "Glucose",
    min_value=0,
    max_value=250,
    value=120
)

blood_pressure = st.number_input(
    "Blood Pressure",
    min_value=0,
    max_value=200,
    value=70
)

skin_thickness = st.number_input(
    "Skin Thickness",
    min_value=0,
    max_value=100,
    value=20
)

insulin = st.number_input(
    "Insulin",
    min_value=0,
    max_value=900,
    value=80
)

bmi = st.number_input(
    "BMI",
    min_value=0.0,
    max_value=70.0,
    value=30.0
)

diabetes_pedigree = st.number_input(
    "Diabetes Pedigree Function",
    min_value=0.0,
    max_value=3.0,
    value=0.47
)

age = st.number_input(
    "Age",
    min_value=1,
    max_value=120,
    value=30
)


# ==========================================
# CREATE INPUT DATAFRAME
# ==========================================

input_data = pd.DataFrame({
    "Pregnancies": [pregnancies],
    "Glucose": [glucose],
    "BloodPressure": [blood_pressure],
    "SkinThickness": [skin_thickness],
    "Insulin": [insulin],
    "BMI": [bmi],
    "DiabetesPedigreeFunction": [diabetes_pedigree],
    "Age": [age]
})


# ==========================================
# PREDICTION
# ==========================================

if st.button("Predict Diabetes"):
    prediction = model.predict(input_data)[0]

    st.write("Prediction:", prediction)

    if hasattr(model, "predict_proba"):
        probability = model.predict_proba(input_data)[0].max()
        st.write(f"Probability: {probability:.2%}")

    else:
        st.warning("Probability is not available for this model.")

    st.metric("Estimated Diabetes Probability",f"{probability * 100:.2f}%")
    if prediction == 1:

        st.error(
            "Model prediction: Outcome = 1"
        )

    else:

        st.success(
            "Model prediction: Outcome = 0"
        )

    st.info(
        "This is a machine-learning prediction "
        "and should not be treated as a medical diagnosis."
    )

import sklearn
import joblib
import numpy as np

print("Scikit-learn:", sklearn.__version__)
print("Joblib:", joblib.__version__)
print("NumPy:", np.__version__)