# -*- coding: utf-8 -*-
"""Logistic Regression Assessment.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1LjqfScGZ34UOUdSuP4KIYlTPTQxBI81K
"""

# IMPORT REQUIRED LIBRARIES
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

from sklearn.model_selection import train_test_split
from sklearn.pipeline import Pipeline
from sklearn.impute import SimpleImputer
from sklearn.preprocessing import StandardScaler
from sklearn.linear_model import LogisticRegression

from sklearn.metrics import (
    accuracy_score,
    precision_score,
    recall_score,
    f1_score,
    roc_auc_score,
    classification_report,
    confusion_matrix,
    roc_curve
)
import warnings
warnings.filterwarnings("ignore")

# LOAD DATASET
df = pd.read_csv("diabetes.csv")
df

df.info()

df.shape

df.size

df.describe()

df.isnull().sum()

"""Check zero values"""

zero_columns = [
    "Glucose",
    "BloodPressure",
    "SkinThickness",
    "Insulin",
    "BMI"
]
for column in zero_columns:
    print(column,"zero values:",(df[column] == 0).sum())

# replace these zero values with NaN.
# Create a copy
data = df.copy()
# Replace physiologically implausible zeros with NaN
for column in zero_columns:
    data[column] = data[column].replace(0, np.nan)
data.isnull().sum()

plt.figure(figsize=(7, 5))
sns.countplot(
    data=df,
    x="Outcome"
)
plt.title("Diabetes Outcome Distribution")
plt.xlabel("Outcome")
plt.ylabel("Number of Patients")
plt.show()

# Select numerical columns
features = [
    "Pregnancies",
    "Glucose",
    "BloodPressure",
    "SkinThickness",
    "Insulin",
    "BMI",
    "DiabetesPedigreeFunction",
    "Age"
]
# Create histograms
df[features].hist(
    figsize=(15, 12),
    bins=20
)
plt.suptitle(
    "Distribution of Diabetes Dataset Features",
    fontsize=16
)
plt.tight_layout()
plt.show()

"""The distributions show that:

Glucose has considerable variation.

BMI is concentrated around the normal/overweight range but contains larger values.

Age is concentrated among younger adults.

Insulin is strongly right-skewed.

Pregnancies is discrete and right-skewed.

DiabetesPedigreeFunction is also right-skewed.
"""

for i in df.select_dtypes(include=['int','float']).columns:
  sns.boxplot(df[i])
  plt.show()

for i in df.select_dtypes(include=['int','float']).columns:
    q1=df[i].quantile(0.25)
    q3=df[i].quantile(0.75)
    IQR=q3-q1
    lower_bound=q1-1.5*IQR
    upper_bound=q3+1.5*IQR
    df[i]=df[i].clip(lower_bound,upper_bound)

for i in df.select_dtypes(include=['int','float']).columns:
  sns.boxplot(df[i])
  plt.show()

"""Glucose vs Outcome"""

plt.figure(figsize=(8, 5))
sns.boxplot(
    data=df,
    x="Outcome",
    y="Glucose"
)
plt.title("Glucose Distribution by Diabetes Outcome")
plt.xlabel("Outcome")
plt.ylabel("Glucose")
plt.show()

"""BMI vs Outcome"""

plt.figure(figsize=(8, 5))
sns.boxplot(
    data=df,
    x="Outcome",
    y="BMI"
)
plt.title("BMI Distribution by Diabetes Outcome")
plt.xlabel("Outcome")
plt.ylabel("BMI")
plt.show()

"""Age vs Outcome"""

plt.figure(figsize=(8, 5))
sns.boxplot(
    data=df,
    x="Outcome",
    y="Age"
)
plt.title("Age Distribution by Diabetes Outcome")
plt.xlabel("Outcome")
plt.ylabel("Age")
plt.show()

"""Correlation Matrix"""

plt.figure(figsize=(10, 8))
correlation = df.corr()
sns.heatmap(
    correlation,
    annot=True,
    cmap="coolwarm",
    fmt=".2f"
)
plt.title("Correlation Matrix")
plt.show()

pairplot_columns = [
    "Glucose",
    "BMI",
    "Age",
    "Pregnancies",
    "Outcome"
]

sns.pairplot(
    df[pairplot_columns],
    hue="Outcome",
    diag_kind="hist"
)

plt.show()

"""Data Preprocessing"""

# Independent variables
X = data.drop("Outcome", axis=1)

# Dependent variable
y = data["Outcome"]

print("X shape:", X.shape)
print("y shape:", y.shape)

"""Train-Test Split"""

X_train, X_test, y_train, y_test = train_test_split(X,y,test_size=0.20,random_state=42,stratify=y)
print("Training samples:", X_train.shape[0])
print("Testing samples :", X_test.shape[0])

"""imputation and standardization"""

preprocessing = Pipeline(
    steps=[
        ("imputer",SimpleImputer(strategy="median")),
        ("scaler",StandardScaler())
    ]
)

# LOGISTIC REGRESSION PIPELINE
model = Pipeline(
    steps=[("preprocessing",preprocessing),
        ("classifier",LogisticRegression(max_iter=1000))
    ]
)

# Train model
model.fit(
    X_train,
    y_train
)
print("Model training completed!")

"""Make Predictions"""

# Predicted classes
y_pred = model.predict(X_test)

# Predicted probabilities
y_prob = model.predict_proba(X_test)[:, 1]

print("Predicted classes:")
print(y_pred[:10])

print("\nPredicted probabilities:")
print(y_prob[:10])

"""Model Evaluation"""

# Accuracy
accuracy = accuracy_score(
    y_test,
    y_pred
)
print("Accuracy:", accuracy)

# Precision
precision = precision_score(
    y_test,
    y_pred
)
print("Precision:", precision)

# Recall
recall = recall_score(
    y_test,
    y_pred
)
print("Recall:", recall)

# F1 Score
f1 = f1_score(
    y_test,
    y_pred
)
print("F1 Score:", f1)

# ROC-AUC
roc_auc = roc_auc_score(
    y_test,
    y_prob
)
print("ROC-AUC:", roc_auc)

"""Classification report"""

print(classification_report(y_test,y_pred))

"""confusion matrix"""

cm=confusion_matrix(
    y_test,
    y_pred
)
plt.figure(figsize=(7, 5))
sns.heatmap(
    cm,
    annot=True,
    fmt="d",
    cmap="Blues"
)
plt.xlabel("Predicted")
plt.ylabel("Actual")
plt.title("Confusion Matrix")
plt.show()
print(cm)

"""ROC Curve"""

# Calculate ROC curve
fpr, tpr, thresholds = roc_curve(
    y_test,
    y_prob
)
# Plot
plt.figure(figsize=(8, 6))
plt.plot(
    fpr,
    tpr,
    label=f"Logistic Regression (AUC = {roc_auc:.3f})"
)
# Random classifier
plt.plot(
    [0, 1],
    [0, 1],
    linestyle="--",
    label="Random Classifier"
)
plt.xlabel("False Positive Rate")
plt.ylabel("True Positive Rate")
plt.title("ROC Curve - Diabetes Prediction")
plt.legend()
plt.show()

"""Interpretation of logistic regression coefficients

"""

# Get feature names
feature_names = X.columns
# Get coefficients
coefficients = model.named_steps[
    "classifier"
].coef_[0]
coefficient_df = pd.DataFrame({
    "Feature": feature_names,
    "Coefficient": coefficients
})
# Calculate odds ratio
coefficient_df["Odds_Ratio"] = np.exp(
    coefficient_df["Coefficient"]
)
coefficient_df = coefficient_df.sort_values(
    by="Coefficient",
    ascending=False
)
display(coefficient_df)

"""Coefficient Visualization"""

plt.figure(figsize=(10, 7))
sns.barplot(
    data=coefficient_df,
    x="Coefficient",
    y="Feature"
)
plt.axvline(
    0,
    linestyle="--"
)
plt.title(
    "Logistic Regression Coefficients"
)
plt.xlabel("Coefficient")
plt.ylabel("Feature")
plt.show()

"""Predicted Diabetes Probability"""

# Display actual outcome and predicted probability
prediction_results = pd.DataFrame({
    "Actual": y_test.values,
    "Predicted": y_pred,
    "Diabetes_Probability": y_prob
})
display(
    prediction_results.head(10)
)

import pandas as pd
import numpy as np
import joblib

from sklearn.pipeline import Pipeline
from sklearn.impute import SimpleImputer
from sklearn.preprocessing import StandardScaler
from sklearn.linear_model import LogisticRegression


# ==========================================
# LOAD DATA
# ==========================================

df = pd.read_csv("diabetes.csv")


# ==========================================
# REPLACE INVALID ZERO VALUES
# ==========================================

zero_columns = [
    "Glucose",
    "BloodPressure",
    "SkinThickness",
    "Insulin",
    "BMI"
]

for column in zero_columns:
    df[column] = df[column].replace(0, np.nan)


# ==========================================
# FEATURES AND TARGET
# ==========================================

X = df.drop("Outcome", axis=1)

y = df["Outcome"]


# ==========================================
# BUILD MODEL
# ==========================================

model = Pipeline(
    steps=[
        (
            "imputer",
            SimpleImputer(strategy="median")
        ),
        (
            "scaler",
            StandardScaler()
        ),
        (
            "classifier",
            LogisticRegression(
                max_iter=1000
            )
        )
    ]
)


# ==========================================
# TRAIN MODEL ON COMPLETE DATA
# ==========================================

model.fit(X, y)


# ==========================================
# SAVE MODEL
# ==========================================

joblib.dump(
    model,
    "model.pkl"
)

print("Model saved successfully!")

from sklearn.compose import ColumnTransformer
from sklearn.pipeline import Pipeline
from sklearn.impute import SimpleImputer
from sklearn.preprocessing import OneHotEncoder, StandardScaler
from sklearn.ensemble import RandomForestRegressor
import joblib

# Define numerical and categorical columns
numerical_columns = X.columns.tolist()
categorical_columns = [] # Assuming no categorical columns in this dataset

numeric_pipeline = Pipeline([
    ("imputer", SimpleImputer(strategy="median")),
    ("scaler", StandardScaler())
])

categorical_pipeline = Pipeline([
    ("imputer", SimpleImputer(strategy="most_frequent")),
    ("encoder", OneHotEncoder(handle_unknown="ignore"))
])

preprocessor = ColumnTransformer([
    ("num", numeric_pipeline, numerical_columns),
    ("cat", categorical_pipeline, categorical_columns)
])

model = Pipeline([
    ("preprocessor", preprocessor),
    ("regressor", RandomForestRegressor(random_state=42))
])

model.fit(X_train, y_train)

joblib.dump(model, "model.pkl")