# -*- coding: utf-8 -*-
"""Basic of Python.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1h7Y3FY3HWbxwQ5dUKRcHFTI2K68reOeO

**Exercise 1: Prime Numbers**

Write a Python program that checks whether a given number is prime or not. A prime number is a natural number greater than 1 that has no positive divisors other than 1 and itself.
"""

n=int(input("Enter a number: "))
if n<=1:
    print("Not a prime number")
else:
    is_prime=True
    for i in range(2,n):
        if n%i==0:
            is_prime=False
            break
    if is_prime:
        print("Prime number")
    else:
        print("Not a prime number")

"""**Exercise 2: Product of Random Numbers**

Develop a Python program that generates two random numbers and asks the user to enter the product of these numbers. The program should then check if the user's answer is correct and display an appropriate message.

"""

import random
num1=random.randint(1,10)
num2=random.randint(1,10)
question=int(input(f"what is {num1} X {num2} ? "))
answer=num1*num2
if question==answer:
  print("correct the answer is ",answer)
else:
  print(f"wrong, {answer} is the correct answer")

"""**Exercise 3: Squares of Even/Odd Numbers**

Create a Python script that prints the squares of all even or odd numbers within the range of 100 to 200. Choose either even or odd numbers and document your choice in the code.

Choice:print all the square root of odd number from 100 to 200
"""

for i in range(100,200):
  if i%2==1:
    print(f"{i}^2={i**2}")

"""**Exercise 4:
✅ Problem Statement (Question): Hospital Billing System**

A hospital charges its patients based on the following:

•	Room charges per day: ₹2,000

•	Doctor consultation fee (flat): ₹1,500

•	Lab test charges: Based on the number of tests taken. Each test costs ₹300

•	Medicine charges: Total cost of medicines provided

•	Discount: If the total bill (before discount) exceeds ₹10,000, a 10% discount is applied

Write a Python program to calculate the final bill for a patient who:

•	Stayed for 4 days

•	Had 3 lab tests

•	Had medicine charges of ₹2,400

"""

room_charges_per_day=2000
doc_fee=1500
lab_test_each=300
days=4
tests=3
med_charges=2400
room_charge=room_charges_per_day*days
lab_charge=lab_test_each*tests
total_bill=room_charge+lab_charge+doc_fee+med_charges
if total_bill>10000:
  discount=total_bill*0.10
else:
  discount=0
final_bill=total_bill-discount
print(f"Room charges: ${room_charge}")
print(f"Lab charges: ${lab_charge}")
print(f"Medicines cost: ${med_charges}")
print(f"Doctor Consultation fee: ${doc_fee}")
print(f"Total bill: ${total_bill}")
print(f"Discount: ${discount}")
print(f"Final bill: ${final_bill}")