# -*- coding: utf-8 -*-
"""Basic Stats-2.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1ndCFEEU0R4CCsjFlXaua5lVnPZV2vRpv

**Problem Statement : Hospital Patient Data Analysis**

Context:
A hospital maintains patient records including admission details, department, diagnosis, doctor, and bill amount. You have two datasets: one with patient info and another with billing details. Some patients have blank bill amounts, and there are multiple rows for the same patient due to follow-ups.

Tasks:

1.	Load the patient dataset and show summary with info().

2.	Select only the columns relevant for billing: ['PatientID', 'Department', 'Doctor', 'BillAmount'].

3.	Drop administrative columns like ['ReceptionistID', 'CheckInTime'].

4.	Use groupby to find total bill amount per department.

5.	Remove duplicate patient records based on PatientID.

6.	Fill missing BillAmount values with the mean bill amount.

7.	Merge the billing dataset with patient dataset on PatientID.

8.	Concatenate an additional DataFrame that contains new patients for the current week (row-wise).

9.	Concatenate new billing category columns like ['InsuranceCovered', 'FinalAmount'] (column-wise).

Expected Outcome:
•	Final cleaned dataset with accurate billing info.
•	All missing values handled, merged dataset across PatientID.
•	Ability to perform further analytics on department-wise revenue or doctor performance.
"""

import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
import warnings
warnings.filterwarnings('ignore')

patients_df=pd.read_csv('Patient_Data.csv')
df

df.head()

df.info()

df.describe()

df.isnull().sum()

df.duplicated().sum()

"""2.Select only the columns relevant for billing: ['PatientID', 'Department', 'Doctor', 'BillAmount']."""

billing_columns=['PatientID','Department','Doctor','BillAmount']
billing_data=df[billing_columns]
print(billing_data)

df

"""3.	Drop administrative columns like ['ReceptionistID', 'CheckInTime']."""

patients = patients.drop(columns=['ReceptionistID', 'CheckInTime'],errors='ignore')
patients.head()

"""4.	Use groupby to find total bill amount per department."""

department_bill=(patients.groupby('Department')['BillAmount'].sum())
department_bill

"""5.	Remove duplicate patient records based on PatientID."""

patients_df= patients_df.drop_duplicates(subset='PatientID',keep='first')
patients

"""6.	Fill missing BillAmount values with the mean bill amount."""

mean_bill=patients['BillAmount'].mean()
print("Mean Bill Amount:",mean_bill)

patients['BillAmount'] = patients['BillAmount'].fillna(mean_bill)
patients

patients['BillAmount'].isnull().sum()

billing = pd.read_csv("Billing_Data.csv")
billing.head()

"""7.	Merge the billing dataset with patient dataset on PatientID."""

merged_data = pd.merge(patients,billing,on='PatientID',how='left')
print("\nMerged Dataset:")
merged_data

"""8.	Concatenate an additional DataFrame that contains new patients for the current week (row-wise).

"""

new_patients = pd.DataFrame({
    'PatientID':[106,107],
    'Department':['Cardiology','Neurology'],
    'Doctor':['Dr. Kumar','Dr. Sharma'],
    'BillAmount':[25000,18000]
})
print("\nNew Patients:")
new_patients

patients_updated = pd.concat([patients, new_patients],ignore_index=True)
patients_updated

"""9.	Concatenate new billing category columns like ['InsuranceCovered', 'FinalAmount'] (column-wise)."""

new_billing_columns = pd.DataFrame({
    'InsuranceCovered': [5000, 7000, 3000, 6000],
    'FinalAmount': [20000, 28000, 17000, 24000]
})

final_data = pd.concat(
    [patients_updated.reset_index(drop=True),
     new_billing_columns.reset_index(drop=True)],
    axis=1
)
final_data