# -*- coding: utf-8 -*-
"""Basic stats-1.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1Nfncr-BpSchA61dVh6a1nxB2kARtkneE

**Descriptive Analytics and Data Preprocessing on Sales & Discounts**

Dataset
Introduction

●	To perform descriptive analytics, visualize data distributions, and preprocess the dataset for further analysis.

Descriptive Analytics for Numerical Columns

●	Objective: To compute and analyze basic statistical measures for numerical columns in the dataset.

●	Steps:
	Load the dataset into a data analysis tool or programming environment (e.g., Python with pandas library).
	Identify numerical columns in the dataset.
	Calculate the mean, median, mode, and standard deviation for these columns.
	Provide a brief interpretation of these statistics.

Data Visualization

●	Objective: To visualize the distribution and relationship of numerical and categorical variables in the dataset.

●	Histograms:
	Plot histograms for each numerical column.
	Analyze the distribution (e.g., skewness, presence of outliers) and provide inferences.

●	Box Plots:
	Create boxplots for numerical variables to identify outliers and the interquartile range.
	Discuss any findings, such as extreme values or unusual distributions.

●	Bar Chart Analysis for Categorical Column:
	Identify categorical columns in the dataset.
	Create bar charts to visualize the frequency or count of each category.
	Analyze the distribution of categories and provide insights.

Conclusion

●	Summarize the key findings from the descriptive analytics and data visualizations.
"""

import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
import warnings
warnings.filterwarnings('ignore')

df=pd.read_csv('sales_data_with_discounts.csv')
df

df.head()

df.info()

df.describe()

df.shape

df.size

df.isnull().sum()

df.duplicated().sum()

numerical_columns = df.select_dtypes(include=['int','float']).columns
categorical_columns = df.select_dtypes(include=['object', 'category']).columns
print("\nNumerical Columns:")
print(list(numerical_columns))
print("\nCategorical Columns:")
print(list(categorical_columns))

# Calculate descriptive statistics

for column in numerical_columns:
    print("\n--------------------------------")
    print("Column:", column)

    print("Mean:", df[column].mean())
    print("Median:", df[column].median())
    print("Mode:", df[column].mode()[0])
    print("Standard Deviation:", df[column].std())

statistics = pd.DataFrame({
    'Mean':df[numerical_columns].mean(),
    'Median':df[numerical_columns].median(),
    'Mode':df[numerical_columns].mode().iloc[0],
    'Standard Deviation':df[numerical_columns].std()
})
print("\nDescriptive Statistics:")
print(statistics)

# histograms for numerical columns
for column in numerical_columns:
    plt.figure(figsize=(8, 5))
    plt.hist(df[column].dropna(), bins=10, edgecolor='black')
    plt.title(f'Distribution of {column}')
    plt.xlabel(column)
    plt.ylabel('Frequency')
    plt.grid(axis='y', alpha=0.3)
    plt.show()

for i in df.select_dtypes(include=['int','float']).columns:
  sns.boxplot(df[i])
  plt.show()

for i in df.select_dtypes(include=['int','float']).columns:
    q1=df[i].quantile(0.25)
    q3=df[i].quantile(0.75)
    IQR=q3-q1
    lower_bound=q1-1.5*IQR
    upper_bound=q3+1.5*IQR
    df[i]=df[i].clip(lower_bound,upper_bound)

for i in df.select_dtypes(include=['int','float']).columns:
  sns.boxplot(df[i])
  plt.show()

print("Categorical columns:")
print(list(categorical_columns))

for column in categorical_columns:
    plt.figure(figsize=(10, 5))
    df[column].value_counts().plot(kind='bar')
    plt.title(f'Frequency of {column}')
    plt.xlabel(column)
    plt.ylabel('Count')
    plt.xticks(rotation=45)
    plt.tight_layout()
    plt.show()

"""**conclusion:** The descriptive analysis provides an overview of the numerical variables in the Sales & Discounts dataset using mean, median, mode, and standard deviation. Histograms help identify the distribution and skewness of numerical variables, while box plots show the spread of the data and potential outliers. Bar charts provide an understanding of the frequency and distribution of categorical variables. Missing values and duplicate records were also examined as part of the preprocessing process. These analyses provide a useful foundation for further statistical analysis, visualization, and predictive modeling."""