# -*- coding: utf-8 -*-
"""Clustering.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1XX698IvzW7o7t5yThxG95BwhNENSx9CE
"""

## import libraries
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

from sklearn.preprocessing import StandardScaler
from sklearn.cluster import KMeans, DBSCAN
from sklearn.decomposition import PCA
from sklearn.metrics import silhouette_score, silhouette_samples
from sklearn.neighbors import NearestNeighbors

sns.set_style('whitegrid')
plt.rcParams['figure.figsize'] = (10, 6)

df = pd.read_excel('EastWestAirlines.xlsx', sheet_name='data')
df

df.head()

df.info()

df.shape

df.size

df.describe().T

df.isnull().sum()

df.duplicated().sum()

df_features = df.drop(columns=['ID#'])
df_features.head()

# Distrubution plot
df_features.hist(bins=30, figsize=(15, 12))
plt.suptitle("Distribution of Features", y=1.02)
plt.tight_layout()
plt.show()

for i in df.select_dtypes(include=['int','float']).columns:
  sns.boxplot(df[i])
  plt.show()

# Cap extreme outliers instead of deleting rows
def cap_outliers_iqr(data, factor=1.5):
    data = data.copy()
    for col in data.columns:
        Q1 = data[col].quantile(0.25)
        Q3 = data[col].quantile(0.75)
        IQR = Q3 - Q1
        lower = Q1 - factor * IQR
        upper = Q3 + factor * IQR
        data[col] = np.clip(data[col], lower, upper)
    return data
df_capped = cap_outliers_iqr(df_features)

# Compare before/after for one skewed column
fig, axes = plt.subplots(1, 2, figsize=(12, 4))
sns.boxplot(y=df_features['Bonus_miles'], ax=axes[0]).set_title('Bonus_miles - Before')
sns.boxplot(y=df_capped['Bonus_miles'], ax=axes[1]).set_title('Bonus_miles - After Capping')
plt.tight_layout()
plt.show()

# Correlation
plt.figure(figsize=(10, 8))
sns.heatmap(df_features.corr(), annot=True, fmt='.2f', cmap='coolwarm')
plt.title("Feature Correlation Heatmap")
plt.show()

# K-Means/DBSCAN are distance-based
scaler = StandardScaler()
scaled_array = scaler.fit_transform(df_capped)
scaled_df = pd.DataFrame(scaled_array, columns=df_capped.columns)
scaled_df.head()

pca = PCA(n_components=2, random_state=42)
pca_components = pca.fit_transform(scaled_df)
print("Explained variance ratio:", pca.explained_variance_ratio_)
print("Total variance captured:", pca.explained_variance_ratio_.sum())

wcss = []
K_range = range(1, 11)
for k in K_range:
    km = KMeans(n_clusters=k, init='k-means++', n_init=10, random_state=42)
    km.fit(scaled_df)
    wcss.append(km.inertia_)
plt.plot(K_range, wcss, marker='o')
plt.xlabel('Number of Clusters (K)')
plt.ylabel('WCSS (Inertia)')
plt.title('Elbow Method for Optimal K')
plt.xticks(K_range)
plt.show()

sil_scores = []
K_range_sil = range(2, 11)   # silhouette needs K >= 2
for k in K_range_sil:
    km = KMeans(n_clusters=k, init='k-means++', n_init=10, random_state=42)
    labels = km.fit_predict(scaled_df)
    score = silhouette_score(scaled_df, labels)
    sil_scores.append(score)
    print(f"K={k}, Silhouette Score={score:.4f}")
plt.plot(list(K_range_sil), sil_scores, marker='o', color='green')
plt.xlabel('Number of Clusters (K)')
plt.ylabel('Silhouette Score')
plt.title('Silhouette Score vs K')
plt.show()

# Fit final K-means model
optimal_k = 3
kmeans_final = KMeans(n_clusters=optimal_k, init='k-means++', n_init=10, random_state=42)
kmeans_labels = kmeans_final.fit_predict(scaled_df)
df['KMeans_Cluster'] = kmeans_labels
kmeans_sil = silhouette_score(scaled_df, kmeans_labels)
print(f"K-Means Silhouette Score (K={optimal_k}): {kmeans_sil:.4f}")
df['KMeans_Cluster'].value_counts()

## K-means cluster visuals
plt.figure(figsize=(8, 6))
sns.scatterplot(x=pca_components[:, 0], y=pca_components[:, 1],hue=kmeans_labels, palette='Set1', s=25, alpha=0.7)
plt.xlabel('PCA Component 1')
plt.ylabel('PCA Component 2')
plt.title(f'K-Means Clusters (K={optimal_k}) - PCA Projection')
plt.legend(title='Cluster')
plt.show()

## K-means cluster profiles
cluster_profile = df.groupby('KMeans_Cluster')[df_features.columns].mean()
cluster_profile['Count'] = df['KMeans_Cluster'].value_counts()
cluster_profile

# DBSCAN: find epsilon using k-distance graph
min_samples = 2 * scaled_df.shape[1]
neighbors = NearestNeighbors(n_neighbors=min_samples)
neighbors_fit = neighbors.fit(scaled_df)
distances, indices = neighbors_fit.kneighbors(scaled_df)

# Sort distances to the k-th nearest neighbor and plot (look for the "elbow/knee")
k_distances = np.sort(distances[:, -1])
plt.plot(k_distances)
plt.xlabel('Points sorted by distance')
plt.ylabel(f'{min_samples}-NN Distance')
plt.title('K-Distance Graph for DBSCAN eps Selection')
plt.show()

## Fit DBSCAN
eps_value = 2.5
dbscan = DBSCAN(eps=eps_value, min_samples=min_samples)
dbscan_labels = dbscan.fit_predict(scaled_df)
df['DBSCAN_Cluster'] = dbscan_labels
n_clusters = len(set(dbscan_labels)) - (1 if -1 in dbscan_labels else 0)
n_noise = list(dbscan_labels).count(-1)
print(f"Estimated number of clusters: {n_clusters}")
print(f"Number of noise points: {n_noise} ({n_noise/len(dbscan_labels)*100:.2f}%)")
df['DBSCAN_Cluster'].value_counts()

# Silhouette score is only meaningful if there are >=2 clusters (excluding noise)
mask = dbscan_labels != -1
if n_clusters >= 2:
    dbscan_sil = silhouette_score(scaled_df[mask], dbscan_labels[mask])
    print(f"DBSCAN Silhouette Score (excluding noise): {dbscan_sil:.4f}")
else:
    print("Not enough clusters formed to compute a silhouette score. Try adjusting eps/min_samples.")

# DBSCAN cluster visuals
plt.figure(figsize=(8, 6))
sns.scatterplot(x=pca_components[:, 0], y=pca_components[:, 1],hue=dbscan_labels, palette='tab10', s=25, alpha=0.7)
plt.xlabel('PCA Component 1')
plt.ylabel('PCA Component 2')
plt.title('DBSCAN Clusters - PCA Projection (Cluster -1 = Noise)')
plt.legend(title='Cluster')
plt.show()

dbscan_profile = df[df['DBSCAN_Cluster'] != -1].groupby('DBSCAN_Cluster')[df_features.columns].mean()
dbscan_profile['Count'] = df[df['DBSCAN_Cluster'] != -1]['DBSCAN_Cluster'].value_counts()
dbscan_profile

# Compare K-means vs cluster
comparison = pd.DataFrame({
    'Algorithm': ['K-Means', 'DBSCAN'],
    'Num_Clusters': [optimal_k, n_clusters],
    'Silhouette_Score': [kmeans_sil, dbscan_sil if n_clusters >= 2 else np.nan],
    'Handles_Noise': ['No', 'Yes'],
    'Assumes_Cluster_Shape': ['Spherical (convex)', 'Arbitrary shape']
})
comparison

"""# Customer Segmentation Using K-Means and DBSCAN

## 1. Objective

The objective of this project is to perform customer segmentation using unsupervised machine learning techniques.

The analysis applies:

* K-Means clustering
* DBSCAN clustering
* Principal Component Analysis (PCA)
* Silhouette Score
* Elbow Method

The goal is to identify meaningful groups of airline customers based on their travel activity, loyalty-program behavior, mileage, balance, and award-related characteristics.

---

# 2. Dataset Description

The dataset used is the **EastWestAirlines customer dataset**.

It contains:

**3,999 customers and 12 variables.**

The dataset includes customer information related to:

* Account balance
* Qualifying miles
* Credit-card miles
* Bonus miles
* Bonus transactions
* Flight miles during the previous 12 months
* Flight transactions during the previous 12 months
* Days since enrollment
* Award status

The `ID#` column is an identifier and was removed before clustering because it does not represent customer behavior.

---

# 3. Data Quality Analysis

The dataset contains:

* **3,999 observations**
* **12 original variables**
* **No missing values**
* **No duplicate records**

All variables were stored as integer values.

After removing the customer ID, **11 behavioral features** were used for clustering.

---

# 4. Exploratory Data Analysis

Distribution plots, box plots, and a correlation heatmap were created to understand the dataset.

The distributions showed that several variables were highly skewed and contained extreme values, particularly:

* Balance
* Qualifying miles
* Bonus miles
* Flight miles
* Flight transactions

Because extreme values can strongly influence distance-based clustering algorithms, an IQR-based outlier capping approach was applied instead of deleting customer records.

This preserves all customers while limiting the influence of extreme observations.

---

# 5. Outlier Treatment

An IQR-based method was used to cap extreme values.

The lower and upper boundaries were calculated using:

**Lower Bound = Q1 − 1.5 × IQR**

**Upper Bound = Q3 + 1.5 × IQR**

Values outside these boundaries were clipped to the corresponding limits.

This approach was selected because removing customers could result in valuable customer information being lost.

---

# 6. Feature Scaling

Since K-Means and DBSCAN are distance-based algorithms, the features were standardized using `StandardScaler`.

After scaling, the features have comparable scales, preventing variables with larger numerical ranges, such as Balance or Bonus miles, from dominating the clustering process.

---

# 7. PCA Analysis

PCA was performed with two components primarily for visualization.

The explained variance was:

| Component | Explained Variance |
| --------- | -----------------: |
| PC1       |         **43.38%** |
| PC2       |         **21.32%** |
| **Total** |         **64.70%** |

Therefore, the first two principal components capture approximately **64.70% of the total variance**.

The PCA representation was subsequently used to visualize the customer clusters in two dimensions.

---

# 8. K-Means Clustering

The Elbow Method was used to evaluate different values of K.

Silhouette scores were also calculated for values of K from 2 to 10.

### Silhouette Scores

|  K | Silhouette Score |
| -: | ---------------: |
|  2 |       **0.3191** |
|  3 |       **0.3087** |
|  4 |       **0.3071** |
|  5 |           0.2804 |
|  6 |           0.2412 |
|  7 |           0.2468 |
|  8 |           0.2505 |
|  9 |           0.2545 |
| 10 |           0.2601 |

Although K=2 produced the highest silhouette score, the notebook selected **K=3** based on the combination of the elbow analysis and the desire to create more meaningful customer segments.

---

# 9. Final K-Means Model

The final K-Means model was created with:

* Number of clusters = **3**
* Initialization = `k-means++`
* `n_init = 10`
* `random_state = 42`

The resulting silhouette score was:

**0.3087**

### Cluster Distribution

| Cluster   | Customers |
| --------- | --------: |
| Cluster 0 | **2,080** |
| Cluster 1 |   **824** |
| Cluster 2 | **1,095** |
| **Total** | **3,999** |

---

# 10. K-Means Cluster Profiles

The cluster profiles reveal three distinct customer segments.

### Cluster 0 – Lower-Value / Less Active Customers

Approximate characteristics:

* Balance: **35,487**
* Bonus miles: **3,765**
* Bonus transactions: **6.23**
* Flight miles in last 12 months: **41**
* Flight transactions: **0.14**
* Days since enrollment: **3,626**
* Award proportion: **16.25%**

This is the largest group and represents customers with relatively low balances, low mileage activity, and limited flight transactions.

### Cluster 1 – High-Activity / Frequent Flyers

Approximate characteristics:

* Balance: **128,222**
* Qualifying miles: **362**
* Bonus miles: **25,106**
* Bonus transactions: **17.25**
* Flight miles in last 12 months: **2,050**
* Flight transactions: **6.02**
* Days since enrollment: **4,511**
* Award proportion: **65.29%**

This group represents highly active customers with high flight activity and strong engagement with the airline's loyalty program.

### Cluster 2 – High-Value / Reward-Oriented Customers

Approximate characteristics:

* Balance: **104,898**
* Qualifying miles: **107**
* Credit-card miles: **3.65**
* Bonus miles: **36,569**
* Bonus transactions: **17.55**
* Flight miles in last 12 months: **60**
* Flight transactions: **0.21**
* Days since enrollment: **4,139**
* Award proportion: **53.79%**

This segment has high balances and bonus miles but relatively low recent flight activity, indicating customers who are strongly engaged with rewards but are not necessarily frequent recent flyers.

---

# 11. DBSCAN Clustering

DBSCAN was also applied to identify clusters and potential noise/outliers.

The number of features was used to determine `min_samples`:

**min_samples = 2 × number of features**

With 11 features:

**min_samples = 22**

The k-distance graph was used to determine a suitable epsilon value.

The selected value was:

**eps = 2.5**

---

# 12. DBSCAN Results

With `eps = 2.5` and `min_samples = 22`, DBSCAN produced:

**Number of clusters = 1**

**Number of noise points = 0**

Therefore:

**100% of the customers were assigned to a single DBSCAN cluster.**

The resulting cluster contains all **3,999 customers**.

Because only one cluster was formed, a silhouette score could not be calculated.

---

# 13. K-Means vs DBSCAN

| Algorithm   | Number of Clusters | Silhouette Score | Handles Noise | Cluster Shape    |
| ----------- | -----------------: | ---------------: | ------------- | ---------------- |
| **K-Means** |              **3** |       **0.3087** | No            | Spherical/convex |
| DBSCAN      |                  1 |              N/A | Yes           | Arbitrary        |

### Interpretation

K-Means successfully created three interpretable customer segments.

DBSCAN, with the selected parameters, did not identify multiple customer groups and instead assigned all observations to one cluster.

Therefore, K-Means was more useful for customer segmentation in this particular analysis.

---

# 14. Key Insights

### Insight 1 – Customer behavior is highly variable

The dataset shows substantial differences in customer balances, mileage, bonus transactions, and flight activity.

This makes customer segmentation useful for identifying different loyalty and engagement patterns.

### Insight 2 – Three meaningful customer groups were identified

K-Means divided customers into three segments:

1. Lower-value / less-active customers
2. High-value frequent flyers
3. High-value reward-oriented customers

### Insight 3 – Cluster 1 is highly engaged

Cluster 1 has the highest:

* Balance
* Qualifying miles
* Recent flight miles
* Flight transactions

It also has the highest proportion of customers with awards.

This segment can be considered the most active and valuable customer group based on the variables analyzed.

### Insight 4 – Cluster 2 is reward-oriented

Cluster 2 has the highest average **Bonus miles** and **Bonus transactions**, while recent flight activity is relatively low.

This suggests that these customers interact strongly with the airline's rewards program even though they are not frequent recent flyers.

### Insight 5 – Cluster 0 contains less-active customers

Cluster 0 has the lowest balance, bonus activity, and recent flight activity.

This segment may represent customers with relatively low engagement with the airline's loyalty program.

### Insight 6 – K-Means produced moderate separation

The final silhouette score for K=3 is:

**0.3087**

This indicates moderate cluster separation rather than highly distinct clusters.

Therefore, the segments are useful for exploratory customer profiling but should not be interpreted as perfectly separated customer populations.

### Insight 7 – DBSCAN was unsuccessful with the selected parameters

DBSCAN produced only one cluster and no noise points.

Therefore, it could not provide meaningful segmentation under the selected `eps` and `min_samples` values.

This also demonstrates that DBSCAN is sensitive to parameter selection.

---

# 15. Business Recommendations

### Cluster 0 – Low Engagement Customers

The airline could use:

* Personalized offers
* Re-engagement campaigns
* Bonus-mile promotions
* Targeted travel incentives

to encourage these customers to become more active.

### Cluster 1 – High-Value Frequent Flyers

These customers could be targeted with:

* Premium loyalty benefits
* Priority services
* Exclusive travel offers
* Upgrade opportunities
* Personalized rewards

Because they demonstrate strong flight activity and high balances, retaining this segment could be particularly valuable.

### Cluster 2 – Reward-Oriented Customers

The airline could encourage these customers to convert their high reward engagement into actual travel activity through:

* Bonus-mile redemption offers
* Targeted flight promotions
* Reward-based travel campaigns
* Personalized destination offers

---

# 16. Final Conclusion

The clustering analysis successfully segmented **3,999 EastWestAirlines customers** based on their behavioral and loyalty-program characteristics.

After removing the identifier column, treating extreme values through IQR-based capping, and standardizing the features, K-Means and DBSCAN were applied to the dataset.

PCA showed that the first two components explained approximately **64.70% of the total variance**, providing a useful two-dimensional representation for visualizing the clusters.

K-Means with **K=3** produced three meaningful customer segments and achieved a **silhouette score of 0.3087**. The clusters differed substantially in terms of balance, bonus miles, flight activity, and award participation.

The analysis identified:

* A large group of relatively low-engagement customers.
* A high-value group of frequent and highly active flyers.
* A high-value group with strong rewards engagement but relatively low recent flight activity.

DBSCAN, using `eps=2.5` and `min_samples=22`, produced only **one cluster with no noise points**, making it unsuitable for meaningful segmentation under the selected parameters.

Therefore, **K-Means was the more useful clustering algorithm for this dataset**. Although the silhouette score indicates only moderate separation, the resulting clusters are interpretable and can support customer profiling, targeted marketing, loyalty-program optimization, and customer-retention strategies.

## Final Findings

**Dataset:** 3,999 customers
**Features used:** 11 behavioral features
**PCA variance captured by 2 components:** 64.70%
**Selected K:** 3
**K-Means Silhouette Score:** 0.3087
**DBSCAN clusters:** 1
**DBSCAN noise:** 0
**Best method for segmentation:** K-Means

"""