# -*- coding: utf-8 -*-
"""Data Transformation Assignment.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1HjDoITSMDJ25cjMVk_AhIuaGcMLU6aT6
"""

import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
import warnings
warnings.filterwarnings('ignore')

from sklearn.preprocessing import StandardScaler
from sklearn.preprocessing import MinMaxScaler
from sklearn.preprocessing import OneHotEncoder
from sklearn.preprocessing import LabelEncoder

df=pd.read_csv('adult_with_headers (1).csv')
df

df.info()

df.describe()

df.shape

df.size

df.isnull().sum()

df.duplicated().sum()

df=df.replace("?", np.nan)

# Fill numerical missing values with median
num_cols = df.select_dtypes(include=np.number).columns
for col in num_cols:
    df[col] = df[col].fillna(df[col].median())

# Fill categorical missing values with mode
cat_cols = df.select_dtypes(include="object").columns
for col in cat_cols:
    df[col] = df[col].fillna(df[col].mode()[0])

df.isnull().sum()

## standard scaling
num_cols = df.select_dtypes(include=np.number).columns
sc = StandardScaler()
df_standard = df.copy()
df_standard[num_cols] = sc.fit_transform(df[num_cols])
df_standard.head()

## min-max scaling
minmax = MinMaxScaler()
df_minmax = df.copy()
df_minmax[num_cols] = minmax.fit_transform(df[num_cols])
df_minmax.head()

## Encoding sections
cat_cols = df.select_dtypes(include="object").columns
for col in cat_cols:
    print(col, ":", df[col].nunique())

##One-hot encoding
onehot_cols = []
for col in cat_cols:
    if df[col].nunique() < 5:
        onehot_cols.append(col)
print("Columns for One-Hot Encoding:")
print(onehot_cols)

df_onehot = pd.get_dummies(df,columns=onehot_cols,dtype=int)
df_onehot.head()

### Label-encoding
label_cols = []
for col in cat_cols:
    if df[col].nunique() > 5:
        label_cols.append(col)
print("Columns for Label Encoding:")
print(label_cols)

df_label = df.copy()
for col in label_cols:
    le = LabelEncoder()
    df_label[col] = le.fit_transform(df_label[col])
df_label.head()

# Feature 1: Total Capital
df["total_capital"] = (
    df["capital_gain"] + df["capital_loss"]
)
df[["capital_gain", "capital_loss", "total_capital"]].head()

#Feature 2: Age group
df["age_group"] = pd.cut(
    df["age"],
    bins=[0, 25, 40, 60, 100],
    labels=["Young", "Adult", "Middle_Aged", "Senior"]
)
df[["age", "age_group"]].head()

# Feature 3
df["work_intensity"] = pd.cut(
    df["hours_per_week"],
    bins=[0, 20, 40, 60, 100],
    labels=[
        "Part_Time",
        "Full_Time",
        "Overtime",
        "Very_High"
    ]
)
df[["hours_per_week", "work_intensity"]].head()

##Log tranasformation
df["capital_gain_log"] = np.log1p(df["capital_gain"])
df[["capital_gain", "capital_gain_log"]].head()

before = df["capital_gain"].skew()
after  = df["capital_gain_log"].skew()
print("Skewness before transformation:", before)
print("Skewness after transformation: ", after)
print(f"\nReduction in skewness: {before - after:.4f}")
print(f"Percent reduction: {((before - after) / before) * 100:.2f}%")

df.head()

df["income"] = df["income"].map({"<=50K": 0,">50K": 1})
print(df["income"].value_counts())

df["capital_gain_log"] = np.log1p(df["capital_gain"])
df["capital_loss_log"] = np.log1p(df["capital_loss"])

import matplotlib.pyplot as plt
plt.figure(figsize=(10, 5))
plt.hist(df["capital_gain"], bins=50)
plt.title("Capital Gain Before Log Transformation")
plt.xlabel("Capital Gain")
plt.ylabel("Frequency")
plt.show()

plt.figure(figsize=(10, 5))
plt.hist(df["capital_gain_log"], bins=50)
plt.title("Capital Gain After Log Transformation")
plt.xlabel("Log(Capital Gain + 1)")
plt.ylabel("Frequency")
plt.show()

df.to_csv("adult_preprocessed.csv", index=False)
print("dataset saved successfully!")

"""Final Assignment Conclusions

Missing values

The Adult dataset uses "?" to represent missing categorical information. These were converted to NaN and categorical variables were imputed using their mode, while numerical variables can be imputed using their median.

Scaling

Standard Scaling is appropriate when features have different scales and the ML algorithm benefits from standardized distributions.

Min-Max Scaling is useful when features need to be constrained to a fixed range such as [0,1].

Encoding

One-Hot Encoding was used for low-cardinality categorical variables such as sex, and race was also treated as one-hot because it has only five categories.

Label Encoding was applied to higher-cardinality variables such as workclass, education, occupation, and native_country, following the assignment requirement.

Feature Engineering

Three useful features were created:

1. net_capital = capital_gain - capital_loss

2. age_group = career-stage grouping based on age

3. work_intensity = grouping based on weekly working hours
Transformation

capital_gain is highly right-skewed, so:

np.log1p(capital_gain)

was applied to reduce the effect of extreme values and make the distribution less skewed.

Feature Selection

Isolation Forest can identify unusual observations, while PPS can identify predictive relationships, including nonlinear relationships that ordinary correlation may not capture.

This gives you a complete workflow:

EDA → Missing Value Treatment → Log Transformation → Encoding → Feature Engineering → Scaling → Isolation Forest → PPS Analysis → ML Model.   
"""