# -*- coding: utf-8 -*-
"""Data Structures, Functions, Numpy & Pandas.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1kv3t29YkVetJ4UCD9qXnwANYDlEDuSMj

**Section A: Data Structures & Control Structures**

1.	Create a list of 5 integers. Perform and print the result of the following operations: append, extend, insert, remove, pop, clear, index, count, sort, and reverse.
"""

s=[30,20,90,26,70]
print(s)
s.append(50)
print("After append",s)
s.extend([60,80])
print("After extend",s)
s.insert(4,54)
print("After insert",s)
s.remove(54)
print("Afer removing 54",s)
s.pop(5)
print("After pop",s)
s.index(26)
print("Index of 26 is",s.index(26))
s.count(70)
print("Count of 70 is",s.count(70))
s.sort()
print("After sorting",s)
s.reverse()
print("After reversing",s)
s.clear()
print("After clear",s)

"""2.	Create a tuple that stores 3 student names. Try changing the second name in the tuple. What happens? Explain why."""

names=["sanath","bhanu","akshay"]
print("Before changing",names)
names[1]="venu"
print("After changing",names)

"""3.	Create a set of integers with some duplicate values. Print the set and explain the output.

A set doesn't allow duplicate values.If we enter the duplicate values then the duplicate values were automatically removed
"""

numbers={10,10,20,30,30,40,40,50}
print(numbers)

"""4.	Create a dictionary with the keys: 'name', 'age', and 'city'. Update the age and add a new key 'email'. Print the final dictionary.

"""

info={
    "name":"sanath",
    "age":20,
    "city":"Huzurabad"
}
info["age"]=21
info["email"]="sanathcharanreddy@gmail.com"
print(info)

"""5. Write a script that checks if a person is eligible to vote (age ≥ 18).
Take age as a variable and print the appropriate message.

"""

age=int(input("enter the age of the person: "))
if age>=18:
  print("person is eligible to vote")
else:
  print("person age is below 18.so,he is not eligible to vote")

"""6.	Given a 'marks' variable, print the grade:
- 90 and above: 'A'
- 75–89: 'B'
- 50–74: 'C'
- Below 50: 'Fail'

"""

marks=int(input("enter the marks: "))
if marks>=90:
  print("above: A")
elif marks>=75 and marks<=89:
  print("B")
elif marks>=50 and marks<=74:
  print("C")
else:
  print("fail")

"""7.	Given a number, check if it's positive, and if it is also even. If not positive, print if it's zero or negative."""

n=int(input("enter the number: "))
if n>0:
  if n%2==0:
    print("the number is positive and even")
  else:
    print("the number is positive but not even")
else:
  if n==0:
    print("the number is zero")
  else:
    print("the number is negative")

"""**Section B: Numpy**
8.	Create:
- A scalar using np.array(5)
- A 1D array with values 1 to 5
- A 2D array (2x3) with values from 10 to 60 in steps of 10


"""

import numpy as np
scalar=np.array(5)
print("Scalar:")
print(scalar)
array_1d=np.array([1, 2, 3, 4, 5])
print("\n 1D Array:")
print(array_1d)
array_2d=np.array([
    [10,20,30],
    [40,50,60]
])
print("\n 2D Array:")
print(array_2d)

"""9.	Generate a 4x4 Numpy array of random integers between 0 and 100 using np.random.randint().

"""

random_array=np.random.randint(0,101,size=(4,4))
print("Random 4x4 Numpy Array:")
print(random_array)

"""10.	Create a 2D numpy array of shape (3x3). Convert it into a pandas DataFrame and add column names: 'A', 'B', 'C'."""

import pandas as pd
array=np.random.randint(0,101,size=(3,3))
df=pd.DataFrame(array,columns=['A','B','C'])
print(df)

"""**Section C: Exploring Pandas**

11.	Create a small DataFrame manually with 10 rows and columns: 'Name', 'Age', 'City', and 'Salary'. Then:
- Use .info(), .describe()
- Select 'Name' and 'City' columns
- Drop 'City' column
- Fill any missing values in 'Salary' column with the mean
- Remove any duplicate rows

"""

data={
    "name":['sanath','bhanu','akshay','venu','sai','ajay','sathwik','shiva','snehith','raju'],
    "age":[21,22,23,23,22,24,20,22,18,23],
    "city":['kkt','blnr','myr','hnk','wgl','mncl','bpl','gdk','hzb','knr'],
    "salary":[30000,35000,42000,40000,45000,np.nan,20000,69000,np.nan,24000]
}
df=pd.DataFrame(data)
print(df)

print("\n DataFrame Information ")
df.info()

print("\n Statistical Summary ")
print(df.describe())

print("\n Name and City Columns ")
print(df[['name', 'city']])

salary_mean=df['salary'].mean()
df['salary']=df['salary'].fillna(salary_mean)
print("\n After Filling Missing Salaries ")
print(df)

df = df.drop_duplicates()
print(df)

df = df.drop('city', axis=1)
print("\n After Dropping City ")
print(df)