# -*- coding: utf-8 -*-
"""Decision Tree Assign.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1J-MuBhcRltVTniZTUumcItohkIDGplQ_
"""

# import required librareies
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

from sklearn.model_selection import train_test_split, GridSearchCV
from sklearn.compose import ColumnTransformer
from sklearn.pipeline import Pipeline
from sklearn.preprocessing import OneHotEncoder
from sklearn.impute import SimpleImputer
from sklearn.tree import DecisionTreeClassifier, plot_tree
from sklearn.metrics import(accuracy_score,precision_score,recall_score,f1_score,roc_auc_score,classification_report,confusion_matrix,ConfusionMatrixDisplay,roc_curve)

import warnings
warnings.filterwarnings("ignore")

## Load dataset
df = pd.read_excel("heart_disease.xlsx", sheet_name="Heart_disease")
df

df.head()

df.info()

df.shape

df.size

df.describe()

df.isnull().sum()

df.duplicated().sum()

df=df.drop_duplicates()
print("Shape after removing duplicates:",df.shape)

for column in df.columns:
    print("\n", column)
    print(df[column].unique())

#Fix Inconsistent Values in exang
print(df["exang"].value_counts(dropna=False))

df["exang"] = df["exang"].astype(str).str.upper().str.strip()
df["exang"] = df["exang"].replace({
    "TRUE": True,
    "TURE": True,
    "FALSE": False
})
print(df["exang"].value_counts())

# Check target variable
print(df["num"].value_counts().sort_index())

df["target"] = (df["num"] > 0).astype(int)
print(df["target"].value_counts())

print(df["target"].value_counts(normalize=True)*100)

#Target distrubution
sns.countplot(x="target", data=df)
plt.title("Heart Disease Distribution")
plt.xlabel("Heart Disease")
plt.ylabel("Count")
plt.show()

# Histrogram
df.hist(
    figsize=(15, 10),
    bins=20
)
plt.tight_layout()
plt.show()

## Box plots
numeric_columns = [
    "age",
    "trestbps",
    "chol",
    "thalch",
    "oldpeak"
]
plt.figure(figsize=(15, 8))
for i, column in enumerate(numeric_columns, 1):
    plt.subplot(2, 3, i)
    sns.boxplot(y=df[column])
    plt.title(column)
plt.tight_layout()
plt.show()

#Correlation matrices
plt.figure(figsize=(10, 7))
correlation = df[numeric_columns + ["target"]].corr()
sns.heatmap(
    correlation,
    annot=True,
    cmap="coolwarm",
    fmt=".2f"
)
plt.title("Correlation Matrix")
plt.show()

# Feature vs target values
plt.figure(figsize=(8, 5))
sns.boxplot(
    x="target",
    y="age",
    data=df
)
plt.title("Age vs Heart Disease")
plt.xlabel("Heart Disease")
plt.ylabel("Age")
plt.show()

plt.figure(figsize=(8, 5))
sns.boxplot(
    x="target",
    y="chol",
    data=df
)
plt.title("Cholesterol vs Heart Disease")
plt.xlabel("Heart Disease")
plt.ylabel("Cholesterol")
plt.show()

X = df.drop(columns=["num", "target"])
y = df["target"]
print("X shape:", X.shape)
print("y shape:", y.shape)

# identify numerical columns
numeric_columns = X.select_dtypes(
    include=["int64", "float64"]
).columns.tolist()
print("Numerical columns:")
print(numeric_columns)

# identify Catagorical columns
categorical_columns = X.select_dtypes(
    include=["object", "bool"]
).columns.tolist()
print("\nCategorical columns:")
print(categorical_columns)

#Train test slpit
X_train, X_test, y_train, y_test = train_test_split(X,y,test_size=0.20,random_state=42,stratify=y)
print("Training data:", X_train.shape)
print("Testing data:", X_test.shape)

## feature engineering/process
numeric_transformer = Pipeline(
    steps=[
        ("imputer", SimpleImputer(strategy="median"))
    ]
)
categorical_transformer = Pipeline(
    steps=[
        ("imputer", SimpleImputer(strategy="most_frequent")),
        ("encoder", OneHotEncoder(
            handle_unknown="ignore",
            sparse_output=False
        ))
    ]
)

preprocessor = ColumnTransformer(
    transformers=[
        ("num", numeric_transformer, numeric_columns),
        ("cat", categorical_transformer, categorical_columns)
    ]
)

#Create decision tree model
decision_tree = DecisionTreeClassifier(random_state=42)

model = Pipeline(
    steps=[
        ("preprocessor", preprocessor),
        ("classifier", decision_tree)
    ]
)

# train the model
model.fit(X_train, y_train)
print("Decision Tree model trained successfully!")

# Make predictions
y_pred = model.predict(X_test)
y_prob = model.predict_proba(X_test)[:, 1]

# evaluate accuracy
accuracy = accuracy_score(y_test, y_pred)
print("Accuracy:", accuracy)

# precision
precision = precision_score(y_test, y_pred)
print("Precision:", precision)

# recall
recall = recall_score(y_test, y_pred)
print("Recall:", recall)

# f1-score
f1 = f1_score(y_test, y_pred)
print("F1 Score:", f1)

# ROC-AUC curve
roc_auc = roc_auc_score(y_test, y_prob)
print("ROC-AUC:", roc_auc)

print(classification_report(y_test, y_pred))

# confusion mtarix
cm = confusion_matrix(y_test, y_pred)
print(cm)
disp = ConfusionMatrixDisplay(
    confusion_matrix=cm,
    display_labels=["No Disease", "Disease"]
)
disp.plot()
plt.title("Decision Tree Confusion Matrix")
plt.show()

# Roc curve
fpr, tpr, thresholds = roc_curve(
    y_test,
    y_prob
)
plt.figure(figsize=(8, 6))
plt.plot(
    fpr,
    tpr,
    label=f"Decision Tree (AUC = {roc_auc:.2f})"
)
plt.plot(
    [0, 1],
    [0, 1],
    linestyle="--"
)
plt.xlabel("False Positive Rate")
plt.ylabel("True Positive Rate")
plt.title("ROC Curve")
plt.legend()
plt.show()

# Hyper tuning
param_grid = {
    "classifier__criterion": [
        "gini",
        "entropy",
        "log_loss"
    ],
    "classifier__max_depth": [
        3,
        5,
        7,
        10,
        None
    ],
    "classifier__min_samples_split": [
        2,
        5,
        10
    ],
    "classifier__min_samples_leaf": [
        1,
        2,
        5
    ]
}

# Gridsearch cv
grid_search = GridSearchCV(
    estimator=model,
    param_grid=param_grid,
    cv=5,
    scoring="f1",
    n_jobs=-1
)
grid_search.fit(X_train, y_train)
print("Hyperparameter tuning completed!")

# Best parameter
print("Best Parameters:")
print(grid_search.best_params_)

# best cross validation score
print("Best Cross Validation F1 Score:")
print(grid_search.best_score_)

# Evaluate tune model
best_model = grid_search.best_estimator_
y_pred_tuned = best_model.predict(X_test)
y_prob_tuned = best_model.predict_proba(X_test)[:, 1]

## tune model metrics
accuracy_tuned = accuracy_score(
    y_test,
    y_pred_tuned
)
precision_tuned = precision_score(
    y_test,
    y_pred_tuned
)
recall_tuned = recall_score(
    y_test,
    y_pred_tuned
)
f1_tuned = f1_score(
    y_test,
    y_pred_tuned
)
roc_auc_tuned = roc_auc_score(
    y_test,
    y_prob_tuned
)
print("Tuned Decision Tree Performance: ")
print("Accuracy :", accuracy_tuned)
print("Precision:", precision_tuned)
print("Recall   :", recall_tuned)
print("F1 Score :", f1_tuned)
print("ROC-AUC  :", roc_auc_tuned)

# Tuned classifiaction report
print(
    classification_report(
        y_test,
        y_pred_tuned
    )
)

## Compare before and after tuning
results = pd.DataFrame({
    "Metric": [
        "Accuracy",
        "Precision",
        "Recall",
        "F1 Score",
        "ROC-AUC"
    ],
    "Before Tuning": [
        accuracy,
        precision,
        recall,
        f1,
        roc_auc
    ],
    "After Tuning": [
        accuracy_tuned,
        precision_tuned,
        recall_tuned,
        f1_tuned,
        roc_auc_tuned
    ]
})
results

results.set_index("Metric").plot(
    kind="bar",
    figsize=(10, 6)
)
plt.title("Decision Tree Performance Before and After Tuning")
plt.ylabel("Score")
plt.ylim(0, 1)
plt.xticks(rotation=0)
plt.legend()
plt.show()

## Visual the decision tree
tree_model = best_model.named_steps["classifier"]

feature_names = (
    best_model
    .named_steps["preprocessor"]
    .get_feature_names_out()
)

plt.figure(figsize=(25, 15))
plot_tree(
    tree_model,
    feature_names=feature_names,
    class_names=["No Disease", "Disease"],
    filled=True,
    rounded=True,
    fontsize=8
)
plt.title("Optimized Decision Tree")
plt.show()

# Feature importance
importance = tree_model.feature_importances_
feature_importance = pd.DataFrame({
    "Feature": feature_names,
    "Importance": importance
})
feature_importance = feature_importance.sort_values(
    by="Importance",
    ascending=False
)
feature_importance.head(15)

top_features = feature_importance.head(15)
plt.figure(figsize=(10, 7))
sns.barplot(
    x="Importance",
    y="Feature",
    data=top_features
)
plt.title("Top 15 Important Features")
plt.xlabel("Importance")
plt.ylabel("Feature")
plt.show()

cm_tuned = confusion_matrix(
    y_test,
    y_pred_tuned
)
disp = ConfusionMatrixDisplay(
    confusion_matrix=cm_tuned,
    display_labels=["No Disease", "Disease"]
)
disp.plot()
plt.title("Tuned Decision Tree Confusion Matrix")
plt.show()

fpr, tpr, thresholds = roc_curve(
    y_test,
    y_prob_tuned
)
plt.figure(figsize=(8, 6))
plt.plot(
    fpr,
    tpr,
    label=f"Decision Tree AUC = {roc_auc_tuned:.2f}"
)
plt.plot(
    [0, 1],
    [0, 1],
    linestyle="--"
)
plt.xlabel("False Positive Rate")
plt.ylabel("True Positive Rate")
plt.title("ROC Curve - Tuned Decision Tree")
plt.legend()
plt.show()

print("FINAL MODEL PERFORMANCE : ")
print(f"Accuracy : {accuracy_tuned:.4f}")
print(f"Precision: {precision_tuned:.4f}")
print(f"Recall   : {recall_tuned:.4f}")
print(f"F1 Score : {f1_tuned:.4f}")
print(f"ROC-AUC  : {roc_auc_tuned:.4f}")
print("\nBest Hyperparameters:")
print(grid_search.best_params_)

"""# Decision Tree – Heart Disease Prediction Report

## 1. Objective

The objective of this project is to develop a **Decision Tree classification model** to predict the presence or absence of heart disease using demographic, clinical, and medical features.

The dataset contains **908 records and 13 variables** initially. After removing one duplicate record, the dataset contains **907 observations**. The target variable `num` contains five severity categories (0–4), which are converted into a binary target where 0 represents **No Disease** and values greater than 0 represent **Disease**.


## 2. Data Exploration

The dataset contains numerical and categorical variables.

### Numerical Features

* Age
* Resting blood pressure (`trestbps`)
* Cholesterol (`chol`)
* Maximum heart rate (`thalch`)
* ST depression (`oldpeak`)

### Categorical Features

* Sex
* Chest pain type (`cp`)
* Fasting blood sugar (`fbs`)
* Resting ECG (`restecg`)
* Exercise-induced angina (`exang`)
* Slope
* Thalassemia (`thal`)

The dataset initially contained **62 missing values in `oldpeak`** and **one duplicate record**. The duplicate record was removed before modelling.

The `exang` variable also contained inconsistent values such as `TURE` and string representations of `TRUE`/`FALSE`. These were standardized into Boolean values.

## 3. Target Variable

The original `num` variable contains five categories:

* 0 → No disease
* 1 → Disease
* 2 → Disease
* 3 → Disease
* 4 → Disease

A new binary target variable was therefore created:

**target = 0:** No Heart Disease
**target = 1:** Heart Disease

The resulting dataset contains:

* **399 observations (43.99%)** – No Disease
* **508 observations (56.01%)** – Disease

This indicates a relatively balanced target distribution, although the disease class is somewhat larger.


## 4. Data Preprocessing

The dataset was divided into training and testing sets using an **80:20 stratified split**.

* Training observations: **725**
* Testing observations: **182**

Numerical missing values were handled using **median imputation**, while categorical missing values were handled using the **most frequent value**.

Categorical variables were converted into numerical representations using **OneHotEncoder** with `handle_unknown="ignore"`.

The preprocessing and Decision Tree classifier were combined into a single **Pipeline**, ensuring that preprocessing was consistently applied during model training and prediction.

## 5. Initial Decision Tree Model

A Decision Tree Classifier was initially trained using the preprocessed training data.

### Initial Performance

| Metric    |  Score |
| --------- | -----: |
| Accuracy  | 73.63% |
| Precision | 74.55% |
| Recall    | 80.39% |
| F1 Score  | 77.36% |
| ROC-AUC   | 72.70% |

The model achieved a recall of approximately **80.39%**, meaning it successfully identified a relatively high proportion of patients belonging to the disease class.

## 6. Initial Confusion Matrix

The initial confusion matrix was:

|                   | Predicted No Disease | Predicted Disease |
| ----------------- | -------------------: | ----------------: |
| Actual No Disease |                   52 |                28 |
| Actual Disease    |                   20 |                82 |

Therefore:

* **52** cases were correctly identified as No Disease.
* **82** cases were correctly identified as Disease.
* **28** No Disease cases were incorrectly classified as Disease.
* **20** Disease cases were incorrectly classified as No Disease.

# 7. Hyperparameter Tuning

GridSearchCV with **5-fold cross-validation** was used to identify better Decision Tree parameters.

The model was optimized using **F1-score** as the scoring metric.

The parameters evaluated included:

* Criterion
* Maximum tree depth
* Minimum samples required for splitting
* Minimum samples required at a leaf

The best parameters were:

```text
criterion = entropy
max_depth = 5
min_samples_leaf = 1
min_samples_split = 10
```

The best cross-validation F1-score was approximately:

**0.7996**

# 8. Tuned Decision Tree Performance

After hyperparameter tuning, the model performance improved.

| Metric    | Before Tuning | After Tuning |
| --------- | ------------: | -----------: |
| Accuracy  |        73.63% |   **75.27%** |
| Precision |        74.55% |   **76.64%** |
| Recall    |        80.39% |   **80.39%** |
| F1 Score  |        77.36% |   **78.47%** |
| ROC-AUC   |        72.70% |   **78.22%** |

The tuned model therefore provided better overall performance than the initial Decision Tree.

# 9. Classification Performance

The tuned model produced the following classification performance:

| Class      | Precision | Recall | F1-Score |
| ---------- | --------: | -----: | -------: |
| No Disease |      0.73 |   0.69 |     0.71 |
| Disease    |      0.77 |   0.80 |     0.78 |

The disease class has a recall of approximately **80%**, which indicates that the model identifies most of the disease cases in the test dataset.

# 10. Final Conclusion

The Decision Tree model successfully classified patients into **No Heart Disease** and **Heart Disease** categories using demographic and clinical features.

The initial model achieved an accuracy of **73.63%**, F1-score of **77.36%**, and ROC-AUC of **72.70%**. After applying GridSearchCV-based hyperparameter tuning, the performance improved to an accuracy of **75.27%**, precision of **76.64%**, recall of **80.39%**, F1-score of **78.47%**, and ROC-AUC of **78.22%**.

The improvement demonstrates that selecting appropriate Decision Tree parameters can enhance model performance and generalization.

The tuned Decision Tree identified **asymptomatic chest pain, cholesterol, oldpeak, and age** among the most influential encoded features. Overall, the model provides a useful classification approach for this dataset, particularly because it achieves relatively strong recall for the disease class.

However, the model should be considered a **machine-learning prediction project rather than a medical diagnostic system**. Its predictions should not replace professional medical evaluation or clinical decision-making.

## Final Model

**Algorithm:** Decision Tree Classifier
**Best Criterion:** Entropy
**Maximum Depth:** 5
**Minimum Samples Split:** 10
**Minimum Samples Leaf:** 1
**Accuracy:** 75.27%
**Precision:** 76.64%
**Recall:** 80.39%
**F1 Score:** 78.47%
**ROC-AUC:** 78.22%

"""