# -*- coding: utf-8 -*-
"""EDA.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1EFYcqtvtwALJkzqQdARnsvv7bhzr7eox
"""

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
from scipy import stats
sns.set_theme(style="whitegrid", palette="Set2")
plt.rcParams["figure.figsize"] = (10, 6)
pd.set_option("display.max_columns", None)
pd.set_option("display.max_rows", 100)
pd.set_option("display.float_format", lambda x: f"{x:,.3f}")

df = pd.read_csv("Cardiotocographic.csv")
df.head()

df.info()

df.describe()

df.shape

df.size

df.dtypes

duplicate_count = df.duplicated().sum()
print("Number of duplicate rows:", duplicate_count)
if duplicate_count > 0:
    df = df.drop_duplicates().reset_index(drop=True)
    print("Duplicate rows removed.")
else:
    print("No duplicate rows found.")

missing_values=df.isnull().sum()
missing_percentage=(df.isnull().sum() / len(df)) * 100
missing_summary=pd.DataFrame({"Missing Values": missing_values,"Missing Percentage": missing_percentage})
missing_summary=missing_summary.sort_values(by="Missing Values", ascending=False)
display(missing_summary)

plt.figure(figsize=(12, 5))
sns.heatmap(df.isnull(),cbar=False,yticklabels=False,cmap="viridis")
plt.title("Missing Values Heatmap")
plt.xlabel("Variables")
plt.show()

numeric_cols = df.select_dtypes(include=np.number).columns.tolist()
categorical_cols = df.select_dtypes(exclude=np.number).columns.tolist()
print("Numerical columns:")
print(numeric_cols)
print("\nCategorical columns:")
print(categorical_cols)
for col in numeric_cols:
    if df[col].isnull().sum() > 0:
        df[col] = df[col].fillna(df[col].median())
for col in categorical_cols:
    if df[col].isnull().sum() > 0:
        df[col] = df[col].fillna(df[col].mode()[0])
print("Missing-value treatment completed.")
print("Total remaining missing values:", df.isnull().sum().sum())

for col in df.columns:
    if df[col].dtype == "object":
        converted = pd.to_numeric(df[col], errors="coerce")
        if converted.notna().mean() > 0.90:
            df[col] = converted
print("Data types after conversion:")
display(df.dtypes.to_frame(name="Data Type"))
numeric_cols = df.select_dtypes(include=np.number).columns.tolist()
categorical_cols = df.select_dtypes(exclude=np.number).columns.tolist()
print("Numerical columns:", numeric_cols)
print("Categorical columns:", categorical_cols)

statistical_summary = df[numeric_cols].describe().T
statistical_summary["median"] = df[numeric_cols].median()
statistical_summary["IQR"] = (
    df[numeric_cols].quantile(0.75)
    - df[numeric_cols].quantile(0.25)
)
statistical_summary = statistical_summary[["count", "mean", "median", "std", "min", "25%", "50%", "75%", "max", "IQR"]]
display(statistical_summary)

additional_stats = pd.DataFrame(index=numeric_cols)
additional_stats["Mean"] = df[numeric_cols].mean()
additional_stats["Median"] = df[numeric_cols].median()
additional_stats["Standard Deviation"] = df[numeric_cols].std()
additional_stats["Variance"] = df[numeric_cols].var()
additional_stats["Minimum"] = df[numeric_cols].min()
additional_stats["Maximum"] = df[numeric_cols].max()
additional_stats["IQR"] = (
    df[numeric_cols].quantile(0.75)
    - df[numeric_cols].quantile(0.25)
)
additional_stats["Skewness"] = df[numeric_cols].skew()
additional_stats["Kurtosis"] = df[numeric_cols].kurtosis()
display(additional_stats.round(3))

for col in categorical_cols:
    print(f"\nFrequency distribution for: {col}")
    display(df[col].value_counts(dropna=False))
df[numeric_cols].hist(
    bins=25,
    figsize=(16, 14),
    edgecolor="black"
)
plt.suptitle("Distributions of Numerical Variables", fontsize=18)
plt.tight_layout()
plt.show()

n_cols = 3
n_rows = int(np.ceil(len(numeric_cols) / n_cols))
fig, axes = plt.subplots(
    n_rows,
    n_cols,
    figsize=(16, 4 * n_rows)
)
axes = np.array(axes).reshape(-1)
for i, col in enumerate(numeric_cols):
    sns.boxplot(
        y=df[col],
        ax=axes[i],
        color="skyblue"
    )
    axes[i].set_title(f"Boxplot of {col}")
for j in range(len(numeric_cols), len(axes)):
    axes[j].set_visible(False)
plt.tight_layout()
plt.show()

outlier_summary = []
for col in numeric_cols:
    Q1 = df[col].quantile(0.25)
    Q3 = df[col].quantile(0.75)
    IQR = Q3 - Q1
    lower_bound = Q1 - 1.5 * IQR
    upper_bound = Q3 + 1.5 * IQR
    outliers = df[
        (df[col] < lower_bound) |
        (df[col] > upper_bound)
    ]
    outlier_summary.append({
        "Variable": col,
        "Q1": Q1,
        "Q3": Q3,
        "IQR": IQR,
        "Lower Bound": lower_bound,
        "Upper Bound": upper_bound,
        "Outlier Count": len(outliers),
        "Outlier Percentage": (len(outliers) / len(df)) * 100
    })
outlier_df = pd.DataFrame(outlier_summary)
display(outlier_df.round(3))

df_analysis = df.copy()
for col in numeric_cols:
    Q1 = df[col].quantile(0.25)
    Q3 = df[col].quantile(0.75)
    IQR = Q3 - Q1
    lower_bound = Q1 - 1.5 * IQR
    upper_bound = Q3 + 1.5 * IQR
    df_analysis[f"{col}_outlier"] = (
        (df[col] < lower_bound) |
        (df[col] > upper_bound)
    )
print("Outliers have been flagged rather than automatically removed.")

correlation_matrix = df[numeric_cols].corr()
plt.figure(figsize=(14, 10))
sns.heatmap(
    correlation_matrix,
    annot=True,
    fmt=".2f",
    cmap="coolwarm",
    center=0,
    linewidths=0.5
)
plt.title("Correlation Heatmap")
plt.tight_layout()
plt.show()
corr_pairs = correlation_matrix.where(
    np.triu(np.ones(correlation_matrix.shape), k=1).astype(bool)
)
corr_pairs = corr_pairs.stack().reset_index()
corr_pairs.columns = ["Variable 1", "Variable 2", "Correlation"]
corr_pairs["Absolute Correlation"] = corr_pairs["Correlation"].abs()
corr_pairs = corr_pairs.sort_values(
    "Absolute Correlation",
    ascending=False
)
display(corr_pairs.head(15).round(3))

if len(corr_pairs) > 0:
    strongest = corr_pairs.iloc[0]
    x = strongest["Variable 1"]
    y = strongest["Variable 2"]
    plt.figure(figsize=(9, 6))
    sns.scatterplot(
        data=df,
        x=x,
        y=y,
        alpha=0.6
    )
    sns.regplot(
        data=df,
        x=x,
        y=y,
        scatter=False,
        color="red"
    )
    plt.title(
        f"{x} vs {y} "
        f"(Correlation = {strongest['Correlation']:.2f})"
    )
    plt.show()

for col in categorical_cols:
    plt.figure(figsize=(10, 5))
    order = df[col].value_counts().index
    sns.countplot(
        data=df,
        x=col,
        order=order
    )
    plt.title(f"Frequency Distribution of {col}")
    plt.xticks(rotation=45)
    plt.tight_layout()
    plt.show()

possible_targets = [
    col for col in df.columns
    if col.upper() in ["NSP", "CLASS", "TARGET", "LABEL", "CLASSIFICATION"]
]
print("Potential target/classification columns:", possible_targets)

if possible_targets:
    target = possible_targets[0]
    print(f"Using '{target}' as the target/classification variable.")
    print(df[target].value_counts())
    plt.figure(figsize=(8, 5))
    sns.countplot(
        data=df,
        x=target,
        order=df[target].value_counts().index
    )
    plt.title(f"Distribution of {target}")
    plt.show()
else:
    print("No obvious classification column was automatically identified.")

if possible_targets:
    target = possible_targets[0]
    if target in numeric_cols:
        target_numeric = True
    else:
        target_numeric = False
    for col in numeric_cols:
        if col != target:
            plt.figure(figsize=(9, 5))
            if target_numeric:
                sns.scatterplot(
                    data=df,
                    x=col,
                    y=target,
                    alpha=0.5
                )
            else:
                sns.boxplot(
                    data=df,
                    x=target,
                    y=col
                )
            plt.title(f"{col} vs {target}")
            plt.xticks(rotation=45)
            plt.tight_layout()
            plt.show()

#group stastics
if possible_targets:
    target = possible_targets[0]
    grouped_statistics = df.groupby(target)[numeric_cols].agg(
        ["mean", "median", "std"]
    )
    display(grouped_statistics.round(3))
if possible_targets:
    target = possible_targets[0]
    if target in df.columns:
        class_means = df.groupby(target)[numeric_cols].mean()
        plt.figure(figsize=(14, 8))
        sns.heatmap(
            class_means.T,
            annot=True,
            fmt=".2f",
            cmap="YlGnBu"
        )
        plt.title(
            f"Mean Numerical Values by {target} Category"
        )
        plt.xlabel(target)
        plt.ylabel("Variables")
        plt.tight_layout()
        plt.show()
variance_summary = pd.DataFrame({
    "Variance": df[numeric_cols].var(),
    "Unique Values": df[numeric_cols].nunique()
})
display(
    variance_summary.sort_values("Variance")
)

threshold = 0.70
high_correlations = corr_pairs[corr_pairs["Absolute Correlation"] >= threshold]
print(f"Variable pairs with absolute correlation >= {threshold}:")
display(high_correlations.round(3))

print("Final dataset dimensions:", df.shape)
print("\nNumerical variables:")
print(len(numeric_cols))
print("\nCategorical variables:")
print(len(categorical_cols))
print("\nMissing values:")
print(df.isnull().sum().sum())
print("\nDuplicate rows:")
print(df.duplicated().sum())

"""**Brief Report**

The exploratory data analysis of the cardiographic dataset provided an overall understanding of its structure, numerical variables, distributions, and relationships. The dataset was first inspected for data types, missing values, and duplicate observations. Missing numerical values were handled using median imputation, while categorical missing values were addressed using the mode where applicable.

Descriptive statistics including mean, median, standard deviation, and interquartile range were calculated to understand the central tendency and variability of the variables. Histograms and boxplots were used to examine distributions and identify potential outliers.

Correlation analysis and heatmaps were used to investigate relationships among cardiographic measurements. Pair plots and scatter plots provided additional insight into possible relationships and patterns between variables. Categorical variables, where present, were analyzed using frequency counts and bar charts.

The analysis provides a foundation for subsequent statistical or machine-learning analysis. In particular, variables showing strong relationships may warrant further investigation, while potential outliers should be examined to determine whether they represent genuine observations or data-quality issues.

Because this is a cardiographic dataset, statistical associations should be interpreted carefully and should not by themselves be treated as clinical conclusions. Further analysis could include feature selection, statistical hypothesis testing, classification modeling, and validation using an appropriate target variable if one is available.
"""