# -*- coding: utf-8 -*-
"""hypothesis testing.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1Py00gi8kAfLBCTWq358wIDxFLqy5YQ5y

**Confidence Intervel**
"""

import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
from scipy import stats

# Durability data
data = [1.13, 1.55, 1.43, 0.92, 1.25, 1.36, 1.32,0.85, 1.07, 1.48, 1.20, 1.33, 1.18, 1.22, 1.29]

# Sample size
n = len(data)

# Sample mean
mean = np.mean(data)

# Sample standard deviation
s = np.std(data, ddof=1)
print("Sample Size (n):", n)
print("Sample Mean:", round(mean, 4))
print("Sample Standard Deviation:", round(s, 4))

"""a. Build 99% Confidence Interval Using Sample Standard Deviation

Assuming the sample is representative of the population, construct a 99% confidence interval for the mean number of characters printed before the print-head fails using the sample standard deviation. Explain the steps you take and the rationale behind using the t-distribution for this task.

"""

confidence_level = 0.99
# Significance level
alpha = 1 - confidence_level
# Degrees of freedom
df = n - 1
# t critical value
t_critical = stats.t.ppf(1 - alpha/2, df)
# Standard Error
standard_error = s / np.sqrt(n)
# Margin of Error
margin_error = t_critical * standard_error
# Confidence Interval
lower_limit = mean - margin_error
upper_limit = mean + margin_error
print("Degrees of Freedom:", df)
print("t-critical value:", round(t_critical, 4))
print("Standard Error:", round(standard_error, 4))
print("Margin of Error:", round(margin_error, 4))
print("Lower Limit:", round(lower_limit, 4))
print("Upper Limit:", round(upper_limit, 4))
print("99% Confidence Interval:",(round(lower_limit, 4), round(upper_limit, 4)))

"""b. Build 99% Confidence Interval Using Known Population Standard Deviation

If it were known that the population standard deviation is 0.2 million characters, construct a 99% confidence interval for the mean number of characters printed before failure.

"""

population_sd = 0.2
# Z critical value for 99% confidence
z_critical = stats.norm.ppf(1 - alpha/2)
# Standard Error
standard_error_z = population_sd / np.sqrt(n)
# Margin of Error
margin_error_z = z_critical * standard_error_z
# Confidence Interval
lower_limit_z = mean - margin_error_z
upper_limit_z = mean + margin_error_z
print("Z-critical value:", round(z_critical, 4))
print("Standard Error:", round(standard_error_z, 4))
print("Margin of Error:", round(margin_error_z, 4))
print("Lower Limit:", round(lower_limit_z, 4))
print("Upper Limit:", round(upper_limit_z, 4))
print("99% Confidence Interval:",(round(lower_limit_z, 4), round(upper_limit_z, 4)))

#Finall comparision
print("FINAL RESULTS:")
print()

print("t-distribution:")
print("99% CI =", (round(lower_limit, 4), round(upper_limit, 4)),
      "million characters")

print("Z-distribution:")
print("99% CI =", (round(lower_limit_z, 4), round(upper_limit_z, 4)),
      "million characters")

"""**Hypothesis testing**"""

import math
from scipy.stats import norm

# Step 1: Hypotheses
# H0: population mean weekly cost = theoretical mean
# H1: population mean weekly cost > theoretical mean

fixed_cost = 1000
cost_per_unit = 5
mean_units = 600
std_units = 25
sample_mean_cost = 3050
sample_size = 25
alpha = 0.05

"""**Hypothesis are:**

Null hypothesis (H0): μ=4000. The mean weekly operating cost equals the theoretical cost.

Alternative hypothesis (H1): μ>4000. The mean weekly operating cost is higher than the theoretical cost.
"""

# Step 2: Theoretical mean, standard deviation, and Z statistic
mu_0 = fixed_cost + cost_per_unit * mean_units
sigma = cost_per_unit * std_units
standard_error = sigma / sqrt(sample_size)
z = (sample_mean_cost - mu_0) / standard_error
print("Theoretical mean:", mu_0)
print("Standard deviation:", sigma)
print("Z-statistic:", z)

# Step 3: DETERMINE THE P-VALUE
print("P-VALUE: ")
print()
p_value = 1 - norm.cdf(z)
print("P-value =", round(p_value, 6))

# Step 4: FIND THE CRITICAL VALUE
print("CRITICAL VALUE:")
print()
critical_value = norm.ppf(1 - alpha)
print("Significance Level (alpha) =", alpha)
print("Critical Z-value =", round(critical_value, 4))

# Step 5: DECISION
print("DECISION")
print()
print("Calculated Z =", round(z, 4))
print("Critical Z =", round(critical_value, 4))

if z > critical_value:
    decision = "Reject H0"
    print("\nDecision: Reject the Null Hypothesis (H0)")
else:
    decision = "Fail to Reject H0"
    print("\nDecision: Fail to Reject the Null Hypothesis(H0)")

# CONCLUSION
print("CONCLUSION")
print()

if z > critical_value:
    print("There is strong evidence that the mean weekly")
    print("operating cost is higher than the theoretical model suggests.")
else:
    print("There is not enough evidence to conclude that the mean")
    print("weekly operating cost is higher than the theoretical model.")

print("\nFinal Result:")
print("Theoretical Mean Cost = Rs.", mean_units)
print("Sample Mean Cost = Rs.", sample_mean_cost)
print("Z-statistic =", round(z, 4))
print("P-value =", round(p_value, 6))
print("Critical Value =", round(critical_value, 4))
print("Decision =", decision)

"""# Hypothesis Testing Report

## 1. Objective

The objective of this analysis is to determine whether there is sufficient statistical evidence to support the restaurant owners' claim that the mean weekly operating cost is higher than the theoretical cost predicted by the existing model.

The theoretical cost model is:

**W = 1000 + 5X**

where X represents the number of units produced per week.

Given that the mean production is 600 units, the theoretical mean weekly operating cost is:

**W = 1000 + (5 × 600) = ₹4,000**

A sample of 25 restaurants has an observed mean weekly operating cost of **₹3,050**.


## 2. Hypotheses

The hypotheses for the right-tailed test are:

**H₀:** μ = ₹4,000
The mean weekly operating cost is equal to the theoretical cost.

**H₁:** μ > ₹4,000
The mean weekly operating cost is greater than the theoretical cost.

The significance level is:

**α = 0.05**

## 3. Calculation of Standard Deviation

The standard deviation of the number of units produced is 25 units.

Since:

**W = 1000 + 5X**

the standard deviation of weekly operating cost is:

**σW = 5 × 25 = ₹125**

The standard error is:

**SE = σ / √n**

**SE = 125 / √25 = ₹25**

## 4. Test Statistic

The Z-test statistic is calculated as:

**Z = (x̄ − μ) / (σ / √n)**

Substituting the values:

**Z = (3050 − 4000) / 25**

**Z = −38.00**

Therefore, the calculated Z-statistic is **−38.00**.

## 5. P-Value and Critical Value

Since this is a right-tailed test, the p-value is calculated as:

**P-value = 1 − Φ(Z)**

The calculated p-value is approximately:

**P-value = 1.000000**

At a 5% significance level, the critical Z-value for a right-tailed test is:

**Zcritical = 1.6449**


## 6. Decision

The decision rule is:

* If Z > 1.6449 → Reject H₀
* If Z ≤ 1.6449 → Fail to Reject H₀

The calculated value is:

**Z = −38.00**

Since:

**−38.00 < 1.6449**

we **fail to reject the null hypothesis**.



# 7. Conclusion

Based on the hypothesis test, there is **not enough statistical evidence to conclude that the mean weekly operating cost is higher than ₹4,000**, which is the amount predicted by the theoretical cost model.

In fact, the sample mean weekly operating cost is **₹3,050**, which is ₹950 lower than the theoretical mean of ₹4,000. The extremely negative Z-statistic of **−38.00** indicates that the observed sample mean is far below the hypothesized mean rather than above it.

Therefore, at the **5% significance level**, the restaurant owners' claim that weekly operating costs have increased is **not supported by the given sample data**.

The analysis supports the conclusion that the existing theoretical cost model of ₹4,000 per week cannot be rejected in favor of the claim that the mean cost is higher.


# 8. Key Insights

### Insight 1 — Theoretical cost

The expected weekly operating cost according to the model is **₹4,000** when the average production is 600 units.

### Insight 2 — Observed cost

The observed sample mean is only **₹3,050**, which is **₹950 lower** than the theoretical cost.

### Insight 3 — Large negative Z-statistic

The calculated Z-statistic is **−38.00**, showing an extremely large difference between the sample mean and the hypothesized mean in the negative direction.

### Insight 4 — P-value

The p-value is **1.000000**, which is much greater than the significance level of **0.05**. Therefore, there is no statistical evidence to reject H₀ in favor of H₁.

### Insight 5 — Decision

The correct statistical decision is:

**Fail to Reject H₀**

This does not mean that we prove H₀ is true. It means that the sample does not provide sufficient evidence to support the claim that the mean weekly cost is greater than ₹4,000.

### Insight 6 — Business interpretation

From a business perspective, the sample does **not indicate an increase in operating costs**. Instead, the observed average cost is substantially below the theoretical model's expected cost.

## Overall Conclusion

The hypothesis testing analysis shows that the restaurant owners' claim of **higher weekly operating costs is not supported by the sample data**. The sample mean of ₹3,050 is considerably lower than the theoretical mean of ₹4,000, resulting in a Z-statistic of −38.00 and a p-value of 1.00. Hence, at the 5% significance level, we fail to reject the null hypothesis.

"""

