# -*- coding: utf-8 -*-
"""hypothesis testing.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1Py00gi8kAfLBCTWq358wIDxFLqy5YQ5y

**Confidence Intervel**
"""

import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
from scipy import stats

# Durability data
data = [1.13, 1.55, 1.43, 0.92, 1.25, 1.36, 1.32,0.85, 1.07, 1.48, 1.20, 1.33, 1.18, 1.22, 1.29]

# Sample size
n = len(data)

# Sample mean
mean = np.mean(data)

# Sample standard deviation
s = np.std(data, ddof=1)
print("Sample Size (n):", n)
print("Sample Mean:", round(mean, 4))
print("Sample Standard Deviation:", round(s, 4))

"""a. Build 99% Confidence Interval Using Sample Standard Deviation

Assuming the sample is representative of the population, construct a 99% confidence interval for the mean number of characters printed before the print-head fails using the sample standard deviation. Explain the steps you take and the rationale behind using the t-distribution for this task.

"""

confidence_level = 0.99
# Significance level
alpha = 1 - confidence_level
# Degrees of freedom
df = n - 1
# t critical value
t_critical = stats.t.ppf(1 - alpha/2, df)
# Standard Error
standard_error = s / np.sqrt(n)
# Margin of Error
margin_error = t_critical * standard_error
# Confidence Interval
lower_limit = mean - margin_error
upper_limit = mean + margin_error
print("Degrees of Freedom:", df)
print("t-critical value:", round(t_critical, 4))
print("Standard Error:", round(standard_error, 4))
print("Margin of Error:", round(margin_error, 4))
print("Lower Limit:", round(lower_limit, 4))
print("Upper Limit:", round(upper_limit, 4))
print("99% Confidence Interval:",(round(lower_limit, 4), round(upper_limit, 4)))

"""b. Build 99% Confidence Interval Using Known Population Standard Deviation

If it were known that the population standard deviation is 0.2 million characters, construct a 99% confidence interval for the mean number of characters printed before failure.

"""

population_sd = 0.2
# Z critical value for 99% confidence
z_critical = stats.norm.ppf(1 - alpha/2)
# Standard Error
standard_error_z = population_sd / np.sqrt(n)
# Margin of Error
margin_error_z = z_critical * standard_error_z
# Confidence Interval
lower_limit_z = mean - margin_error_z
upper_limit_z = mean + margin_error_z
print("Z-critical value:", round(z_critical, 4))
print("Standard Error:", round(standard_error_z, 4))
print("Margin of Error:", round(margin_error_z, 4))
print("Lower Limit:", round(lower_limit_z, 4))
print("Upper Limit:", round(upper_limit_z, 4))
print("99% Confidence Interval:",(round(lower_limit_z, 4), round(upper_limit_z, 4)))

#Finall comparision
print("FINAL RESULTS:")
print()

print("t-distribution:")
print("99% CI =", (round(lower_limit, 4), round(upper_limit, 4)),
      "million characters")

print("Z-distribution:")
print("99% CI =", (round(lower_limit_z, 4), round(upper_limit_z, 4)),
      "million characters")

"""**Hypothesis testing**"""

import math
from scipy.stats import norm

# Step 1: Hypotheses
# H0: population mean weekly cost = theoretical mean
# H1: population mean weekly cost > theoretical mean

fixed_cost = 1000
cost_per_unit = 5
mean_units = 600
std_units = 25
sample_mean_cost = 3050
sample_size = 25
alpha = 0.05

"""**Hypothesis are:**

Null hypothesis (H0): μ=4000. The mean weekly operating cost equals the theoretical cost.

Alternative hypothesis (H1): μ>4000. The mean weekly operating cost is higher than the theoretical cost.
"""

# Step 2: Theoretical mean, standard deviation, and Z statistic
mu_0 = fixed_cost + cost_per_unit * mean_units
sigma = cost_per_unit * std_units
standard_error = sigma / sqrt(sample_size)
z = (sample_mean_cost - mu_0) / standard_error
print("Theoretical mean:", mu_0)
print("Standard deviation:", sigma)
print("Z-statistic:", z)

# Step 3: DETERMINE THE P-VALUE
print("P-VALUE: ")
print()
p_value = 1 - norm.cdf(z)
print("P-value =", round(p_value, 6))

# Step 4: FIND THE CRITICAL VALUE
print("CRITICAL VALUE:")
print()
critical_value = norm.ppf(1 - alpha)
print("Significance Level (alpha) =", alpha)
print("Critical Z-value =", round(critical_value, 4))

# Step 5: DECISION
print("DECISION")
print()
print("Calculated Z =", round(z, 4))
print("Critical Z =", round(critical_value, 4))

if z > critical_value:
    decision = "Reject H0"
    print("\nDecision: Reject the Null Hypothesis (H0)")
else:
    decision = "Fail to Reject H0"
    print("\nDecision: Fail to Reject the Null Hypothesis(H0)")

# CONCLUSION
print("CONCLUSION")
print()

if z > critical_value:
    print("There is strong evidence that the mean weekly")
    print("operating cost is higher than the theoretical model suggests.")
else:
    print("There is not enough evidence to conclude that the mean")
    print("weekly operating cost is higher than the theoretical model.")

print("\nFinal Result:")
print("Theoretical Mean Cost = Rs.", mean_units)
print("Sample Mean Cost = Rs.", sample_mean_cost)
print("Z-statistic =", round(z, 4))
print("P-value =", round(p_value, 6))
print("Critical Value =", round(critical_value, 4))
print("Decision =", decision)

