# -*- coding: utf-8 -*-
"""Logistic Regression Assessment.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1LjqfScGZ34UOUdSuP4KIYlTPTQxBI81K
"""

# Install required packages for Streamlit deployment
!pip install -q streamlit pyngrok joblib

# required libraries
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import accuracy_score,precision_score,recall_score,f1_score,roc_auc_score,roc_curve,classification_report,confusion_matrix
import joblib

# Load the diabetes dataset
df=pd.read_csv("diabetes.csv")
df.head()

df.shape

df.size

"""**Perform exploratory data analysis**"""

print("Data Types:")
df.dtypes

print("Summary Statistics:")
df.describe()

print("\nMissing Values:")
df.isnull().sum()

print("Duplicate Rows:")
df.duplicated().sum()

print("Target Distribution:")
df["Outcome"].value_counts()

"""**Visualize feature distributions and correlations**"""

df.hist(figsize=(15,12))
plt.tight_layout()
plt.show()

plt.figure(figsize=(10,6))
sns.boxplot(data=df)
plt.xticks(rotation=45)
plt.title("Box Plot of Features")
plt.show()

plt.figure(figsize=(10,8))
sns.heatmap(df.corr(),annot=True,cmap="coolwarm")
plt.title("Correlation Matrix")
plt.show()

X=df.drop(columns=["Outcome"])
y=df["Outcome"]
missing_values=["Glucose","BloodPressure","SkinThickness","Insulin","BMI"]
for col in missing_values:
    X[col]=X[col].replace(0,np.nan)
    X[col]=X[col].fillna(X[col].median())
print("Missing Values After Imputation:")
print(X.isnull().sum())

X_train,X_test,y_train,y_test=train_test_split(X,y,test_size=0.20,random_state=42,stratify=y)
scaler=StandardScaler()
X_train_scaled=scaler.fit_transform(X_train)
X_test_scaled=scaler.transform(X_test)
print("Training Samples:",len(X_train))
print("Testing Samples:",len(X_test))

"""**Build and train the Logistic Regression model**"""

model=LogisticRegression(max_iter=1000)
model.fit(X_train_scaled,y_train)
y_pred=model.predict(X_test_scaled)
y_prob=model.predict_proba(X_test_scaled)[:,1]
print("Model trained successfully.")
print(classification_report(y_test,y_pred))

"""**Evaluate the Logistic Regression model**"""

accuracy=accuracy_score(y_test,y_pred)
print("Accuracy:",accuracy)

precision=precision_score(y_test,y_pred)
print("Precision:",precision)

recall=recall_score(y_test,y_pred)
print("Recall:",recall)

f1=f1_score(y_test,y_pred)
print("F1-Score:",f1)

roc_auc=roc_auc_score(y_test,y_prob)
print("ROC-AUC:",roc_auc)

print("\nConfusion Matrix:")
print(confusion_matrix(y_test,y_pred))

"""**Plot the ROC curve**"""

fpr,tpr,thresholds=roc_curve(y_test,y_prob)
plt.figure(figsize=(8,6))
plt.plot(fpr,tpr,label=f"ROC-AUC = {roc_auc:.3f}")
plt.plot([0,1],[0,1],linestyle="--")
plt.xlabel("False Positive Rate")
plt.ylabel("True Positive Rate")
plt.title("ROC Curve")
plt.legend()
plt.show()

"""**Interpret Logistic Regression coefficients**"""

coefficient_df=pd.DataFrame({"Feature":X.columns,"Coefficient":model.coef_[0]})
coefficient_df["Odds_Ratio"]=np.exp(model.coef_[0])
coefficient_df["Absolute_Coefficient"]=abs(coefficient_df["Coefficient"])
coefficient_df=coefficient_df.sort_values("Absolute_Coefficient",ascending=False)
coefficient_df.drop(columns=["Absolute_Coefficient"])

"""**Save the trained model and scaler for Streamlit**"""

joblib.dump(model,"logistic_model.pkl")
joblib.dump(scaler,"scaler.pkl")
print("Model and scaler saved successfully.")

"""#Create the Streamlit application"""

app_code='''import streamlit as st
import pandas as pd
import joblib
st.title(" 🩺 Diabetes Prediction using Logistic Regression")
model=joblib.load("logistic_model.pkl")
scaler=joblib.load("scaler.pkl")
features=["Pregnancies","Glucose","BloodPressure","SkinThickness","Insulin","BMI","DiabetesPedigreeFunction","Age"]
values=[]
for feature in features:
    value=st.number_input(feature,value=0.0)
    values.append(value)
if st.button("Predict"):
    input_data=pd.DataFrame([values],columns=features)
    input_scaled=scaler.transform(input_data)
    prediction=model.predict(input_scaled)[0]
    probability=model.predict_proba(input_scaled)[0][1]
    if prediction==1:
        st.error(f"Prediction: Diabetes detected. Probability: {probability:.2%}")
    else:
        st.success(f"Prediction: No diabetes detected. Probability: {probability:.2%}")
'''
with open("app.py","w") as f:
    f.write(app_code)
print("app.py created successfully.")

# Verify files required for Streamlit
import os
print("Files:")
print(os.listdir())

# Start the Streamlit application
!streamlit run app.py --server.port 8501 &>/content/streamlit.log &

# Install Cloudflare Tunnel
!wget -q https://github.com/cloudflare/cloudflared/releases/latest/download/cloudflared-linux-amd64 -O /content/cloudflared
!chmod +x /content/cloudflared

# Create a public URL for the Streamlit app using Cloudflare Tunnel
import subprocess
import re
process=subprocess.Popen(["/content/cloudflared","tunnel","--url","http://localhost:8501"],stdout=subprocess.PIPE,stderr=subprocess.STDOUT,text=True)
for line in process.stdout:
    if "trycloudflare.com" in line:
        print(line)