# -*- coding: utf-8 -*-
"""Logistic Regression Assessment.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1LjqfScGZ34UOUdSuP4KIYlTPTQxBI81K
"""

# Install required packages for Streamlit deployment
!pip install -q streamlit pyngrok joblib

# required libraries
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import accuracy_score,precision_score,recall_score,f1_score,roc_auc_score,roc_curve,classification_report,confusion_matrix
import joblib

# Load the diabetes dataset
df=pd.read_csv("diabetes.csv")
df.head()

df.shape

df.size

"""**Perform exploratory data analysis**"""

print("Data Types:")
df.dtypes

print("Summary Statistics:")
df.describe()

print("\nMissing Values:")
df.isnull().sum()

print("Duplicate Rows:")
df.duplicated().sum()

print("Target Distribution:")
df["Outcome"].value_counts()

"""**Visualize feature distributions and correlations**"""

df.hist(figsize=(15,12))
plt.tight_layout()
plt.show()

plt.figure(figsize=(10,6))
sns.boxplot(data=df)
plt.xticks(rotation=45)
plt.title("Box Plot of Features")
plt.show()

plt.figure(figsize=(10,8))
sns.heatmap(df.corr(),annot=True,cmap="coolwarm")
plt.title("Correlation Matrix")
plt.show()

X=df.drop(columns=["Outcome"])
y=df["Outcome"]
missing_values=["Glucose","BloodPressure","SkinThickness","Insulin","BMI"]
for col in missing_values:
    X[col]=X[col].replace(0,np.nan)
    X[col]=X[col].fillna(X[col].median())
print("Missing Values After Imputation:")
print(X.isnull().sum())

X_train,X_test,y_train,y_test=train_test_split(X,y,test_size=0.20,random_state=42,stratify=y)
scaler=StandardScaler()
X_train_scaled=scaler.fit_transform(X_train)
X_test_scaled=scaler.transform(X_test)
print("Training Samples:",len(X_train))
print("Testing Samples:",len(X_test))

"""**Build and train the Logistic Regression model**"""

model=LogisticRegression(max_iter=1000)
model.fit(X_train_scaled,y_train)
y_pred=model.predict(X_test_scaled)
y_prob=model.predict_proba(X_test_scaled)[:,1]
print("Model trained successfully.")
print(classification_report(y_test,y_pred))

"""**Evaluate the Logistic Regression model**"""

accuracy=accuracy_score(y_test,y_pred)
print("Accuracy:",accuracy)

precision=precision_score(y_test,y_pred)
print("Precision:",precision)

recall=recall_score(y_test,y_pred)
print("Recall:",recall)

f1=f1_score(y_test,y_pred)
print("F1-Score:",f1)

roc_auc=roc_auc_score(y_test,y_prob)
print("ROC-AUC:",roc_auc)

print("\nConfusion Matrix:")
print(confusion_matrix(y_test,y_pred))

"""**Plot the ROC curve**"""

fpr,tpr,thresholds=roc_curve(y_test,y_prob)
plt.figure(figsize=(8,6))
plt.plot(fpr,tpr,label=f"ROC-AUC = {roc_auc:.3f}")
plt.plot([0,1],[0,1],linestyle="--")
plt.xlabel("False Positive Rate")
plt.ylabel("True Positive Rate")
plt.title("ROC Curve")
plt.legend()
plt.show()

"""**Interpret Logistic Regression coefficients**"""

coefficient_df=pd.DataFrame({"Feature":X.columns,"Coefficient":model.coef_[0]})
coefficient_df["Odds_Ratio"]=np.exp(model.coef_[0])
coefficient_df["Absolute_Coefficient"]=abs(coefficient_df["Coefficient"])
coefficient_df=coefficient_df.sort_values("Absolute_Coefficient",ascending=False)
coefficient_df.drop(columns=["Absolute_Coefficient"])

"""**Save the trained model and scaler for Streamlit**"""

joblib.dump(model,"logistic_model.pkl")
joblib.dump(scaler,"scaler.pkl")
print("Model and scaler saved successfully.")

"""#Create the Streamlit application"""

app_code='''import streamlit as st
import pandas as pd
import joblib
st.title(" 🩺 Diabetes Prediction using Logistic Regression")
model=joblib.load("logistic_model.pkl")
scaler=joblib.load("scaler.pkl")
features=["Pregnancies","Glucose","BloodPressure","SkinThickness","Insulin","BMI","DiabetesPedigreeFunction","Age"]
values=[]
for feature in features:
    value=st.number_input(feature,value=0.0)
    values.append(value)
if st.button("Predict"):
    input_data=pd.DataFrame([values],columns=features)
    input_scaled=scaler.transform(input_data)
    prediction=model.predict(input_scaled)[0]
    probability=model.predict_proba(input_scaled)[0][1]
    if prediction==1:
        st.error(f"Prediction: Diabetes detected. Probability: {probability:.2%}")
    else:
        st.success(f"Prediction: No diabetes detected. Probability: {probability:.2%}")
'''
with open("app.py","w") as f:
    f.write(app_code)
print("app.py created successfully.")

# Verify files required for Streamlit
import os
print("Files:")
print(os.listdir())

# Start the Streamlit application
!streamlit run app.py --server.port 8501 &>/content/streamlit.log &

# Install Cloudflare Tunnel
!wget -q https://github.com/cloudflare/cloudflared/releases/latest/download/cloudflared-linux-amd64 -O /content/cloudflared
!chmod +x /content/cloudflared

# Create a public URL for the Streamlit app using Cloudflare Tunnel
import subprocess
import re
process=subprocess.Popen(["/content/cloudflared","tunnel","--url","http://localhost:8501"],stdout=subprocess.PIPE,stderr=subprocess.STDOUT,text=True)
for line in process.stdout:
    if "trycloudflare.com" in line:
        print(line)

"""# Logistic Regression – Diabetes Prediction Report

## 1. Objective

The objective of this project is to develop a machine learning classification model to predict whether a person is likely to have diabetes based on medical and demographic features.

Logistic Regression is used because the target variable, `Outcome`, represents a binary classification problem where the outcome indicates the presence or absence of diabetes.

## 2. Dataset and Exploratory Data Analysis

The dataset is loaded from `diabetes.csv`. The analysis examines the dataset structure, data types, descriptive statistics, missing values, duplicate records, and target-class distribution.

Histograms are used to understand feature distributions, box plots are used to identify potential outliers, and a correlation matrix is generated to understand relationships between numerical variables.

The target variable is `Outcome`, while the remaining variables are used as input features.

## 3. Data Preprocessing

The dataset contains certain medical variables where a value of zero is not practically meaningful. These include:

* Glucose
* BloodPressure
* SkinThickness
* Insulin
* BMI

The zero values in these columns are replaced with missing values and then imputed using the respective column median. This helps prevent invalid zero values from negatively affecting the model.

The data is then divided into training and testing sets using an **80:20 split** with stratification to maintain the class distribution. StandardScaler is applied to standardize the features before training the model.

## 4. Model Development

A Logistic Regression model is trained using the standardized training data.

The model generates:

* Class predictions using `predict()`
* Diabetes probabilities using `predict_proba()`

The maximum number of iterations is set to 1000 to allow sufficient iterations for model convergence.

## 5. Model Evaluation

The model is evaluated using multiple classification metrics:

### Accuracy

Measures the overall proportion of correctly classified observations.

### Precision

Measures how many observations predicted as diabetic are actually diabetic.

### Recall

Measures how effectively the model identifies people who actually have diabetes.

### F1-Score

Provides a balance between precision and recall.

### ROC-AUC

Measures the model's ability to distinguish between the two classes across different classification thresholds.

The code also generates a confusion matrix and ROC curve for a more detailed evaluation of model performance.

## 6. Feature and Coefficient Analysis

The Logistic Regression coefficients are analyzed to understand the relationship between each feature and the predicted outcome.

The code calculates both the coefficient and its corresponding **odds ratio** using:

`Odds_Ratio = exp(coefficient)`

Features are then sorted according to the absolute magnitude of their coefficients to identify variables having stronger influence on the model's predictions.

A positive coefficient indicates that an increase in the feature is associated with increased odds of the positive class, while a negative coefficient indicates decreased odds, assuming the other variables remain constant.

## 7. Deployment

The trained Logistic Regression model and StandardScaler are saved using Joblib so they can be reused during deployment.

A Streamlit application is created where users can enter values for the eight input features:

* Pregnancies
* Glucose
* BloodPressure
* SkinThickness
* Insulin
* BMI
* DiabetesPedigreeFunction
* Age

The application scales the user input using the saved scaler and generates both a diabetes prediction and probability using the trained model.


# 8. Conclusion

The Logistic Regression model successfully provides a machine learning approach for predicting diabetes based on multiple medical and demographic features.

The project follows an end-to-end machine learning workflow consisting of **data exploration, data cleaning, missing-value treatment, feature scaling, train-test splitting, model training, evaluation, coefficient interpretation, and deployment**.

The preprocessing stage is particularly important because several variables contain zero values that are not meaningful as actual medical measurements. Replacing these values with missing values and applying median imputation improves the quality of the input data.

Logistic Regression is also suitable for this project because it provides both binary predictions and probability estimates. The use of accuracy, precision, recall, F1-score, ROC-AUC, confusion matrix, and ROC curve allows the model to be evaluated from multiple perspectives.

Finally, deploying the trained model through Streamlit makes the project practically usable by allowing users to enter patient-related information and receive a predicted outcome with an estimated probability.

Overall, this project demonstrates a complete **classification and deployment pipeline using Logistic Regression** and provides an interpretable foundation for diabetes prediction.

**Note:** This model should be considered an educational/predictive machine-learning project and not a substitute for professional medical diagnosis.

"""