# -*- coding: utf-8 -*-
"""Multiplie Linear Regression Assignment.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1S5gyqyTxNjYsWU7SOEsFppOtrJ_Alp5L
"""

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

# Machine Learning
from sklearn.model_selection import train_test_split
from sklearn.compose import ColumnTransformer
from sklearn.pipeline import Pipeline
from sklearn.preprocessing import (
    OneHotEncoder,
    StandardScaler,
    PolynomialFeatures
)

from sklearn.linear_model import LinearRegression, Ridge, Lasso

# Evaluation metrics
from sklearn.metrics import (
    mean_absolute_error,
    mean_squared_error,
    r2_score
)
import statsmodels.api as sm
import warnings
warnings.filterwarnings("ignore")

df=pd.read_csv('ToyotaCorolla - MLR.csv')
df

df.head()

df.shape

df.size

df.info()

df.describe()

df.isnull().sum()

df.duplicated().sum()

df.drop_duplicates()

df["Fuel_Type"].value_counts()

df["Automatic"].value_counts()

plt.figure(figsize=(8, 5))
sns.histplot(df["Price"], kde=True)
plt.title("Distribution of Toyota Corolla Price")
plt.xlabel("Price (€)")
plt.ylabel("Frequency")
plt.show()

for i in df.select_dtypes(include=['int','float']).columns:
  sns.boxplot(df[i])
  plt.show()

for i in df.select_dtypes(include=['int','float']).columns:
    q1=df[i].quantile(0.25)
    q3=df[i].quantile(0.75)
    IQR=q3-q1
    lower_bound=q1-1.5*IQR
    upper_bound=q3+1.5*IQR
    df[i]=df[i].clip(lower_bound,upper_bound)

for i in df.select_dtypes(include=['int','float']).columns:
  sns.boxplot(df[i])
  plt.show()

numeric_columns = [
    "Age_08_04",
    "KM",
    "HP",
    "cc",
    "Doors",
    "Weight",
    # "Quarterly_Tax",
    "Price"
]
df[numeric_columns].hist(
    figsize=(15, 12),
    bins=30
)
plt.suptitle("Distribution of Numerical Variables")
plt.show()

fig,axes=plt.subplots(2,4,figsize=(18,10))
for i, column in enumerate(numeric_columns[:-1]):
    row=i//4
    col=i%4
    sns.scatterplot(
        data=df,
        x=column,
        y="Price",
        ax=axes[row, col]
    )
    axes[row,col].set_title(f"Price vs {column}")
plt.tight_layout()
plt.show()

"""Correlation Matrix"""

plt.figure(figsize=(10, 7))
correlation_matrix = df[numeric_columns].corr()
sns.heatmap(
    correlation_matrix,
    annot=True,
    cmap="coolwarm",
    fmt=".2f"
)
plt.title("Correlation Matrix")
plt.show()

x=df.drop('Price',axis=1)
y=df["Price"]

"""Train-Test Split"""

X_train, X_test, y_train, y_test = train_test_split(x,y,test_size=0.20,random_state=42)
print("Training data:", X_train.shape)
print("Testing data:", X_test.shape)

numeric_features = [
    "Age_08_04",
    "KM",
    "HP",
    "Automatic",
    "cc",
    "Doors",
    "Weight",
]

categorical_features = [
    "Fuel_Type"
]

preprocessor = ColumnTransformer(
    transformers=[
        ("num",StandardScaler(),numeric_features),
        ("cat",OneHotEncoder(drop="first",handle_unknown="ignore"),categorical_features)
    ]
)

"""**model-1**"""

model1 = Pipeline(
    steps=[
        ("preprocessor", preprocessor),
        ("regressor", LinearRegression())
    ]
)
model1.fit(X_train, y_train)
y_pred1 = model1.predict(X_test)

def evaluate_model(model_name, y_actual, y_pred):
    mae = mean_absolute_error(y_actual, y_pred)
    mse = mean_squared_error(y_actual, y_pred)
    rmse = np.sqrt(mse)
    r2 = r2_score(y_actual, y_pred)
    print("=" * 50)
    print(model_name)
    print("=" * 50)
    print("MAE :", round(mae, 2))
    print("MSE :", round(mse, 2))
    print("RMSE:", round(rmse, 2))
    print("R2  :", round(r2, 4))
    return {
        "Model": model_name,
        "MAE": mae,
        "MSE": mse,
        "RMSE": rmse,
        "R2": r2
    }

results = []

results.append(
    evaluate_model(
        "Model 1 - Full MLR",
        y_test,
        y_pred1
    )
)

"""**model-2**"""

selected_features = [
    "Age_08_04",
    "KM",
    "HP",
    "Weight",
    "Fuel_Type"
]
X2 = df[selected_features]
X_train2, X_test2, y_train2, y_test2 = train_test_split(X2,y,test_size=0.20,random_state=42)

numeric_features2 = [
    "Age_08_04",
    "KM",
    "HP",
    "Weight",
]
categorical_features2 = [
    "Fuel_Type"
]
preprocessor2 = ColumnTransformer(
    transformers=[
        ("num",StandardScaler(),numeric_features2),
        ("cat",OneHotEncoder(drop="first",handle_unknown="ignore"),categorical_features2)
    ]
)

model2 = Pipeline(
    steps=[
        ("preprocessor", preprocessor2),
        ("regressor", LinearRegression())
    ]
)
model2.fit(X_train2, y_train2)
y_pred2 = model2.predict(X_test2)



results.append(
    evaluate_model(
        "Model 2 - Reduced MLR",
        y_test2,
        y_pred2
    )
)

"""**model-3**"""

numeric_features3 = [
    "Age_08_04",
    "KM",
    "HP",
    "cc",
    "Weight",
]

categorical_features3 = [
    "Fuel_Type"
]

preprocessor3 = ColumnTransformer(
    transformers=[
        ("num",Pipeline(steps=[("scaler", StandardScaler()),("poly",PolynomialFeatures(degree=2,include_bias=False))]),numeric_features3),
        ("cat",OneHotEncoder(drop="first",handle_unknown="ignore"),categorical_features3)
    ]
)

model3 = Pipeline(
    steps=[
        ("preprocessor", preprocessor3),
        ("regressor", LinearRegression())
    ]
)
model3.fit(X_train, y_train)
y_pred3 = model3.predict(X_test)

results.append(
    evaluate_model(
        "Model 3 - MLR with Interaction/Polynomial Terms",
        y_test,
        y_pred3
    )
)

pd.DataFrame(results)

"""Evaluation metrics

MAE	is Average absolute prediction error

MSE is Average squared prediction error

RMSE is Typical prediction error in Price units

R² is Proportion of variation explained by the model

For RMSE and MAE:Lower is better.

For R²:Higher indicates more variation explained by the model.
"""

plt.figure(figsize=(8, 6))
plt.scatter(
    y_test,
    y_pred1,
    alpha=0.6
)
plt.xlabel("Actual Price ($)")
plt.ylabel("Predicted Price ($)")
plt.title("Actual vs Predicted Toyota Corolla Price")
minimum = min(y_test.min(), y_pred1.min())
maximum = max(y_test.max(), y_pred1.max())
plt.plot(
    [minimum, maximum],
    [minimum, maximum],
    linestyle="--"
)
plt.show()

# Get feature names after preprocessing
feature_names = model1.named_steps[
    "preprocessor"
].get_feature_names_out()

coefficients = model1.named_steps[
    "regressor"
].coef_

coefficient_df = pd.DataFrame({
    "Feature": feature_names,
    "Coefficient": coefficients
})

coefficient_df = coefficient_df.sort_values(
    by="Coefficient",
    ascending=False
)

print(coefficient_df)

"""**ridge model**

Ridge regression adds an L2 penalty to the loss function.

Loss=MSE+α∑β
2
j
"""

ridge_model = Pipeline(
    steps=[
        ("preprocessor", preprocessor),
        (
            "regressor",
            Ridge(alpha=10)
        )
    ]
)

ridge_model.fit(
    X_train,
    y_train
)

ridge_pred = ridge_model.predict(X_test)

ridge_result = evaluate_model(
    "Ridge Regression",
    y_test,
    ridge_pred
)
results.append(ridge_result)

"""**lasso model**

Lasso uses an L1 penalty.

Loss=MSE+α∑∣βj∣
"""

lasso_model = Pipeline(
    steps=[
        ("preprocessor", preprocessor),
        (
            "regressor",
            Lasso(alpha=10)
        )
    ]
)

lasso_model.fit(
    X_train,
    y_train
)

lasso_pred = lasso_model.predict(X_test)

lasso_result = evaluate_model(
    "Lasso Regression",
    y_test,
    lasso_pred
)
results.append(lasso_result)

pd.DataFrame(results)

alphas = [0.01, 0.1, 1, 10, 100, 1000]

ridge_results = []

for alpha in alphas:

    model = Pipeline(
        steps=[
            ("preprocessor", preprocessor),
            ("regressor", Ridge(alpha=alpha))
        ]
    )

    model.fit(X_train, y_train)

    prediction = model.predict(X_test)

    rmse = np.sqrt(
        mean_squared_error(
            y_test,
            prediction
        )
    )

    r2 = r2_score(
        y_test,
        prediction
    )

    ridge_results.append({
        "Alpha": alpha,
        "RMSE": rmse,
        "R2": r2
    })

ridge_results_df = pd.DataFrame(ridge_results)

print(ridge_results_df)

lasso_results = []

for alpha in alphas:

    model = Pipeline(
        steps=[
            ("preprocessor", preprocessor),
            ("regressor", Lasso(alpha=alpha))
        ]
    )

    model.fit(X_train, y_train)

    prediction = model.predict(X_test)

    rmse = np.sqrt(
        mean_squared_error(
            y_test,
            prediction
        )
    )

    r2 = r2_score(
        y_test,
        prediction
    )

    lasso_results.append({
        "Alpha": alpha,
        "RMSE": rmse,
        "R2": r2
    })

lasso_results_df = pd.DataFrame(lasso_results)

print(lasso_results_df)

"""conclusion:

You can use this conclusion after you run the actual model and insert your numerical results:

Exploratory Data Analysis was performed to understand the distribution, relationships, and potential outliers in the Toyota Corolla dataset. Numerical and categorical variables were appropriately pre-processed, with categorical variables encoded using one-hot encoding and numerical variables standardized where appropriate.

The dataset was divided into 80% training data and 20% testing data. Three multiple linear regression models were developed using different feature specifications. The models were evaluated using MAE, MSE, RMSE, and R².

Ridge and Lasso regression were subsequently applied to address potential multicollinearity and reduce the risk of overfitting. The final models were compared based on their test-set performance. The model with the most appropriate combination of low prediction error and strong explanatory performance can be selected based on the actual evaluation results.

Residual analysis, correlation analysis, and VIF were used to examine the major assumptions of linear regression. Any violations of linearity, homoscedasticity, normality, or multicollinearity assumptions should be considered when interpreting the final results.
"""