# -*- coding: utf-8 -*-
"""Neural Networks Assessment.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1l-3bKFEyroogIyW0WxxaWgONLtsX6hYD
"""

# import libraries
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

from sklearn.model_selection import train_test_split, GridSearchCV
from sklearn.preprocessing import StandardScaler, LabelEncoder
from sklearn.neural_network import MLPClassifier
from sklearn.pipeline import Pipeline
from sklearn.metrics import (accuracy_score,precision_score,recall_score,f1_score,classification_report,confusion_matrix,ConfusionMatrixDisplay)

df=pd.read_csv('sonardataset.csv')
df

df.head()

df.size

df.shape

df.info()

df.describe()

df.isnull().sum()

df.duplicated().sum()

df['Y'].value_counts()

# Visualize target distrubution
plt.figure(figsize=(6, 4))
sns.countplot(x="Y", data=df)
plt.title("Distribution of Mine and Rock Classes")
plt.xlabel("Class")
plt.ylabel("Number of Samples")
plt.show()

# Now Exploratary Data Analysis
df.iloc[:, :10].hist(figsize=(15, 10), bins=20)
plt.suptitle("Distribution of First 10 Sonar Features")
plt.show()

# Box plots
plt.figure(figsize=(15, 6))
sns.boxplot(data=df.iloc[:, :10])
plt.title("Box Plot of First 10 Sonar Features")
plt.xticks(rotation=45)
plt.show()

# Correlation matrices
plt.figure(figsize=(15, 12))
correlation = df.iloc[:, :-1].corr()
sns.heatmap(correlation,cmap="coolwarm",center=0)
plt.title("Correlation Matrix of Sonar Features")
plt.show()

X = df.drop("Y", axis=1)
y = df["Y"]
print("X shape:", X.shape)
print("y shape:", y.shape)

label_encoder = LabelEncoder()
y = label_encoder.fit_transform(y)
print("Encoded classes:", label_encoder.classes_)

## Train-Test-Split
X_train, X_test, y_train, y_test = train_test_split(X,y,test_size=0.20,random_state=42,stratify=y)
print("Training data:", X_train.shape)
print("Testing data:", X_test.shape)

# creat ANN model
ann_model = Pipeline([
    ("scaler", StandardScaler()),
    ("ann", MLPClassifier(hidden_layer_sizes=(20,),activation="relu",learning_rate_init=0.001,max_iter=1000,random_state=42))
])

ann_model.fit(X_train, y_train)

# Make predictions
y_pred = ann_model.predict(X_test)
print("Predictions:")
print(y_pred)

# Accuracy
accuracy = accuracy_score(y_test, y_pred)
print("Accuracy:", accuracy)

# precision
precision = precision_score(y_test, y_pred)
print("Precision:", precision)

# Recall
recall = recall_score(y_test, y_pred)
print("Recall:", recall)

# F1-score
f1 = f1_score(y_test, y_pred)
print("F1 Score:", f1)

## All matrices together
basic_results = pd.DataFrame({
    "Metric": ["Accuracy","Precision","Recall","F1 Score"],
    "Basic ANN": [accuracy,precision,recall,f1]
})

basic_results

# Classification report
print(classification_report(
    y_test,
    y_pred,
    target_names=label_encoder.classes_
))

# Confusion matrix
cm = confusion_matrix(y_test, y_pred)
disp = ConfusionMatrixDisplay(
    confusion_matrix=cm,
    display_labels=label_encoder.classes_
)
disp.plot()
plt.title("Confusion Matrix - Basic ANN")
plt.show()

# Grid search creat pipeline
ann_pipeline = Pipeline([
    ("scaler", StandardScaler()),
    ("ann", MLPClassifier(max_iter=1000,random_state=42))
])

# Define hyperparameters
param_grid = {
    "ann__hidden_layer_sizes": [(10,),(20,),(20, 10)],
    "ann__activation": ["relu","tanh"],
    "ann__learning_rate_init": [0.001,0.01]
}

# Grid search
grid_search = GridSearchCV(
    estimator=ann_pipeline,
    param_grid=param_grid,
    cv=5,
    scoring="f1",
    n_jobs=-1
)
grid_search.fit(X_train, y_train)

# Best parameter
print("Best Parameters:")
print(grid_search.best_params_)

# Best cross-validation score
print("Best Cross-Validation F1 Score:")
print(grid_search.best_score_)

# View all hyperparamter tunes
tuning_results = pd.DataFrame(grid_search.cv_results_)
tuning_results[
    [
        "param_ann__hidden_layer_sizes",
        "param_ann__activation",
        "param_ann__learning_rate_init",
        "mean_test_score",
        "std_test_score"
    ]
].sort_values(
    by="mean_test_score",
    ascending=False
)

# predicted tuned
best_ann = grid_search.best_estimator_
y_pred_tuned = best_ann.predict(X_test)

# tuned accuarcy
tuned_accuracy = accuracy_score(
    y_test,
    y_pred_tuned
)
print("Tuned ANN Accuracy:", tuned_accuracy)

# Tuned precision
tuned_precision = precision_score(
    y_test,
    y_pred_tuned
)
print("Tuned ANN Precision:", tuned_precision)

# Tuned recall
tuned_recall = recall_score(
    y_test,
    y_pred_tuned
)
print("Tuned ANN Recall:", tuned_recall)

# Tuned f1-score
tuned_f1 = f1_score(
    y_test,
    y_pred_tuned
)
print("Tuned ANN F1 Score:", tuned_f1)

# Tuned classification report
print(
    classification_report(
        y_test,
        y_pred_tuned,
        target_names=label_encoder.classes_
    )
)

# Tuned confusion matrix
cm_tuned = confusion_matrix(
    y_test,
    y_pred_tuned
)
disp = ConfusionMatrixDisplay(
    confusion_matrix=cm_tuned,
    display_labels=label_encoder.classes_
)
disp.plot()
plt.title("Confusion Matrix - Tuned ANN")
plt.show()

# Compare ANN VS tuned ANN
comparison = pd.DataFrame({
    "Metric": ["Accuracy","Precision","Recall","F1 Score"],
    "Basic ANN": [accuracy,precision,recall,f1],
    "Tuned ANN": [tuned_accuracy,tuned_precision,tuned_recall,tuned_f1]
})
comparison

# Visuals of comparision
comparison_plot = comparison.set_index("Metric")
comparison_plot.plot(
    kind="bar",
    figsize=(10, 6)
)
plt.title("Basic ANN vs Tuned ANN")
plt.ylabel("Score")
plt.ylim(0, 1)
plt.xticks(rotation=0)
plt.show()

# Identify improvement
print("Basic ANN Accuracy:", round(accuracy, 4))
print("Tuned ANN Accuracy:", round(tuned_accuracy, 4))
print()
print("Basic ANN F1 Score:", round(f1, 4))
print("Tuned ANN F1 Score:", round(tuned_f1, 4))
print()
if tuned_f1 > f1:
    print("The tuned ANN improved the F1 Score.")
elif tuned_f1 < f1:
    print("The tuned ANN produced a lower F1 Score on the test set.")
else:
    print("Both models produced the same F1 Score.")

# Best ANN configuration
print("Best ANN Configuration:")
print(grid_search.best_params_)

# Comapre results table
final_results = pd.DataFrame({
    "Model": ["Basic ANN","Tuned ANN"],
    "Accuracy": [accuracy,tuned_accuracy],
    "Precision": [precision,tuned_precision],
    "Recall": [recall,tuned_recall],
    "F1 Score": [f1,tuned_f1]
})
final_results

"""## Conclusion

* The Artificial Neural Network (ANN) model was successfully developed to classify sonar signals into **Mine (M) and Rock (R)** categories.
* The dataset contained **208 observations and 60 numerical sonar features**, with no missing values.
* The data was divided into **80% training data (166 samples)** and **20% testing data (42 samples)**.
* A basic ANN achieved **85.71% accuracy** and an **F1-score of 84.21%**.
* Hyperparameter tuning was performed using **GridSearchCV with 5-fold cross-validation**.
* The best ANN configuration used **ReLU activation, one hidden layer with 20 neurons, and a learning rate of 0.01**.
* The tuned ANN achieved **88.10% accuracy, 94.12% precision, 80.00% recall, and 86.49% F1-score**.
* The tuned ANN performed better than the basic ANN, particularly in terms of **accuracy and F1-score**.
* Overall, the results demonstrate that **hyperparameter tuning improved the ANN's classification performance** for distinguishing mines from rocks.
* For a real-world mine-detection system, **recall is particularly important**, as missing an actual mine could have serious safety consequences.
"""