# -*- coding: utf-8 -*-
"""NLP Assessment.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/138emJ-hqHy5jRVl8WdnN3eTi-iDF2nKo
"""

# Import Required Libraries
import pandas as pd
import numpy as np
import re
import matplotlib.pyplot as plt
import seaborn as sns

from sklearn.feature_extraction.text import TfidfVectorizer, ENGLISH_STOP_WORDS
from sklearn.model_selection import train_test_split, cross_val_score
from sklearn.linear_model import LogisticRegression
from sklearn.svm import LinearSVC
from sklearn.pipeline import Pipeline
from sklearn.metrics import (accuracy_score,precision_score,recall_score,f1_score,classification_report,confusion_matrix)

from wordcloud import WordCloud

pip install WordCloud

df = pd.read_csv("amazonreviews.tsv", sep="\t")
df

df.head()

df.shape

df.size

df.info()

df.describe()

df.isnull().sum()

df.duplicated().sum()

print(df["label"].value_counts())

plt.figure(figsize=(6,4))
sns.countplot(data=df, x="label")
plt.title("Sentiment Distribution")
plt.xlabel("Sentiment")
plt.ylabel("Number of Reviews")
plt.show()

# Text cleaning
def clean_text(text):
    text = text.lower()
    text = re.sub(r"<.*?>", " ", text)
    text = re.sub(r"[^a-z\s]", " ", text)
    words = text.split()
    words = [
        word for word in words
        if word not in ENGLISH_STOP_WORDS and len(word) > 2
    ]
    text = " ".join(words)
    return text

# Apply text cleaning
df["clean_review"] = df["review"].apply(clean_text)

# Display original and cleaned reviews
df[["review", "clean_review"]].head(10)

# Word count analysis
df["word_count"] = df["clean_review"].apply(lambda x: len(x.split()))
df[["review", "word_count"]].head()

plt.figure(figsize=(8,5))
plt.hist(df["word_count"], bins=30)
plt.title("Distribution of Review Word Counts")
plt.xlabel("Number of Words")
plt.ylabel("Number of Reviews")
plt.show()

# Most common words
from collections import Counter
# Combine all cleaned reviews
all_words = " ".join(df["clean_review"])
# Split into individual words
words = all_words.split()
# Count word frequency
word_counts = Counter(words)
# Display 20 most common words
word_counts.most_common(20)

# Select positive reviews
positive_reviews = df[df["label"] == "pos"]["clean_review"]
# Combine positive reviews
positive_text = " ".join(positive_reviews)
# Split into words
positive_words = positive_text.split()
# Count positive words
positive_counts = Counter(positive_words)
# Display most common positive words
positive_counts.most_common(20)

# Select negative reviews
negative_reviews = df[df["label"] == "neg"]["clean_review"]
# Combine negative reviews
negative_text = " ".join(negative_reviews)
# Split into words
negative_words = negative_text.split()
# Count negative words
negative_counts = Counter(negative_words)
# Display most common negative words
negative_counts.most_common(20)

# Postive word cloud
positive_wordcloud = WordCloud(
    width=1000,
    height=500,
    background_color="white"
).generate(positive_text)
plt.figure(figsize=(12,6))
plt.imshow(positive_wordcloud, interpolation="bilinear")
plt.axis("off")
plt.title("Positive Reviews Word Cloud")
plt.show()

# Create negative word cloud
negative_wordcloud = WordCloud(
    width=1000,
    height=500,
    background_color="white"
).generate(negative_text)
plt.figure(figsize=(12,6))
plt.imshow(negative_wordcloud, interpolation="bilinear")
plt.axis("off")
plt.title("Negative Reviews Word Cloud")
plt.show()

X = df["clean_review"]
y = df["label"]
print("X shape:", X.shape)
print("y shape:", y.shape)

y = y.map({
    "neg": 0,
    "pos": 1
})
y.head()

# Train test slpit
X_train, X_test, y_train, y_test = train_test_split(X,y,test_size=0.20,random_state=42,stratify=y)
print("Training data:", X_train.shape)
print("Testing data:", X_test.shape)

# Feature extraction
tfidf = TfidfVectorizer(max_features=20000,ngram_range=(1,2),min_df=2,sublinear_tf=True)
# Fit and transform training data
X_train_tfidf = tfidf.fit_transform(X_train)
# Transform test data
X_test_tfidf = tfidf.transform(X_test)
print("Training TF-IDF shape:", X_train_tfidf.shape)
print("Testing TF-IDF shape:", X_test_tfidf.shape)

# Logistic regression model
lr_model = LogisticRegression(max_iter=1000)
# Train the model
lr_model.fit(X_train_tfidf, y_train)
# Predict test data
y_pred_lr = lr_model.predict(X_test_tfidf)

"""# Logistic Regression Results"""

accuracy_lr = accuracy_score(y_test, y_pred_lr)
print("Accuracy :", accuracy_lr)

precision_lr = precision_score(y_test, y_pred_lr)
print("Precision:", precision_lr)

recall_lr = recall_score(y_test, y_pred_lr)
print("Recall   :", recall_lr)

f1_lr = f1_score(y_test, y_pred_lr)
print("F1 Score :", f1_lr)

# Classification report
print(classification_report(y_test,y_pred_lr,target_names=["Negative", "Positive"]))

# Confusion matrix
cm = confusion_matrix(y_test, y_pred_lr)
plt.figure(figsize=(6,5))
sns.heatmap(cm,annot=True,fmt="d",cmap="Blues",xticklabels=["Negative", "Positive"],yticklabels=["Negative", "Positive"])
plt.title("Logistic Regression Confusion Matrix")
plt.xlabel("Predicted")
plt.ylabel("Actual")
plt.show()

# Linear SVM model
svm_model = LinearSVC()
# Train model
svm_model.fit(X_train_tfidf, y_train)
# Predict
y_pred_svm = svm_model.predict(X_test_tfidf)

"""# Linear SVM Results"""

accuracy_svm = accuracy_score(y_test, y_pred_svm)
print("Accuracy :", accuracy_svm)

precision_svm = precision_score(y_test, y_pred_svm)
print("Precision:", precision_svm)

recall_svm = recall_score(y_test, y_pred_svm)
print("Recall   :", recall_svm)

f1_svm = f1_score(y_test, y_pred_svm)
print("F1 Score :", f1_svm)

print(classification_report(y_test,y_pred_svm,target_names=["Negative", "Positive"]))

# visuals
cm_svm = confusion_matrix(y_test, y_pred_svm)
plt.figure(figsize=(6,5))
sns.heatmap(
    cm_svm,annot=True,fmt="d",cmap="Greens",
    xticklabels=["Negative", "Positive"],
    yticklabels=["Negative", "Positive"]
)
plt.title("SVM Confusion Matrix")
plt.xlabel("Predicted")
plt.ylabel("Actual")
plt.show()

# Compare both models
results = pd.DataFrame({
    "Model": ["Logistic Regression","Linear SVM"],
    "Accuracy": [accuracy_lr,accuracy_svm],
    "Precision": [precision_lr,precision_svm],
    "Recall": [recall_lr,recall_svm],
    "F1 Score": [f1_lr,f1_svm]
})
results

results.set_index("Model").plot(
    kind="bar",
    figsize=(10,6)
)
plt.title("Model Performance Comparison")
plt.ylabel("Score")
plt.ylim(0,1)
plt.xticks(rotation=0)
plt.show()

# Cross validation
lr_pipeline = Pipeline([
    ("tfidf",TfidfVectorizer(max_features=20000,ngram_range=(1,2),min_df=2,sublinear_tf=True)),
    ("model",LogisticRegression(max_iter=1000))
])

# Perform 5-fold cross-validation
cv_scores = cross_val_score(lr_pipeline,X,y,cv=5,scoring="f1")
print("Cross-validation F1 scores:")
for i, score in enumerate(cv_scores, 1):
    print("Fold", i, ":", score)
print("Average F1 Score:", cv_scores.mean())

lr_pipeline.fit(X_train, y_train)

new_reviews = [
    "This product is excellent and I really love it",
    "Very bad product. I am completely disappointed",
    "Amazing quality and great performance",
    "Terrible product and waste of money"
]

clean_new_reviews = [clean_text(review) for review in new_reviews]
predictions = lr_pipeline.predict(clean_new_reviews)

for review, prediction in zip(new_reviews, predictions):
    if prediction == 1:
        sentiment = "Positive"
    else:
        sentiment = "Negative"
    print("Review:", review)
    print("Sentiment:", sentiment)

# Get TF-IDF feature names
feature_names = lr_pipeline.named_steps["tfidf"].get_feature_names_out()
# Get model coefficients
coefficients = lr_pipeline.named_steps["model"].coef_[0]

# postive words
positive_indexes = np.argsort(coefficients)[-20:]
positive_features = feature_names[positive_indexes]
print("Important Positive Words:")
for word in reversed(positive_features):
    print(word)

# negative words
negative_indexes = np.argsort(coefficients)[:20]
negative_features = feature_names[negative_indexes]
print("Important Negative Words:")
for word in negative_features:
    print(word)

"""### Conclusion

* The NLP project successfully performed **Amazon Customer Review Sentiment Analysis** to classify reviews as **Positive or Negative**.
* Text preprocessing and **TF-IDF vectorization** were used to convert review text into numerical features.
* Two machine learning models, **Logistic Regression** and **Linear SVM**, were developed and evaluated.
* Logistic Regression achieved **85.30% accuracy** and an **F1-score of 84.85%**.
* Linear SVM achieved **84.95% accuracy** and an **F1-score of 84.64%**.
* Both models provided approximately **85% accuracy**, showing that TF-IDF features were effective for sentiment classification.
* Five-fold cross-validation of the Logistic Regression pipeline produced an average **F1-score of 84.25%**, indicating consistent model performance.
* Overall, the models were able to effectively distinguish between positive and negative customer reviews.

### Final Model Selection

* **Final Model: Logistic Regression**
* Logistic Regression was selected because it achieved the **highest test accuracy (85.30%)** and **F1-score (84.85%)** compared with Linear SVM.
* It also provides **interpretable feature coefficients**, making it easier to understand which words contribute to positive or negative sentiment.
* The model is computationally simple, efficient, and suitable as a **baseline sentiment classification model**.
* Therefore, **Logistic Regression with TF-IDF features** was selected as the final model for the Amazon customer review sentiment analysis.

"""