# -*- coding: utf-8 -*-
"""PCA assessments.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1t_T6ZMP63QcAEwpjR6WZVNtD_cw48TRI
"""

## Import Libraries
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

from sklearn.preprocessing import StandardScaler
from sklearn.decomposition import PCA
from sklearn.cluster import KMeans
from sklearn.metrics import silhouette_score, davies_bouldin_score

import warnings
warnings.filterwarnings('ignore')

df=pd.read_csv('wine.csv')
df

df.head()

df.info()

df.shape

df.size

df.describe()

df.isnull().sum()

df.duplicated().sum()

# separate feature and target
X = df.drop('Type', axis=1)
y = df['Type']
print("Features shape:", X.shape)
print("Target shape:", y.shape)

# Distrubution of features Histrogram
X.hist(figsize=(15, 12), bins=20)
plt.suptitle("Distribution of Wine Features", fontsize=16)
plt.tight_layout()
plt.show()

# Box plot
for i in df.select_dtypes(include=['int','float']).columns:
  sns.boxplot(df[i])
  plt.show()

# correlation matrices
plt.figure(figsize=(14, 10))
correlation = X.corr()
sns.heatmap(
    correlation,
    annot=True,
    cmap='coolwarm',
    fmt='.2f'
)
plt.title("Correlation Matrix of Wine Features")
plt.show()

# Dimensionality Reduction with PCA
scaler = StandardScaler()
X_scaled = scaler.fit_transform(X)
print("Standardized data shape:", X_scaled.shape)

# verify standard
print("Mean of standardized features:")
print(X_scaled.mean(axis=0))

print("Standard deviation:")
print(X_scaled.std(axis=0))

## Apply PCA
pca = PCA()
X_pca = pca.fit_transform(X_scaled)
print("Original shape:", X_scaled.shape)
print("PCA shape:", X_pca.shape)

# Explained variance ratio
explained_variance = pca.explained_variance_ratio_
for i, variance in enumerate(explained_variance):
    print(f"PC{i+1}: {variance:.4f}")

# Scatter plot
plt.figure(figsize=(10, 6))
plt.plot(
    range(1, len(explained_variance) + 1),
    explained_variance,
    marker='o'
)
plt.xlabel("Principal Component")
plt.ylabel("Explained Variance Ratio")
plt.title("Scatter Plot")
plt.xticks(range(1, 14))
plt.grid()
plt.show()

# Cummalative explained varianace
cumulative_variance = np.cumsum(explained_variance)
plt.figure(figsize=(10, 6))
plt.plot(
    range(1, len(cumulative_variance) + 1),
    cumulative_variance,
    marker='o'
)
plt.axhline(y=0.90, linestyle='--', label='90% Variance')
plt.xlabel("Number of Principal Components")
plt.ylabel("Cumulative Explained Variance")
plt.title("Cumulative Explained Variance")
plt.xticks(range(1, 14))
plt.legend()
plt.grid()
plt.show()

# Find number of components for variance
n_components = np.argmax(cumulative_variance >= 0.90) + 1
print("Number of components required for 90% variance:", n_components)

# create final PCA dataset
pca_final = PCA(n_components=8)
X_pca_final = pca_final.fit_transform(X_scaled)
print("Original data shape:", X_scaled.shape)
print("PCA data shape:", X_pca_final.shape)

# create PCA dataset
pca_columns = [f'PC{i}' for i in range(1, 9)]
pca_df = pd.DataFrame(
    X_pca_final,
    columns=pca_columns
)
pca_df.head()

# Clustering with Original Data
# We will use K-Means clustering.
# Before deciding the number of clusters, let's examine several K values.
# Elbow method
inertia = []
K = range(2, 11)
for k in K:
    kmeans = KMeans(
        n_clusters=k,
        random_state=42,
        n_init=10
    )
    kmeans.fit(X_scaled)
    inertia.append(kmeans.inertia_)

plt.figure(figsize=(10, 6))
plt.plot(K, inertia, marker='o')
plt.xlabel("Number of Clusters (K)")
plt.ylabel("Inertia")
plt.title("Elbow Method - Original Data")
plt.grid()
plt.show()

# Apply K-Means to original dataset
kmeans_original = KMeans(
    n_clusters=3,
    random_state=42,
    n_init=10
)
original_clusters = kmeans_original.fit_predict(X_scaled)
print(original_clusters)

# Add cluster labels
df_original = X.copy()
df_original['Cluster'] = original_clusters
df_original.head()

print(df_original['Cluster'].value_counts().sort_index())

# visual original cluster
plt.figure(figsize=(10, 7))
plt.scatter(
    X['Alcohol'],
    X['Proline'],
    c=original_clusters,
    cmap='viridis',
    s=60
)
plt.xlabel("Alcohol")
plt.ylabel("Proline")
plt.title("K-Means Clustering - Original Data")
plt.colorbar(label="Cluster")
plt.show()

# silhouette
silhouette_original = silhouette_score(
    X_scaled,
    original_clusters
)
print("Silhouette Score:", silhouette_original)

db_original = davies_bouldin_score(
    X_scaled,
    original_clusters
)
print("Davies-Bouldin Index:", db_original)

# clustering with PCA data
pca_inertia = []
K = range(2, 11)
for k in K:
    kmeans = KMeans(
        n_clusters=k,
        random_state=42,
        n_init=10
    )
    kmeans.fit(X_pca_final)
    pca_inertia.append(kmeans.inertia_)

plt.figure(figsize=(10, 6))
plt.plot(K, pca_inertia, marker='o')
plt.xlabel("Number of Clusters (K)")
plt.ylabel("Inertia")
plt.title("Elbow Method - PCA Data")
plt.grid()
plt.show()

# Apply K-means to PCA data
kmeans_pca = KMeans(
    n_clusters=3,
    random_state=42,
    n_init=10
)
pca_clusters = kmeans_pca.fit_predict(X_pca_final)
print(pca_clusters)

# ADD PCA data
pca_cluster_df = pca_df.copy()
pca_cluster_df['Cluster'] = pca_clusters
pca_cluster_df.head()

# Visual PCA cluster
plt.figure(figsize=(10, 7))
plt.scatter(
    X_pca_final[:, 0],
    X_pca_final[:, 1],
    c=pca_clusters,
    cmap='viridis',
    s=60
)
plt.xlabel("Principal Component 1")
plt.ylabel("Principal Component 2")
plt.title("K-Means Clustering using PCA Data")
plt.colorbar(label="Cluster")
plt.show()

# Evalute PCA
silhouette_pca = silhouette_score(
    X_pca_final,
    pca_clusters
)
print("PCA Silhouette Score:", silhouette_pca)

db_pca = davies_bouldin_score(
    X_pca_final,
    pca_clusters
)
print("PCA Davies-Bouldin Index:", db_pca)

# Comparision and analysis
comparison = pd.DataFrame({
    'Dataset': [
        'Original Data',
        'PCA Data'
    ],
    'Number of Features': [
        X_scaled.shape[1],
        X_pca_final.shape[1]
    ],
    'Number of Clusters': [
        3,
        3
    ],
    'Silhouette Score': [
        silhouette_original,
        silhouette_pca
    ],
    'Davies-Bouldin Index': [
        db_original,
        db_pca
    ]
})
comparison

comparison.set_index('Dataset')[[
    'Silhouette Score',
    'Davies-Bouldin Index'
]].plot(
    kind='bar',
    figsize=(10, 6)
)
plt.title("Clustering Performance Comparison")
plt.ylabel("Score")
plt.xticks(rotation=0)
plt.grid(axis='y')
plt.show()

# Compare cluster analysis
comparison_clusters = pd.DataFrame({
    'Original_Cluster': original_clusters,
    'PCA_Cluster': pca_clusters
})
comparison_clusters.head(20)

pd.crosstab(
    comparison_clusters['Original_Cluster'],
    comparison_clusters['PCA_Cluster']
)

# Original vs PCA visuals
plt.figure(figsize=(10, 7))
plt.scatter(
    X['Alcohol'],
    X['Proline'],
    c=original_clusters,
    cmap='viridis',
    s=60
)
plt.xlabel("Alcohol")
plt.ylabel("Proline")
plt.title("Clusters - Original Data")
plt.show()

plt.figure(figsize=(10, 7))
plt.scatter(
    X_pca_final[:, 0],
    X_pca_final[:, 1],
    c=pca_clusters,
    cmap='viridis',
    s=60
)
plt.xlabel("PC1")
plt.ylabel("PC2")
plt.title("Clusters - PCA Data")
plt.show()

plt.figure(figsize=(10, 7))
plt.scatter(
    X_pca_final[:, 0],
    X_pca_final[:, 1],
    c=pca_clusters,
    cmap='viridis',
    s=60
)
plt.xlabel("PC1")
plt.ylabel("PC2")
plt.title("Clusters - PCA Data")
plt.show()

"""## Conclusion

The Wine dataset consists of **178 observations and 14 variables**, including 1 target variable (`Type`) and 13 numerical chemical features. Exploratory Data Analysis showed that the features have different distributions and scales, with several features exhibiting strong correlations. The dataset contains **no missing values and no duplicate records**.

Before applying PCA, all 13 numerical features were standardized using `StandardScaler` so that features with larger numerical values would not dominate the analysis. PCA was then applied to reduce the dimensionality of the dataset. The analysis showed that the first **8 principal components retain approximately 92% of the total variance**, reducing the feature space from 13 dimensions to 8 while preserving most of the information.

K-Means clustering with 3 clusters was performed on both the standardized original data and the PCA-transformed data. The original data achieved a **Silhouette Score of 0.285** and a **Davies-Bouldin Index of 1.389**. After PCA, the Silhouette Score improved to **0.315**, while the Davies-Bouldin Index decreased to **1.267**. Since a higher Silhouette Score and a lower Davies-Bouldin Index indicate better clustering quality, the PCA-based clustering provided better-defined clusters.

Furthermore, the cluster assignments from the original and PCA datasets were identical, indicating that dimensionality reduction preserved the important structure of the data.

Overall, PCA successfully reduced dimensionality while retaining most of the dataset's information and slightly improving clustering performance. Therefore, the PCA-transformed dataset with **8 principal components** is a more efficient representation for further clustering analysis.

## Key Insights

1. **No data-quality issues:** The dataset contains no missing values or duplicate records.

2. **Different feature scales:** The features have significantly different numerical ranges, making standardization necessary before PCA and K-Means.

3. **Feature correlation:** Several chemical features are correlated, indicating the presence of redundant information.

4. **Effective dimensionality reduction:** PCA reduced the number of features from **13 to 8** while retaining approximately **92% of the variance**.

5. **Better clustering after PCA:** The Silhouette Score improved from **0.285 to 0.315**.

6. **Improved cluster compactness:** The Davies-Bouldin Index decreased from **1.389 to 1.267**, indicating better-separated and more compact clusters.

7. **Stable cluster assignments:** The crosstab shows that all **65, 51, and 62 observations** in the original clusters correspond exactly to the same PCA clusters.

8. **PCA improves efficiency:** Reducing 13 dimensions to 8 can simplify visualization, reduce computational complexity, and remove some redundant information while preserving the main structure of the dataset.

### Overall Finding

**PCA was effective for this dataset because it reduced dimensionality by approximately 38.5% (13 → 8 features), retained approximately 92% of the information, and improved the quality of K-Means clustering.**

"""