# -*- coding: utf-8 -*-
"""Random forest assessment.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1i59trmFs4qsEjO4GrIU41XMY_qsx5fVQ
"""

## Import libraries
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
from sklearn.ensemble import(RandomForestClassifier,BaggingClassifier,AdaBoostClassifier,GradientBoostingClassifier)
from sklearn.metrics import(accuracy_score,precision_score,recall_score,f1_score,classification_report,confusion_matrix)

import warnings
warnings.filterwarnings('ignore')

df = pd.read_excel("glass.xlsx", sheet_name="glass")
df

df.head()

df.shape

df.size

df.info()

df.isnull().sum()

df.duplicated().sum()

df = df.drop_duplicates()
print("Shape after removing duplicates:", df.shape)

df.dtypes

# check target class distrubution
print(df['Type'].value_counts())

plt.figure(figsize=(8,5))
sns.countplot(data=df, x='Type')
plt.title("Glass Type Distribution")
plt.xlabel("Glass Type")
plt.ylabel("Count")
plt.show()

# Healing imbalanced data
class_weight='balanced'

## check outliers boxplot
plt.figure(figsize=(15,8))
df.drop(columns=['Type']).boxplot()
plt.title("Box Plot of Glass Features")
plt.xticks(rotation=45)
plt.show()

# Histrogram of features
df.drop(columns=['Type']).hist(
    figsize=(15,12),
    bins=20
)
plt.suptitle("Distribution of Glass Features")
plt.show()

# Correlation Heatmap
plt.figure(figsize=(10,8))
sns.heatmap(
    df.corr(),
    annot=True,
    cmap='coolwarm',
    fmt='.2f'
)
plt.title("Correlation Heatmap")
plt.show()

# Pair plot
sns.pairplot(
    df,
    vars=['RI', 'Na', 'Mg', 'Al', 'Ca'],
    hue='Type'
)
plt.show()

## separate features and target
X = df.drop('Type', axis=1)
y = df['Type']
print("Features shape:", X.shape)
print("Target shape:", y.shape)

# train test split
X_train, X_test, y_train, y_test = train_test_split(X,y,test_size=0.20,random_state=42,stratify=y)
print("Training data:", X_train.shape)
print("Testing data:", X_test.shape)

# Feature Scaling
scaler = StandardScaler()
X_train_scaled = scaler.fit_transform(X_train)
X_test_scaled = scaler.transform(X_test)

# Random forest model
rf_model = RandomForestClassifier(
    n_estimators=200,
    random_state=42,
    class_weight='balanced'
)
rf_model.fit(X_train_scaled, y_train)

# make predictions
y_pred_rf = rf_model.predict(X_test_scaled)
print(y_pred_rf)

# Accuracy , precision, recall, f1-score
rf_accuracy = accuracy_score(y_test, y_pred_rf)
print("Random Forest Accuracy:", rf_accuracy)
rf_precision = precision_score(
    y_test,
    y_pred_rf,
    average='weighted',
    zero_division=0
)
rf_recall = recall_score(
    y_test,
    y_pred_rf,
    average='weighted',
    zero_division=0
)
rf_f1 = f1_score(
    y_test,
    y_pred_rf,
    average='weighted',
    zero_division=0
)
print("Accuracy : ", rf_accuracy)
print("Precision: ", rf_precision)
print("Recall   : ", rf_recall)
print("F1 Score : ", rf_f1)

# Classification report
print("Random Forest Classification Report")
print(
    classification_report(
        y_test,
        y_pred_rf,
        zero_division=0
    )
)

# final matrices
cm = confusion_matrix(y_test, y_pred_rf)
plt.figure(figsize=(8,6))
sns.heatmap(
    cm,
    annot=True,
    fmt='d',
    cmap='Blues'
)
plt.title("Random Forest Confusion Matrix")
plt.xlabel("Predicted")
plt.ylabel("Actual")
plt.show()

# feature importance
feature_importance = pd.DataFrame({
    'Feature': X.columns,
    'Importance': rf_model.feature_importances_
})
feature_importance = feature_importance.sort_values(
    by='Importance',
    ascending=False
)
feature_importance

plt.figure(figsize=(10,6))
sns.barplot(
    data=feature_importance,
    x='Importance',
    y='Feature'
)
plt.title("Random Forest Feature Importance")
plt.show()

# Implement bagging
bagging_model = BaggingClassifier(
    n_estimators=200,
    random_state=42
)
bagging_model.fit(X_train_scaled, y_train)

y_pred_bagging = bagging_model.predict(X_test_scaled)

bag_accuracy = accuracy_score(y_test, y_pred_bagging)
bag_precision = precision_score(
    y_test,
    y_pred_bagging,
    average='weighted',
    zero_division=0
)
bag_recall = recall_score(
    y_test,
    y_pred_bagging,
    average='weighted',
    zero_division=0
)
bag_f1 = f1_score(
    y_test,
    y_pred_bagging,
    average='weighted',
    zero_division=0
)
print("Bagging Results")
print("Accuracy :", bag_accuracy)
print("Precision:", bag_precision)
print("Recall   :", bag_recall)
print("F1 Score :", bag_f1)

# AdaBoost
boosting_model = AdaBoostClassifier(
    n_estimators=200,
    random_state=42
)
boosting_model.fit(X_train_scaled, y_train)

y_pred_boosting = boosting_model.predict(X_test_scaled)

boost_accuracy = accuracy_score(
    y_test,
    y_pred_boosting
)
boost_precision = precision_score(
    y_test,
    y_pred_boosting,
    average='weighted',
    zero_division=0
)
boost_recall = recall_score(
    y_test,
    y_pred_boosting,
    average='weighted',
    zero_division=0
)
boost_f1 = f1_score(
    y_test,
    y_pred_boosting,
    average='weighted',
    zero_division=0
)
print("AdaBoost Results")
print("Accuracy :", boost_accuracy)
print("Precision:", boost_precision)
print("Recall   :", boost_recall)
print("F1 Score :", boost_f1)

# Gradiant Boost
gradient_model = GradientBoostingClassifier(
    n_estimators=200,
    random_state=42
)
gradient_model.fit(X_train_scaled, y_train)

y_pred_gradient = gradient_model.predict(X_test_scaled)

gradient_accuracy = accuracy_score(
    y_test,
    y_pred_gradient
)
gradient_precision = precision_score(
    y_test,
    y_pred_gradient,
    average='weighted',
    zero_division=0
)
gradient_recall = recall_score(
    y_test,
    y_pred_gradient,
    average='weighted',
    zero_division=0
)
gradient_f1 = f1_score(
    y_test,
    y_pred_gradient,
    average='weighted',
    zero_division=0
)
print("Gradient Boosting Results")
print("Accuracy :", gradient_accuracy)
print("Precision:", gradient_precision)
print("Recall   :", gradient_recall)
print("F1 Score :", gradient_f1)

results = pd.DataFrame({
    'Model': [
        'Random Forest',
        'Bagging',
        'AdaBoost',
        'Gradient Boosting'
    ],
    'Accuracy': [
        rf_accuracy,
        bag_accuracy,
        boost_accuracy,
        gradient_accuracy
    ],
    'Precision': [
        rf_precision,
        bag_precision,
        boost_precision,
        gradient_precision
    ],
    'Recall': [
        rf_recall,
        bag_recall,
        boost_recall,
        gradient_recall
    ],
    'F1 Score': [
        rf_f1,
        bag_f1,
        boost_f1,
        gradient_f1
    ]
})
results

results.set_index('Model')[
    ['Accuracy', 'Precision', 'Recall', 'F1 Score']
].plot(
    kind='bar',
    figsize=(12,6)
)
plt.title("Model Performance Comparison")
plt.ylabel("Score")
plt.ylim(0, 1)
plt.xticks(rotation=0)
plt.legend(
    bbox_to_anchor=(1.05, 1),
    loc='upper left'
)
plt.show()

# Find best model
best_model = results.loc[
    results['F1 Score'].idxmax()
]
print("Best Model:")
print(best_model)

# Final report
print(" RANDOM FOREST ")
print(
    classification_report(
        y_test,
        y_pred_rf,
        zero_division=0
    )
)
print(" BAGGING ")
print(
    classification_report(
        y_test,
        y_pred_bagging,
        zero_division=0
    )
)
print(" ADABOOST ")
print(
    classification_report(
        y_test,
        y_pred_boosting,
        zero_division=0
    )
)
print(" GRADIENT BOOSTING ")
print(
    classification_report(
        y_test,
        y_pred_gradient,
        zero_division=0
    )
)

"""# Random Forest and Ensemble Learning Report

## 1. Objective

The objective of this project is to classify different types of glass based on their chemical properties using ensemble machine learning techniques.

The analysis focuses primarily on **Random Forest**, while also comparing its performance with other ensemble methods:

* Random Forest
* Bagging
* AdaBoost
* Gradient Boosting

The goal is to determine which ensemble model provides the best classification performance on the Glass dataset.

# 2. Dataset Description

The dataset contains **214 observations and 10 variables**.

There are **9 chemical composition features** and one target variable, `Type`.

### Input Features

* RI – Refractive Index
* Na – Sodium
* Mg – Magnesium
* Al – Aluminum
* Si – Silicon
* K – Potassium
* Ca – Calcium
* Ba – Barium
* Fe – Iron

### Target

`Type` represents the different types of glass.

The dataset contains six classes:

| Glass Type | Number of Records |
| ---------- | ----------------: |
| Type 1     |                69 |
| Type 2     |                76 |
| Type 3     |                17 |
| Type 5     |                13 |
| Type 6     |                 9 |
| Type 7     |                29 |

The dataset is therefore **imbalanced**, with Type 2 and Type 1 having considerably more observations than Type 6 and Type 5.


# 3. Data Quality Analysis

The dataset was checked for missing values and duplicate records.

### Missing Values

There were **no missing values** in the dataset.

### Duplicate Records

The dataset contained **1 duplicate record**.

After removing the duplicate, the final dataset contained:

**213 observations × 10 variables**

This cleaned dataset was used for subsequent modelling.


# 4. Exploratory Data Analysis

Several visualizations were used to understand the dataset:

* Histograms
* Box plots
* Correlation heatmap
* Pair plots
* Target-class distribution

The box plots helped identify potential outliers in the chemical features, while the histograms provided an understanding of feature distributions.

The correlation heatmap was used to examine relationships among the chemical properties.

The pair plot helped visualize relationships between selected features and their distribution across different glass types.


# 5. Data Preparation

The features and target were separated into:

**X:** 9 chemical features
**y:** Glass Type

The dataset was divided into training and testing sets using an **80:20 split** with stratification.

### Training Dataset

**170 observations**

### Testing Dataset

**43 observations**

StandardScaler was applied to standardize the feature values before model training.

Because the target classes are imbalanced, the Random Forest model was configured with:

`class_weight='balanced'`

This gives greater importance to underrepresented classes during model training.


# 6. Random Forest Model

A Random Forest Classifier was trained using:

* **200 decision trees**
* `random_state = 42`
* `class_weight = 'balanced'`

Random Forest combines multiple decision trees and aggregates their predictions to produce the final classification.

The ensemble approach helps reduce the limitations of using a single decision tree and can provide more robust predictions.


# 7. Random Forest Performance

The Random Forest model achieved the following results:

| Metric    |      Score |
| --------- | ---------: |
| Accuracy  | **79.07%** |
| Precision | **81.01%** |
| Recall    | **79.07%** |
| F1 Score  | **79.20%** |

Therefore, the Random Forest model correctly classified approximately **79% of the test observations**.


# 8. Random Forest Classification Performance

The class-wise performance was:

| Class  | Precision | Recall | F1 Score |
| ------ | --------: | -----: | -------: |
| Type 1 |      0.75 |   0.86 |     0.80 |
| Type 2 |      0.73 |   0.73 |     0.73 |
| Type 3 |      1.00 |   0.67 |     0.80 |
| Type 5 |      1.00 |   0.67 |     0.80 |
| Type 6 |      0.67 |   1.00 |     0.80 |
| Type 7 |      1.00 |   0.83 |     0.91 |

The model performed particularly well for **Type 7**, with an F1-score of **0.91**.

Type 1 also achieved a strong recall of **0.86**, indicating that most Type 1 glass samples were correctly identified.


# 9. Feature Importance

Random Forest provides feature importance values that help identify which chemical properties contributed most to the classification.

| Feature | Importance |
| ------- | ---------: |
| Mg      | **17.69%** |
| Na      | **14.22%** |
| Ca      | **13.61%** |
| Al      | **12.37%** |
| K       | **12.06%** |
| RI      | **11.18%** |
| Si      |  **8.44%** |
| Ba      |  **8.06%** |
| Fe      |  **2.36%** |

### Key observation

**Magnesium (Mg)** was the most important feature, contributing approximately **17.69%** of the total feature importance.

It was followed by:

1. Na – 14.22%
2. Ca – 13.61%
3. Al – 12.37%
4. K – 12.06%
5. RI – 11.18%

**Fe** had the lowest feature importance at approximately **2.36%**.

These importance values indicate how useful the features were to the trained Random Forest for making classification decisions. They should not be interpreted as causal relationships.


# 10. Ensemble Model Comparison

The notebook compares four ensemble learning techniques.

| Model                 |   Accuracy |  Precision |     Recall |   F1 Score |
| --------------------- | ---------: | ---------: | ---------: | ---------: |
| **Random Forest**     | **79.07%** | **81.01%** | **79.07%** | **79.20%** |
| **Bagging**           | **79.07%** | **79.40%** | **79.07%** | **78.86%** |
| **AdaBoost**          | **41.86%** | **47.98%** | **41.86%** | **42.01%** |
| **Gradient Boosting** | **83.72%** | **84.92%** | **83.72%** | **83.23%** |


# 11. Model Comparison Insights

### Random Forest

Random Forest achieved **79.07% accuracy** and **79.20% F1-score**, making it a strong ensemble model for this dataset.

### Bagging

Bagging achieved the same accuracy as Random Forest at **79.07%**, but its F1-score was slightly lower at **78.86%**.

Therefore, Random Forest performed marginally better overall.

### AdaBoost

AdaBoost performed considerably worse, achieving only **41.86% accuracy** and **42.01% F1-score**.

This indicates that AdaBoost was not well suited to this particular dataset and configuration.

### Gradient Boosting

Gradient Boosting achieved the highest performance:

* Accuracy: **83.72%**
* Precision: **84.92%**
* Recall: **83.72%**
* F1-score: **83.23%**

Therefore, Gradient Boosting was selected as the **best-performing model** based on F1-score.


# 12. Final Conclusion

The Random Forest model successfully classified different glass types using their chemical properties and achieved an accuracy of **79.07%**, precision of **81.01%**, recall of **79.07%**, and F1-score of **79.20%**.

The feature-importance analysis showed that **Mg, Na, Ca, Al, and K** were among the most influential chemical properties for the Random Forest model, with Mg being the most important feature.

The project also demonstrated the effectiveness of comparing multiple ensemble learning algorithms rather than relying on a single model. Random Forest and Bagging both achieved approximately 79% accuracy, whereas AdaBoost performed substantially worse.

However, **Gradient Boosting was the best-performing model in this experiment**, achieving **83.72% accuracy and an F1-score of 83.23%**. Therefore, based on the evaluated metrics, Gradient Boosting would be the preferred model among the four tested approaches.

Overall, the analysis demonstrates that ensemble learning techniques can effectively classify glass types, and model comparison is essential for selecting the most suitable algorithm for a particular dataset.

"""