# -*- coding: utf-8 -*-
"""Recommendation system Assessment.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1PzdHwHiT1-dSJjTDbOwg9WaDSGDLsDHV
"""

# Import required libraries
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

from sklearn.preprocessing import MultiLabelBinarizer, MinMaxScaler, OneHotEncoder
from sklearn.metrics.pairwise import cosine_similarity

pd.set_option('display.max_columns', None)

df=pd.read_csv('anime.csv')
df

df.head()

df.size

df.shape

df.info()

df.describe()

df.isnull().sum()

df.duplicated().sum()

# Unique values in categorical-ish columns
print("Types:", df['type'].unique())
print("Episodes sample:", df['episodes'].unique()[:15])

# Fill categorical missing values
df['genre'] = df['genre'].fillna('Unknown')
df['type'] = df['type'].fillna('Unknown')

# Convert episodes to numeric ('Unknown' -> NaN), then impute
df['episodes'] = pd.to_numeric(df['episodes'], errors='coerce')
df['episodes'] = df['episodes'].fillna(df['episodes'].median())

# Impute missing ratings with the median rating
df['rating'] = df['rating'].fillna(df['rating'].median())

df.isnull().sum()

fig, axes = plt.subplots(1, 3, figsize=(15, 4))
df['rating'].hist(bins=30, ax=axes[0])
axes[0].set_title('Rating distribution')
df['type'].value_counts().plot(kind='bar', ax=axes[1])
axes[1].set_title('Count by type')
np.log1p(df['members']).hist(bins=30, ax=axes[2])
axes[2].set_title('log(1 + members) distribution')
plt.tight_layout()
plt.show()

# multi-hot encoding
df['genre_list'] = df['genre'].apply(lambda g: [x.strip() for x in g.split(',')])
mlb = MultiLabelBinarizer()
genre_encoded = mlb.fit_transform(df['genre_list'])
genre_df = pd.DataFrame(genre_encoded, columns=mlb.classes_, index=df.index)
print(f"Number of unique genre tags: {len(mlb.classes_)}")
genre_df.head()

# one-hot encoding
type_df = pd.get_dummies(df['type'], prefix='type')
type_df.head()

scaler = MinMaxScaler()
numeric_scaled = scaler.fit_transform(df[['episodes', 'rating']])
numeric_df = pd.DataFrame(numeric_scaled, columns=['episodes_scaled', 'rating_scaled'], index=df.index)
numeric_df.head()

feature_matrix = pd.concat([genre_df, type_df, numeric_df], axis=1)
print("Feature matrix shape:", feature_matrix.shape)
feature_matrix.head()

GENRE_WEIGHT = 2.0
weighted_matrix = feature_matrix.copy()
weighted_matrix[mlb.classes_] = weighted_matrix[mlb.classes_] * GENRE_WEIGHT
X = weighted_matrix.values
X.shape

cosine_sim = cosine_similarity(X)
print(cosine_sim.shape)

# Map anime name -> row index (handles exact-match lookups)
indices = pd.Series(df.index, index=df['name']).drop_duplicates()

def recommend_anime(title, top_n=10, threshold=None):
    if title not in indices:
        # Simple fuzzy fallback: case-insensitive substring match
        matches = df[df['name'].str.contains(title, case=False, na=False, regex=False)]
        if matches.empty:
            raise ValueError(f"'{title}' not found in dataset.")
        idx = matches.index[0]
        print(f"Exact match not found. Using closest match: '{df.loc[idx, 'name']}'")
    else:
        idx = indices[title]
        if isinstance(idx, pd.Series):  # duplicate names
            idx = idx.iloc[0]
    sim_scores = list(enumerate(cosine_sim[idx]))
    sim_scores = [s for s in sim_scores if s[0] != idx]  # exclude itself
    sim_scores.sort(key=lambda x: x[1], reverse=True)
    if threshold is not None:
        sim_scores = [s for s in sim_scores if s[1] >= threshold]
    sim_scores = sim_scores[:top_n]
    result_idx = [i for i, _ in sim_scores]
    scores = [s for _, s in sim_scores]
    result = df.loc[result_idx, ['name', 'genre', 'type', 'rating', 'members']].copy()
    result['similarity'] = scores
    return result.reset_index(drop=True)

recommend_anime('Gintama', top_n=5)

def recommendations_at_thresholds(title, thresholds=(0.9, 0.8, 0.7, 0.6, 0.5)):
   counts = []
   for t in thresholds:
       recs = recommend_anime(title, top_n=len(df), threshold=t)
       counts.append(len(recs))
   return pd.DataFrame({'threshold': thresholds, 'num_recommendations': counts})
recommendations_at_thresholds('Gintama')

# Visualize how list size shrinks as the threshold rises
thresh_df = recommendations_at_thresholds('One Piece', thresholds=np.arange(0.5, 1.0, 0.05))
plt.figure(figsize=(7, 4))
plt.plot(thresh_df['threshold'], thresh_df['num_recommendations'], marker='o')
plt.xlabel('Similarity threshold')
plt.ylabel('# of recommendations')
plt.title("Recommendation list size vs. threshold ('One Piece')")
plt.grid(alpha=0.3)
plt.show()

def recommend_anime_adaptive(title, min_results=5, top_n=10, start_threshold=0.8, step=0.1, min_threshold=0.3):
    threshold = start_threshold
    while threshold >= min_threshold:
        recs = recommend_anime(title, top_n=top_n, threshold=threshold)
        if len(recs) >= min_results:
            print(f"Using threshold={threshold:.2f} -> {len(recs)} results")
            return recs
        threshold -= step
    print("Falling back to top_n with no threshold.")
    return recommend_anime(title, top_n=top_n)
recommend_anime_adaptive('Fullmetal Alchemist: Brotherhood')

def genre_overlap_report(title, top_n=10):
    recs = recommend_anime(title, top_n=top_n)
    target_genres = set(df.loc[indices[title], 'genre_list']) if title in indices else None
    if target_genres is None:
        print("Title not found for overlap report.")
        return recs
    overlaps = []
    for name in recs['name']:
        row = df[df['name'] == name].iloc[0]
        overlap = len(target_genres & set(row['genre_list'])) / max(len(target_genres), 1)
        overlaps.append(round(overlap, 2))
    recs['genre_overlap'] = overlaps
    return recs
genre_overlap_report('Gintama')

"""#Conclusion

The Anime Recommendation System successfully implements a content-based recommendation approach using the anime dataset. The system handles missing values, converts genres into multi-hot encoded features, encodes anime types, and scales numerical features such as episodes and ratings.

A 53-dimensional feature matrix was created using 44 genre features, anime type features, and scaled numerical attributes. Genre features were given higher importance using a weight of 2.0 because genre is considered the strongest signal for content similarity.

Cosine similarity was then used to identify anime titles with similar characteristics. The system successfully generated relevant recommendations for titles such as Naruto, Death Note, and Fullmetal Alchemist: Brotherhood, including sequels, spin-offs, and anime with similar genres.

The threshold analysis also showed that increasing the similarity threshold produces fewer but more closely related recommendations. For example, for Naruto, 884 anime meet a 0.5 similarity threshold, while only 9 meet a 0.9 threshold. An adaptive recommendation mechanism was therefore implemented to maintain a useful number of recommendations while preserving similarity.

Overall, the project demonstrates that content-based filtering with cosine similarity can effectively recommend anime based on genre, type, episodes, and rating characteristics. The system is particularly useful for users who want recommendations similar to a specific anime.

However, the system does not use user ratings or historical user-item interactions, so it cannot learn individual user preferences. Future improvements could include collaborative filtering, user personalization, popularity adjustments, hybrid recommendation methods, and quantitative evaluation using user feedback.

Final Finding: The developed recommendation system provides a practical and interpretable way to discover similar anime while avoiding popularity bias by deliberately excluding the members feature from the similarity calculation.
"""