# -*- coding: utf-8 -*-
"""RNN Assessment.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/19WVmHA8dmVNRyiWjtf_jGV4SjHP7P_6T
"""

# import libraries
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

from sklearn.preprocessing import MinMaxScaler
from sklearn.metrics import mean_squared_error, mean_absolute_error
from statsmodels.tsa.seasonal import seasonal_decompose

import tensorflow as tf
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import SimpleRNN, LSTM, GRU, Dense, Dropout
from tensorflow.keras.callbacks import EarlyStopping

np.random.seed(42)
tf.random.set_seed(42)

import warnings
warnings.filterwarnings('ignore')

df=pd.read_csv('monthly_milk_production.csv')
df

df.head()

df.shape

df.size

df.info()

df.describe()

df.isnull().sum()

df.duplicated().sum()

# convert date to column
df['Date'] = pd.to_datetime(df['Date'])
df = df.sort_values('Date')
df = df.set_index('Date')
print(df.head())

# Plot montly production
plt.figure(figsize=(14, 6))
plt.plot(
    df.index,
    df['Production'],
    linewidth=2
)
plt.title("Monthly Milk Production Over Time")
plt.xlabel("Date")
plt.ylabel("Milk Production")
plt.grid(True)
plt.show()

# distrubution of production
plt.figure(figsize=(8, 5))
sns.histplot(
    df['Production'],
    kde=True
)
plt.title("Distribution of Monthly Milk Production")
plt.xlabel("Production")
plt.ylabel("Frequency")
plt.show()

# Box plot for outliers
plt.figure(figsize=(8, 4))
sns.boxplot(
    x=df['Production']
)
plt.title("Box Plot of Milk Production")
plt.xlabel("Production")
plt.show()

Q1 = df['Production'].quantile(0.25)
Q3 = df['Production'].quantile(0.75)
IQR = Q3 - Q1
lower_bound = Q1 - 1.5 * IQR
upper_bound = Q3 + 1.5 * IQR
print("Q1:", Q1)
print("Q3:", Q3)
print("IQR:", IQR)
print("Lower bound:", lower_bound)
print("Upper bound:", upper_bound)

outliers = df[
    (df['Production'] < lower_bound) |
    (df['Production'] > upper_bound)
]
print("Number of possible outliers:", len(outliers))
display(outliers)

# Analyze monthly seasonality
monthly_average = df.groupby(
    df.index.month
)['Production'].mean()
monthly_average

plt.figure(figsize=(10, 5))
plt.plot(range(1, 13),monthly_average.values,marker='o')
plt.xticks(range(1, 13))
plt.title("Average Milk Production by Month")
plt.xlabel("Month")
plt.ylabel("Average Production")
plt.grid(True)
plt.show()

# seasonal decompse
decomposition = seasonal_decompose(df['Production'],model='additive',period=12)
fig = decomposition.plot()
fig.set_size_inches(14, 10)
plt.show()

# Extract production values
values = df['Production'].values
values = values.astype('float32')
values = values.reshape(-1, 1)
print("Shape:", values.shape)

# Train test split the model data
n = len(values)
train_end = int(n * 0.70)
val_end = int(n * 0.85)
train_data = values[:train_end]
validation_data = values[train_end:val_end]
test_data = values[val_end:]
print("Total:", len(values))
print("Training:", len(train_data))
print("Validation:", len(validation_data))
print("Testing:", len(test_data))

## Normalize data
scaler = MinMaxScaler(
    feature_range=(0, 1)
)
# Fit only on training data
scaler.fit(train_data)
scaled_values = scaler.transform(values)
print(scaled_values[:5])

lookback=12

def create_sequences(data, window):
    X = []
    y = []
    for i in range(window, len(data)):
        X.append(data[i-window:i])
        y.append(data[i])
    return np.array(X), np.array(y)

# create training sequnace
train_scaled = scaled_values[:train_end]
X_train, y_train = create_sequences(
    train_scaled,
    lookback
)
print("X_train shape:", X_train.shape)
print("y_train shape:", y_train.shape)

# Cross validation
validation_scaled = scaled_values[train_end-lookback:val_end]
X_val, y_val = create_sequences(validation_scaled,lookback)
print("X_val shape:", X_val.shape)
print("y_val shape:", y_val.shape)

test_scaled = scaled_values[val_end-lookback:]
X_test, y_test = create_sequences(test_scaled,lookback)
print("X_test shape:", X_test.shape)
print("y_test shape:", y_test.shape)

# Build RNN model
def build_rnn():
    model = Sequential()
    model.add(SimpleRNN(64,activation='tanh',input_shape=(lookback, 1)))
    model.add(Dropout(0.2))
    model.add(Dense(32, activation='relu'))
    model.add(Dense(1))
    model.compile(optimizer='adam',loss='mse')
    return model

# Train RNN
rnn_model = build_rnn()
early_stop = EarlyStopping(monitor='val_loss',patience=20,restore_best_weights=True)
rnn_history = rnn_model.fit(X_train,y_train,validation_data=(X_val,y_val),
    epochs=150,
    batch_size=16,
    callbacks=[early_stop],
    verbose=1
)

plt.figure(figsize=(10, 5))
plt.plot(
    rnn_history.history['loss'],
    label='Training Loss'
)
plt.plot(
    rnn_history.history['val_loss'],
    label='Validation Loss'
)
plt.title("RNN Training vs Validation Loss")
plt.xlabel("Epoch")
plt.ylabel("MSE Loss")
plt.legend()
plt.grid(True)
plt.show()

# Build LSTM model
def build_lstm():
  model = Sequential()
  model.add(LSTM(64,activation='tanh',input_shape=(lookback, 1)))
  model.add(Dropout(0.2))
  model.add(Dense(32,activation='relu'))
  model.add(Dense(1))
  model.compile(optimizer='adam',loss='mse')
  return model

## Train LSTM
lstm_model = build_lstm()
lstm_history = lstm_model.fit(X_train,y_train,validation_data=(X_val,y_val),
epochs=150,
batch_size=16,
callbacks=[early_stop],
verbose=1
)

plt.figure(figsize=(10, 5))
plt.plot(
    lstm_history.history['loss'],
    label='Training Loss'
)
plt.plot(
    lstm_history.history['val_loss'],
    label='Validation Loss'
)
plt.title("LSTM Training vs Validation Loss")
plt.xlabel("Epoch")
plt.ylabel("MSE Loss")
plt.legend()
plt.grid(True)
plt.show()

# Build GRU
def build_gru():
    model = Sequential()
    model.add(GRU(64,activation='tanh',input_shape=(lookback, 1)))
    model.add(Dropout(0.2))
    model.add(Dense(32,activation='relu'))
    model.add(Dense(1))
    model.compile(optimizer='adam',loss='mse')
    return model

# Train GRU
gru_model = build_gru()
gru_history = gru_model.fit(X_train,y_train,validation_data=(X_val,y_val),
epochs=150,
batch_size=16,
callbacks=[early_stop],
verbose=1
)

# Loss plot
plt.figure(figsize=(10, 5))
plt.plot(
    gru_history.history['loss'],
    label='Training Loss'
)
plt.plot(
    gru_history.history['val_loss'],
    label='Validation Loss'
)
plt.title("GRU Training vs Validation Loss")
plt.xlabel("Epoch")
plt.ylabel("MSE Loss")
plt.legend()
plt.grid(True)
plt.show()

# Create evalution function
def evaluate_model(model, X_test, y_test):
    predictions_scaled = model.predict(X_test,verbose=0)
    actual = scaler.inverse_transform(y_test.reshape(-1, 1)).ravel()
    predictions = scaler.inverse_transform(predictions_scaled).ravel()
    rmse = np.sqrt(mean_squared_error(actual,predictions))
    mae = mean_absolute_error(actual,predictions)
    mape = np.mean(np.abs((actual - predictions) /np.where(actual == 0, 1, actual))) * 100
    return rmse, mae, mape, actual, predictions

# Evaluate models
results = []
predictions = {}
models = {
    'RNN': rnn_model,
    'LSTM': lstm_model,
    'GRU': gru_model
}
for name, model in models.items():
    rmse, mae, mape, actual, pred = evaluate_model(model,X_test,y_test)
    results.append([name,rmse,mae,mape])
    predictions[name] = pred

# Model comparision table
results_df = pd.DataFrame(results,columns=['Model','RMSE','MAE','MAPE (%)'])
results_df = results_df.sort_values(by='RMSE').reset_index(drop=True)
display(results_df)

# Actual vs Predicted plot
test_dates = df.index[val_end:]
actual_test = scaler.inverse_transform(y_test.reshape(-1, 1)).ravel()
plt.figure(figsize=(14, 6))
plt.plot(test_dates,actual_test,label='Actual',linewidth=2)
plt.plot(test_dates,predictions['RNN'],label='RNN')
plt.plot(test_dates,predictions['LSTM'],label='LSTM')
plt.plot(test_dates,predictions['GRU'],label='GRU')
plt.title("Actual vs RNN, LSTM and GRU Predictions")
plt.xlabel("Date")
plt.ylabel("Production")
plt.legend()
plt.grid(True)
plt.show()

# Compare RMSE
plt.figure(figsize=(8, 5))
plt.bar(results_df['Model'],results_df['RMSE'])
plt.title("RMSE Comparison")
plt.xlabel("Model")
plt.ylabel("RMSE")
plt.show()

## Compare MAE
plt.figure(figsize=(8, 5))
plt.bar(results_df['Model'],results_df['MAE'])
plt.title("MAE Comparison")
plt.xlabel("Model")
plt.ylabel("MAE")
plt.show()

# Comapre MAPE
plt.figure(figsize=(8, 5))
plt.bar(results_df['Model'],results_df['MAPE (%)'])
plt.title("MAPE Comparison")
plt.xlabel("Model")
plt.ylabel("MAPE (%)")
plt.show()

# Hypertuning
def prepare_sequences_for_window(window):
    train_scaled = scaled_values[:train_end]
    validation_scaled = scaled_values[train_end-window:val_end]
    X_train_temp, y_train_temp = create_sequences(train_scaled,window)
    X_val_temp, y_val_temp = create_sequences(validation_scaled,window)
    return (X_train_temp,y_train_temp,X_val_temp,y_val_temp)

# Tune LSTM
tuning_results = []
for window in [6, 12, 18]:
    Xtr, ytr, Xv, yv = prepare_sequences_for_window(window)
    for units in [32, 64]:
        model = Sequential()
        model.add(LSTM(units,activation='tanh',input_shape=(window, 1)))
        model.add(Dropout(0.2))
        model.add(Dense(1))
        model.compile(optimizer='adam',loss='mse')
        early_stop_tuning = EarlyStopping(monitor='val_loss',patience=10,restore_best_weights=True)
        model.fit(Xtr,ytr,validation_data=(Xv, yv),epochs=80,batch_size=16,callbacks=[early_stop_tuning],verbose=0)
        val_pred_scaled = model.predict(Xv,verbose=0)
        val_actual = scaler.inverse_transform(yv.reshape(-1, 1)).ravel()
        val_pred = scaler.inverse_transform(val_pred_scaled).ravel()
        rmse = np.sqrt(mean_squared_error(val_actual,val_pred))
        tuning_results.append([window,units,rmse])

tuning_df = pd.DataFrame(tuning_results,columns=['Window Size','LSTM Units','Validation RMSE'])
tuning_df = tuning_df.sort_values(by='Validation RMSE').reset_index(drop=True)
display(tuning_df)

best_model_name = results_df.iloc[0]['Model']
print("Best Model:",best_model_name)

# Forecast next 12 months
history = list(scaled_values[-lookback:].ravel())
future_scaled = []

# Get the actual model object from the models dictionary
best_model = models[best_model_name]

for i in range(12):
    input_data = np.array(history[-lookback:])
    input_data = input_data.reshape(1, lookback, 1)
    next_prediction = best_model.predict(input_data, verbose=0)[0, 0]
    future_scaled.append(next_prediction)
    history.append(next_prediction)

# Inverse transform the forecasted values
future_forecast = scaler.inverse_transform(np.array(future_scaled).reshape(-1, 1)).ravel()

# Generate future dates for the next 12 months starting after the last date in the dataframe
last_date = df.index[-1]
future_dates = pd.date_range(start=last_date + pd.DateOffset(months=1), periods=12, freq='MS')

# Create a forecast DataFrame
forecast_df = pd.DataFrame(data={'Forecast': future_forecast}, index=future_dates)
print(forecast_df)

# Plot the historical data alongside the future forecast
plt.figure(figsize=(14, 6))
plt.plot(df.index, df['Production'], label='Historical Production', linewidth=2)
plt.plot(forecast_df.index, forecast_df['Forecast'], label='RNN 12-Month Forecast', color='red', linestyle='--', marker='o')
plt.title("Monthly Milk Production - Historical vs 12-Month Future Forecast")
plt.xlabel("Date")
plt.ylabel("Milk Production")
plt.legend()
plt.grid(True)
plt.show()

best_predictions = predictions[best_model_name]
residuals = actual_test - best_predictions
residual_std = np.std(residuals)
print("Residual Standard Deviation:",residual_std)

forecast_df['Lower_95'] = (forecast_df['Forecast'] - 1.96 * residual_std)
forecast_df['Upper_95'] = (forecast_df['Forecast'] + 1.96 * residual_std)
forecast_df['Lower_95'] = (forecast_df['Lower_95'].clip(lower=0))
display(forecast_df)

# Plot the historical data along with forecast and confidence intervals
plt.figure(figsize=(14, 6))
plt.plot(df.index, df['Production'], label='Historical Production', linewidth=2)
plt.plot(forecast_df.index, forecast_df['Forecast'], label='RNN 12-Month Forecast', color='red', linestyle='--', marker='o')
plt.fill_between(
    forecast_df.index,
    forecast_df['Lower_95'],
    forecast_df['Upper_95'],
    color='pink',
    alpha=0.4,
    label='95% Confidence Interval'
)
plt.title("Monthly Milk Production - Historical vs 12-Month Forecast with 95% Confidence Intervals")
plt.xlabel("Date")
plt.ylabel("Milk Production")
plt.legend()
plt.grid(True)
plt.show()

## Display final forecast
final_forecast = forecast_df.copy()
final_forecast['Forecast_Production'] = (final_forecast['Forecast'].round(2))
final_forecast['Lower_95'] = (final_forecast['Lower_95'].round(2))
final_forecast['Upper_95'] = (final_forecast['Upper_95'].round(2))
# Drop the old unrounded Forecast column if you only want Forecast_Production
final_forecast = final_forecast.drop(columns=['Forecast'])
display(final_forecast)

"""### Conclusion

* The project successfully performed **monthly milk production forecasting** using deep learning-based time series models.
* The data was organized chronologically, analyzed for trends and seasonality, and normalized using **MinMaxScaler**.
* A **12-month lookback window** was used to create sequential input data for the neural network models.
* Three models — **RNN, LSTM, and GRU** — were trained and evaluated using **RMSE, MAE, and MAPE**.
* The models were compared based on their forecasting performance, with **lower RMSE, MAE, and MAPE indicating better performance**.
* Hyperparameter tuning was also performed for the **LSTM model** using different window sizes and numbers of LSTM units.
* The best-performing model from the model comparison was selected for forecasting the **next 12 months of milk production**.
* A **95% confidence interval** was also calculated around the future forecasts to represent forecast uncertainty.
* Overall, the project demonstrates that **RNN-based deep learning models can effectively capture temporal patterns and seasonality in monthly milk production data**.
* The final selected model provides a practical approach for generating future milk-production forecasts based on historical patterns.

"""