# -*- coding: utf-8 -*-
"""SVM(Support Vector Machine) Assign.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1U6Cfb0S1FkhcxZr1lZQ5cMZjJuU1xeDY
"""

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
import warnings
warnings.filterwarnings('ignore')

from sklearn.model_selection import train_test_split
from sklearn.preprocessing import LabelEncoder, StandardScaler
from sklearn.svm import SVC

from sklearn.metrics import accuracy_score
from sklearn.metrics import precision_score
from sklearn.metrics import recall_score
from sklearn.metrics import f1_score
from sklearn.metrics import classification_report
from sklearn.metrics import confusion_matrix

df=pd.read_csv('Pharma_Industry (1).csv')
df

df.head()

df.info()

df.describe()

df.shape

df.size

df.isnull().sum()

df.duplicated().sum()

## Task 1 : feature distrubution
df.hist(figsize=(15, 10), bins=20)
plt.tight_layout()
plt.show()

for i in df.select_dtypes(include=['int','float']).columns:
  sns.boxplot(df[i])
  plt.title("Box Plot of Features")
  plt.show()

for i in df.select_dtypes(include=['int','float']).columns:
    q1=df[i].quantile(0.25)
    q3=df[i].quantile(0.75)
    IQR=q3-q1
    lower_bound=q1-1.5*IQR
    upper_bound=q3+1.5*IQR
    df[i]=df[i].clip(lower_bound,upper_bound)

for i in df.select_dtypes(include=['int','float']).columns:
  sns.boxplot(df[i])
  plt.title("Box Plot of Features")
  plt.show()

##Density plots
numeric_columns = df.select_dtypes(include=np.number).columns
df[numeric_columns].plot(
    kind='density',
    subplots=True,
    layout=(3, 3),
    figsize=(15, 10),
    sharex=False
)
plt.tight_layout()
plt.show()

## feature correlation
numeric_df = df.select_dtypes(include=np.number)
correlation = numeric_df.corr()
print(correlation)

## Correlation heatmap
plt.figure(figsize=(12, 8))
sns.heatmap(
    correlation,
    annot=True,
    cmap='coolwarm',
    fmt='.2f'
)
plt.title("Feature Correlation Heatmap")
plt.show()

# Set target column (matches actual dataframe column name)
target_column = "Drug Response"
# Separate feature and target
X = df.drop(target_column, axis=1)
y = df[target_column]

print("Features:")
print(X.head())

print("\nTarget:")
print(y.head())

X.head()

# Enocde target variables
label_encoder = LabelEncoder()
y = label_encoder.fit_transform(y)
print("Encoded target:")
print(y[:10])

# Train test slpit
X_train, X_test, y_train, y_test = train_test_split(X,y,test_size=0.20,random_state=42,stratify=y)
print("training data:", X_train.shape)
print("testing data:", X_test.shape)

# Feature scaling
scaler = StandardScaler()
X_train = scaler.fit_transform(X_train)
X_test = scaler.transform(X_test)
plt.figure(figsize=(7, 5))
sns.countplot(x=y)
plt.title("Class Distribution")
plt.xlabel("Drug Response Class")
plt.ylabel("Number of Samples")
plt.show()
unique, counts = np.unique(y, return_counts=True)
for i in range(len(unique)):
    print("Class", unique[i], ":", counts[i])

pair_columns = df.select_dtypes(include=np.number).columns
sns.pairplot(df[pair_columns])
plt.show()

# Scater plot
numeric_columns = df.select_dtypes(include=np.number).columns
plt.figure(figsize=(8, 6))
plt.scatter(
    df[numeric_columns[0]],
    df[numeric_columns[1]],
    c=y,
    cmap='viridis'
)
plt.xlabel(numeric_columns[0])
plt.ylabel(numeric_columns[1])
plt.title("Scatter Plot of First Two Features")
plt.show()

# SVM implementation
svm_model = SVC(
    kernel='rbf',
    C=1.0,
    gamma='scale'
)
svm_model.fit(X_train, y_train)

y_pred = svm_model.predict(X_test)

# Evalute model
#Accuracy
accuracy = accuracy_score(y_test, y_pred)
print("Accuracy:", accuracy)

## precision
precision = precision_score(
    y_test,
    y_pred,
    average='weighted'
)
print("Precision:", precision)

## recall
recall = recall_score(
    y_test,
    y_pred,
    average='weighted'
)
print("Recall:", recall)

#F1 score
f1 = f1_score(
    y_test,
    y_pred,
    average='weighted'
)
print("F1 Score:", f1)

print("Classification Report:")
print(classification_report(y_test, y_pred))

#visuals of SVM
cm = confusion_matrix(y_test, y_pred)

plt.figure(figsize=(7, 5))

sns.heatmap(
    cm,
    annot=True,
    fmt='d',
    cmap='Blues'
)

plt.xlabel("Predicted Class")
plt.ylabel("Actual Class")
plt.title("SVM Confusion Matrix")

plt.show()

## actual Vs predicted values
plt.figure(figsize=(10, 5))
plt.plot(
    y_test[:50],
    marker='o',
    label='Actual'
)
plt.plot(
    y_pred[:50],
    marker='x',
    label='Predicted'
)
plt.title("Actual vs Predicted Classes")
plt.xlabel("Test Sample")
plt.ylabel("Class")
plt.legend()
plt.show()

## Task 6: Parameter Tuning and Optimization
C_values = [0.1, 1, 10, 100]
results = []
for c in C_values:
    model = SVC(
        kernel='rbf',
        C=c,
        gamma='scale'
    )
    model.fit(X_train, y_train)
    prediction = model.predict(X_test)
    accuracy = accuracy_score(y_test, prediction)
    results.append([c, accuracy])

results_df = pd.DataFrame(results,columns=['C', 'Accuracy'])
print(results_df)

## plot c vs accuracy
plt.figure(figsize=(8, 5))
plt.plot(
    results_df['C'],
    results_df['Accuracy'],
    marker='o'
)
plt.xscale('log')
plt.xlabel("C")
plt.ylabel("Accuracy")
plt.title("C Value vs Accuracy")

plt.show()

# diffrent gamma values
gamma_values = ['scale', 0.001, 0.01, 0.1, 1]
gamma_results = []
for gamma in gamma_values:
    model = SVC(
        kernel='rbf',
        C=1,
        gamma=gamma
    )
    model.fit(X_train, y_train)
    prediction = model.predict(X_test)
    accuracy = accuracy_score(y_test, prediction)
    gamma_results.append([gamma, accuracy])

gamma_df = pd.DataFrame(
    gamma_results,
    columns=['Gamma', 'Accuracy']
)
print(gamma_df)

# Comparison of Different SVM Kernels
kernels = ['linear', 'poly', 'rbf']
kernel_results = []
for kernel in kernels:
    model = SVC(
        kernel=kernel,
        C=1
    )
    model.fit(X_train, y_train)
    prediction = model.predict(X_test)
    accuracy = accuracy_score(y_test, prediction)
    precision = precision_score(
        y_test,
        prediction,
        average='weighted'
    )
    recall = recall_score(
        y_test,
        prediction,
        average='weighted'
    )
    f1 = f1_score(
        y_test,
        prediction,
        average='weighted'
    )
    kernel_results.append([
        kernel,
        accuracy,
        precision,
        recall,
        f1
    ])
kernel_df = pd.DataFrame(
    kernel_results,
    columns=[
        'Kernel',
        'Accuracy',
        'Precision',
        'Recall',
        'F1 Score'
    ]
)
print(kernel_df)

kernel_df.plot(
    x='Kernel',
    y=['Accuracy', 'Precision', 'Recall', 'F1 Score'],
    kind='bar',
    figsize=(10, 6)
)
plt.title("SVM Kernel Performance Comparison")
plt.ylabel("Score")
plt.ylim(0, 1)
plt.xticks(rotation=0)
plt.show()