# -*- coding: utf-8 -*-
"""SVM(Support Vector Machine) Assign.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1U6Cfb0S1FkhcxZr1lZQ5cMZjJuU1xeDY
"""

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
import warnings
warnings.filterwarnings('ignore')

from sklearn.model_selection import train_test_split
from sklearn.preprocessing import LabelEncoder, StandardScaler
from sklearn.svm import SVC

from sklearn.metrics import accuracy_score
from sklearn.metrics import precision_score
from sklearn.metrics import recall_score
from sklearn.metrics import f1_score
from sklearn.metrics import classification_report
from sklearn.metrics import confusion_matrix

df=pd.read_csv('Pharma_Industry (1).csv')
df

df.head()

df.info()

df.describe()

df.shape

df.size

df.isnull().sum()

df.duplicated().sum()

## Task 1 : feature distrubution
df.hist(figsize=(15, 10), bins=20)
plt.tight_layout()
plt.show()

for i in df.select_dtypes(include=['int','float']).columns:
  sns.boxplot(df[i])
  plt.title("Box Plot of Features")
  plt.show()

for i in df.select_dtypes(include=['int','float']).columns:
    q1=df[i].quantile(0.25)
    q3=df[i].quantile(0.75)
    IQR=q3-q1
    lower_bound=q1-1.5*IQR
    upper_bound=q3+1.5*IQR
    df[i]=df[i].clip(lower_bound,upper_bound)

for i in df.select_dtypes(include=['int','float']).columns:
  sns.boxplot(df[i])
  plt.title("Box Plot of Features")
  plt.show()

##Density plots
numeric_columns = df.select_dtypes(include=np.number).columns
df[numeric_columns].plot(
    kind='density',
    subplots=True,
    layout=(3, 3),
    figsize=(15, 10),
    sharex=False
)
plt.tight_layout()
plt.show()

## feature correlation
numeric_df = df.select_dtypes(include=np.number)
correlation = numeric_df.corr()
print(correlation)

## Correlation heatmap
plt.figure(figsize=(12, 8))
sns.heatmap(
    correlation,
    annot=True,
    cmap='coolwarm',
    fmt='.2f'
)
plt.title("Feature Correlation Heatmap")
plt.show()

# Set target column (matches actual dataframe column name)
target_column = "Drug Response"
# Separate feature and target
X = df.drop(target_column, axis=1)
y = df[target_column]

print("Features:")
print(X.head())

print("\nTarget:")
print(y.head())

X.head()

# Enocde target variables
label_encoder = LabelEncoder()
y = label_encoder.fit_transform(y)
print("Encoded target:")
print(y[:10])

# Train test slpit
X_train, X_test, y_train, y_test = train_test_split(X,y,test_size=0.20,random_state=42,stratify=y)
print("training data:", X_train.shape)
print("testing data:", X_test.shape)

# Feature scaling
scaler = StandardScaler()
X_train = scaler.fit_transform(X_train)
X_test = scaler.transform(X_test)
plt.figure(figsize=(7, 5))
sns.countplot(x=y)
plt.title("Class Distribution")
plt.xlabel("Drug Response Class")
plt.ylabel("Number of Samples")
plt.show()
unique, counts = np.unique(y, return_counts=True)
for i in range(len(unique)):
    print("Class", unique[i], ":", counts[i])

pair_columns = df.select_dtypes(include=np.number).columns
sns.pairplot(df[pair_columns])
plt.show()

# Scater plot
numeric_columns = df.select_dtypes(include=np.number).columns
plt.figure(figsize=(8, 6))
plt.scatter(
    df[numeric_columns[0]],
    df[numeric_columns[1]],
    c=y,
    cmap='viridis'
)
plt.xlabel(numeric_columns[0])
plt.ylabel(numeric_columns[1])
plt.title("Scatter Plot of First Two Features")
plt.show()

# SVM implementation
svm_model = SVC(
    kernel='rbf',
    C=1.0,
    gamma='scale'
)
svm_model.fit(X_train, y_train)

y_pred = svm_model.predict(X_test)

# Evalute model
#Accuracy
accuracy = accuracy_score(y_test, y_pred)
print("Accuracy:", accuracy)

## precision
precision = precision_score(
    y_test,
    y_pred,
    average='weighted'
)
print("Precision:", precision)

## recall
recall = recall_score(
    y_test,
    y_pred,
    average='weighted'
)
print("Recall:", recall)

#F1 score
f1 = f1_score(
    y_test,
    y_pred,
    average='weighted'
)
print("F1 Score:", f1)

print("Classification Report:")
print(classification_report(y_test, y_pred))

#visuals of SVM
cm = confusion_matrix(y_test, y_pred)

plt.figure(figsize=(7, 5))

sns.heatmap(
    cm,
    annot=True,
    fmt='d',
    cmap='Blues'
)

plt.xlabel("Predicted Class")
plt.ylabel("Actual Class")
plt.title("SVM Confusion Matrix")

plt.show()

## actual Vs predicted values
plt.figure(figsize=(10, 5))
plt.plot(
    y_test[:50],
    marker='o',
    label='Actual'
)
plt.plot(
    y_pred[:50],
    marker='x',
    label='Predicted'
)
plt.title("Actual vs Predicted Classes")
plt.xlabel("Test Sample")
plt.ylabel("Class")
plt.legend()
plt.show()

## Task 6: Parameter Tuning and Optimization
C_values = [0.1, 1, 10, 100]
results = []
for c in C_values:
    model = SVC(
        kernel='rbf',
        C=c,
        gamma='scale'
    )
    model.fit(X_train, y_train)
    prediction = model.predict(X_test)
    accuracy = accuracy_score(y_test, prediction)
    results.append([c, accuracy])

results_df = pd.DataFrame(results,columns=['C', 'Accuracy'])
print(results_df)

## plot c vs accuracy
plt.figure(figsize=(8, 5))
plt.plot(
    results_df['C'],
    results_df['Accuracy'],
    marker='o'
)
plt.xscale('log')
plt.xlabel("C")
plt.ylabel("Accuracy")
plt.title("C Value vs Accuracy")

plt.show()

# diffrent gamma values
gamma_values = ['scale', 0.001, 0.01, 0.1, 1]
gamma_results = []
for gamma in gamma_values:
    model = SVC(
        kernel='rbf',
        C=1,
        gamma=gamma
    )
    model.fit(X_train, y_train)
    prediction = model.predict(X_test)
    accuracy = accuracy_score(y_test, prediction)
    gamma_results.append([gamma, accuracy])

gamma_df = pd.DataFrame(
    gamma_results,
    columns=['Gamma', 'Accuracy']
)
print(gamma_df)

# Comparison of Different SVM Kernels
kernels = ['linear', 'poly', 'rbf']
kernel_results = []
for kernel in kernels:
    model = SVC(
        kernel=kernel,
        C=1
    )
    model.fit(X_train, y_train)
    prediction = model.predict(X_test)
    accuracy = accuracy_score(y_test, prediction)
    precision = precision_score(
        y_test,
        prediction,
        average='weighted'
    )
    recall = recall_score(
        y_test,
        prediction,
        average='weighted'
    )
    f1 = f1_score(
        y_test,
        prediction,
        average='weighted'
    )
    kernel_results.append([
        kernel,
        accuracy,
        precision,
        recall,
        f1
    ])
kernel_df = pd.DataFrame(
    kernel_results,
    columns=[
        'Kernel',
        'Accuracy',
        'Precision',
        'Recall',
        'F1 Score'
    ]
)
print(kernel_df)

kernel_df.plot(
    x='Kernel',
    y=['Accuracy', 'Precision', 'Recall', 'F1 Score'],
    kind='bar',
    figsize=(10, 6)
)
plt.title("SVM Kernel Performance Comparison")
plt.ylabel("Score")
plt.ylim(0, 1)
plt.xticks(rotation=0)
plt.show()

"""# Support Vector Machine (SVM) – Drug Response Classification Report

## 1. Business Context

Pharmaceutical companies invest significant resources in clinical trials to evaluate drug efficacy. However, individual differences in biology, metabolism, and pre-existing conditions can cause patients to respond differently to the same drug.

Traditional clinical trials can take years and involve substantial costs and risks. Machine learning can help predict drug response at an earlier stage, potentially supporting more efficient decision-making and personalized medicine.

The objective of this project is therefore to classify whether a patient is likely to respond to a drug based on selected clinical and drug-related features.

---

# 2. Dataset Description

The dataset used is `Pharma_Industry.csv`.

It contains **500 observations and 6 variables**.

### Features

1. Drug Dosage (mg)
2. Systolic Blood Pressure (mmHg)
3. Heart Rate (BPM)
4. Liver Toxicity Index (U/L)
5. Blood Glucose Level (mg/dL)

### Target

**Drug Response**

* `0` → Class 0
* `1` → Class 1

The dataset contains:

* **240 observations of Class 0**
* **260 observations of Class 1**

Therefore, the target variable is relatively balanced.

---

# 3. Data Quality Analysis

The dataset contains **500 non-null observations for all six variables**.

### Missing Values

There are **no missing values** in the dataset.

### Duplicate Values

The dataset contains **0 duplicate records**.

Therefore, no records were removed during duplicate removal, and the final dataset remains:

**500 rows × 6 columns**

---

# 4. Exploratory Data Analysis

Several exploratory visualizations were performed:

* Histograms
* Box plots
* Density plots
* Correlation matrix
* Correlation heatmap
* Pair plot
* Scatter plot
* Class distribution plot

These visualizations were used to understand feature distributions, possible outliers, relationships between variables, and the distribution of the target classes.

---

# 5. Correlation Analysis

The correlation analysis showed relatively weak relationships among most predictor variables.

Some notable correlations with the target `Drug Response` were:

| Feature                 | Correlation with Drug Response |
| ----------------------- | -----------------------------: |
| Liver Toxicity Index    |                      **0.435** |
| Systolic Blood Pressure |                      **0.305** |
| Blood Glucose Level     |                      **0.229** |
| Drug Dosage             |                          0.043 |
| Heart Rate              |                         -0.010 |

### Interpretation

The **Liver Toxicity Index** had the strongest linear correlation with Drug Response at approximately **0.435**.

Systolic Blood Pressure showed the second strongest relationship at approximately **0.305**.

Drug Dosage and Heart Rate had very weak linear correlations with the target.

However, correlation alone does not determine predictive importance, particularly for an SVM with a nonlinear RBF kernel.

---

# 6. Data Preprocessing

The target variable was separated from the predictor variables.

### Features

The five clinical/drug-related variables were used as predictors.

### Target

`Drug Response` was used as the classification target.

The dataset contained no categorical predictor variables, so no categorical encoding was required.

The target was passed through `LabelEncoder`, resulting in two classes:

**[0, 1]**

The dataset was divided using an **80:20 stratified train-test split**.

### Training Data

**400 observations**

### Testing Data

**100 observations**

StandardScaler was then applied to the features.

Feature scaling is particularly important for SVM because SVM relies on distances and the relative scale of features can strongly influence the decision boundary.

---

# 7. SVM Model

A Support Vector Classifier was trained using an **RBF (Radial Basis Function) kernel**.

Initial parameters:

* Kernel = `rbf`
* C = `1.0`
* Gamma = `scale`

The RBF kernel allows the SVM to model nonlinear relationships between the clinical features and drug response.

---

# 8. Initial SVM Performance

The initial RBF SVM achieved:

| Metric             |      Score |
| ------------------ | ---------: |
| Accuracy           | **77.00%** |
| Weighted Precision | **77.18%** |
| Weighted Recall    | **77.00%** |
| Weighted F1 Score  | **76.90%** |

Therefore, the model correctly classified approximately **77% of the test observations**.

---

# 9. Classification Report

The class-wise results were:

| Class       | Precision |   Recall | F1 Score | Support |
| ----------- | --------: | -------: | -------: | ------: |
| Class 0     |      0.79 |     0.71 |     0.75 |      48 |
| Class 1     |      0.75 |     0.83 |     0.79 |      52 |
| **Overall** |  **0.77** | **0.77** | **0.77** | **100** |

### Interpretation

The model performed better at identifying **Class 1**:

* Recall = **83%**
* F1-score = **79%**

For Class 0:

* Recall = **71%**
* F1-score = **75%**

This indicates that the SVM was somewhat better at identifying positive drug-response cases than negative cases.

---

# 10. Hyperparameter Tuning – C

Different values of the regularization parameter `C` were tested:

* 0.1
* 1
* 10
* 100

The results were:

|       C | Accuracy |
| ------: | -------: |
| **0.1** |  **78%** |
|       1 |      77% |
|      10 |      75% |
|     100 |      72% |

### Insight

The best performance was obtained with:

**C = 0.1 → Accuracy = 78%**

As C increased beyond 0.1, accuracy decreased.

This suggests that stronger regularization produced better generalization on this particular test set.

---

# 11. Hyperparameter Tuning – Gamma

The following gamma values were tested:

* `scale`
* 0.001
* 0.01
* 0.1
* 1

Results:

| Gamma | Accuracy |
| ----- | -------: |
| scale |  **77%** |
| 0.001 |      74% |
| 0.01  |      70% |
| 0.1   |  **77%** |
| 1     |      72% |

### Insight

The best gamma performance was **77%**, obtained with both:

* `gamma = scale`
* `gamma = 0.1`

Very low gamma values reduced model performance, while gamma = 1 also resulted in lower accuracy.

---

# 12. SVM Kernel Comparison

Three different SVM kernels were compared:

* Linear
* Polynomial
* RBF

The results were:

| Kernel     | Accuracy |  Precision |  Recall |   F1 Score |
| ---------- | -------: | ---------: | ------: | ---------: |
| Linear     |      72% |     72.45% |     72% |     71.97% |
| Polynomial |      65% |     65.03% |     65% |     65.01% |
| **RBF**    |  **77%** | **77.18%** | **77%** | **76.90%** |

---

# 13. Kernel Comparison Insights

### RBF Kernel

The RBF kernel achieved the best overall performance:

**Accuracy = 77%**

This indicates that the relationship between the clinical features and drug response may contain nonlinear patterns that are better captured by the RBF kernel.

### Linear Kernel

The linear kernel achieved:

**72% accuracy**

This is lower than the RBF kernel, suggesting that a purely linear decision boundary may not adequately capture the relationships in this dataset.

### Polynomial Kernel

The polynomial kernel performed the worst:

**65% accuracy**

Therefore, the polynomial kernel was not suitable for this particular dataset and parameter configuration.

---

# 14. Key Insights

### Insight 1 – Dataset quality is good

There are no missing values and no duplicate records, so the dataset required minimal data cleaning.

### Insight 2 – Classes are relatively balanced

The dataset contains:

* Class 0 → 240 observations
* Class 1 → 260 observations

This relatively balanced distribution reduces the risk of the model being heavily biased toward one class.

### Insight 3 – Feature scaling is important

StandardScaler was used before SVM training. This is important because SVM relies on distances and the geometry of the feature space.

### Insight 4 – RBF is the best kernel

Among the three tested kernels:

**RBF > Linear > Polynomial**

RBF achieved the highest accuracy, precision, recall, and F1-score.

### Insight 5 – Lower C performed better

The best C value tested was:

**C = 0.1**

with an accuracy of **78%**.

Increasing C from 0.1 to 100 progressively reduced test accuracy.

### Insight 6 – Liver Toxicity has the strongest linear relationship

The Liver Toxicity Index had the highest correlation with Drug Response:

**r ≈ 0.435**

However, this does not mean it is necessarily the most important feature for the nonlinear SVM model.

### Insight 7 – The model identifies positive response relatively well

For Class 1, the model achieved:

**Recall = 83%**

This means the model correctly identified a relatively high proportion of actual Class 1 cases.

---

# 15. Final Model Comparison

Based on the experiments performed:

| Experiment      |       Best Result |
| --------------- | ----------------: |
| Initial RBF SVM |      77% Accuracy |
| Best C          | **C = 0.1 → 78%** |
| Best Gamma      |           **77%** |
| Best Kernel     |     **RBF → 77%** |

The best individual accuracy observed during parameter testing was:

**78% with C = 0.1**

---

# 16. Final Conclusion

The SVM model was successfully developed to classify drug response using five clinical and drug-related features.

The dataset contained **500 observations**, with no missing values or duplicate records. The target classes were relatively balanced, with 240 observations in Class 0 and 260 observations in Class 1.

After preprocessing and standardization, an RBF-based SVM achieved **77% accuracy**, with a weighted precision of **77.18%**, weighted recall of **77%**, and weighted F1-score of **76.90%**.

The hyperparameter analysis showed that the regularization parameter had a noticeable effect on performance. Among the tested values, **C = 0.1 produced the highest accuracy of 78%**. Increasing C resulted in progressively lower accuracy.

The comparison of SVM kernels showed that the **RBF kernel was the best-performing kernel**, achieving 77% accuracy compared with 72% for the linear kernel and 65% for the polynomial kernel. This suggests that nonlinear relationships between the input features and drug response are important for this classification problem.

The classification report also showed that the model achieved a **recall of 83% for Class 1**, indicating relatively good identification of positive drug-response cases.

Overall, the analysis demonstrates that **SVM with an RBF kernel is a suitable approach for this drug-response classification dataset**, with the best observed test accuracy of 78% using C = 0.1.

However, this model is intended for analytical and educational purposes. It should not be considered a substitute for clinical trials, medical expertise, or real-world pharmaceutical decision-making without extensive external validation.

## Final Finding

**Best kernel:** RBF
**Best tested C:** 0.1
**Best observed accuracy:** 78%
**Initial RBF accuracy:** 77%
**Best class-1 recall:** 83%

"""