# -*- coding: utf-8 -*-
"""Time series Assessment.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1-ZnYf7dCsBG7u_cmjLBECYkO9WRj7TFq
"""

# import libraries
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import matplotlib.dates as mdates

from statsmodels.tsa.stattools import adfuller
from statsmodels.graphics.tsaplots import plot_acf, plot_pacf
from statsmodels.tsa.arima.model import ARIMA
from statsmodels.tsa.holtwinters import ExponentialSmoothing, Holt
from statsmodels.stats.diagnostic import acorr_ljungbox
from sklearn.metrics import mean_absolute_error, mean_squared_error

import warnings
warnings.filterwarnings("ignore")

pip install statsmodels

df = pd.read_csv("exchange_rate.csv")
df

df.head()

df.size

df.shape

df["date"] = pd.to_datetime(df["date"], format="%d-%m-%Y %H:%M")
df = df.set_index("date").sort_index()
df = df.rename(columns={"Ex_rate": "USD_AUD"})
print(f"Date range: {df.index.min().date()}  to  {df.index.max().date()}")

df.info()

df.describe()

df.isnull().sum()

df.duplicated().sum()

# plot history
fig, ax = plt.subplots()
ax.plot(df.index, df["USD_AUD"], linewidth=0.8, color="steelblue")
ax.set_title("USD/AUD Exchange Rate (Daily), 1990–2010")
ax.set_xlabel("Date")
ax.set_ylabel("USD to AUD Rate")
plt.tight_layout()
plt.show()

recent = df.loc[df.index >= (df.index.max() - pd.DateOffset(years=3))]
fig, ax = plt.subplots()
ax.plot(recent.index, recent["USD_AUD"], color="darkorange")
ax.set_title("USD/AUD Exchange Rate — Last 3 Years")
ax.set_xlabel("Date")
ax.set_ylabel("USD to AUD Rate")
plt.tight_layout()
plt.show()

# check calander gaps/missing values
full_range = pd.date_range(df.index.min(), df.index.max(), freq="D")
missing_dates = full_range.difference(df.index)
print(f"Total calendar days in range: {len(full_range)}")
print(f"Dates present in dataset:     {len(df)}")
print(f"Missing calendar dates:       {len(missing_dates)}")
print("\nDay-of-week counts in the dataset:")
print(df.index.day_name().value_counts())

ts = df["USD_AUD"].asfreq("B")
n_filled = ts.isna().sum()
ts = ts.ffill()
print(f"Business-day index length: {len(ts)}")
print(f"Holiday gaps forward-filled: {n_filled}")
ts.tail()

## Stationary checks
def adf_report(series, label):
    result = adfuller(series.dropna(), autolag="AIC")
    print(f"\nADF Test: {label}")
    print(f"ADF statistic: {result[0]:.3f}")
    print(f"p-value:       {result[1]:.3f}")
    print(f"Used lags:     {result[2]}")
    print(f"Critical values: {result[4]}")
    if result[1] < 0.05:
        print("-> Stationary (reject H0 of unit root) at 5% level.")
    else:
        print("-> Non-stationary (fail to reject H0 of unit root) at 5% level.")
adf_report(ts, "Level series (USD_AUD)")
adf_report(ts.diff(), "First difference of USD_AUD")

# Train-test-split
model_data = ts.loc[ts.index >= (ts.index.max() - pd.DateOffset(years=3))].copy()
H = 30
train = model_data.iloc[:-H]
test = model_data.iloc[-H:]
print(f"Training observations: {len(train)}  ({train.index.min().date()} to {train.index.max().date()})")
print(f"Test observations:     {len(test)}  ({test.index.min().date()} to {test.index.max().date()})")

## ACF & PACF series
train_diff = train.diff().dropna()
fig, axes = plt.subplots(1, 2, figsize=(14, 4))
plot_acf(train_diff, lags=30, ax=axes[0])
axes[0].set_title("ACF of Differenced Series")
plot_pacf(train_diff, lags=30, ax=axes[1], method="ywm")
axes[1].set_title("PACF of Differenced Series")
plt.tight_layout()
plt.show()

## Grid search ARIMA
import itertools
d = 1
p_values = range(0, 3)
q_values = range(0, 3)
results = []
for p, q in itertools.product(p_values, q_values):
    try:
        m = ARIMA(train, order=(p, d, q)).fit()
        results.append({"p": p, "d": d, "q": q, "AIC": m.aic, "BIC": m.bic})
    except Exception:
        results.append({"p": p, "d": d, "q": q, "AIC": np.nan, "BIC": np.nan})
order_search = pd.DataFrame(results).sort_values("AIC").reset_index(drop=True)
order_search

# Select best orders
best_order = (order_search.loc[0, "p"], d, order_search.loc[0, "q"])
best_order = tuple(int(x) for x in best_order)
print(f"Selected ARIMA order (p, d, q) by lowest AIC: {best_order}")

# Fit ARIMA
arima_model = ARIMA(train, order=best_order)
arima_fit = arima_model.fit()
print(arima_fit.summary())

# residual digonastics
residuals = arima_fit.resid
fig, axes = plt.subplots(2, 2, figsize=(13, 8))
axes[0, 0].plot(residuals)
axes[0, 0].set_title("Residuals over Time")
axes[0, 0].axhline(0, color="black", linewidth=0.8)
axes[0, 1].hist(residuals, bins=30, color="slategray", edgecolor="white")
axes[0, 1].set_title("Residual Distribution")
plot_acf(residuals, lags=30, ax=axes[1, 0])
axes[1, 0].set_title("ACF of Residuals")
from scipy import stats
stats.probplot(residuals, dist="norm", plot=axes[1, 1])
axes[1, 1].set_title("Q-Q Plot of Residuals")
plt.tight_layout()
plt.show()

# Ljung-box testing
lb_test = acorr_ljungbox(residuals, lags=[10, 20], return_df=True)
print(lb_test)
print()
if (lb_test["lb_pvalue"] > 0.05).all():
    print("Fail to reject H0: residuals show no significant autocorrelation (good — model is adequate).")
else:
    print("Some Ljung-Box p-values < 0.05: mild residual autocorrelation remains.")

# ARIMA forecasting vs actual
forecast_result = arima_fit.get_forecast(steps=H)
arima_forecast = forecast_result.predicted_mean
arima_forecast.index = test.index
conf_int = forecast_result.conf_int(alpha=0.05)
conf_int.index = test.index
fig, ax = plt.subplots()
ax.plot(train.index[-90:], train.iloc[-90:], label="Train (last 90 days)", color="steelblue")
ax.plot(test.index, test, label="Actual (test)", color="black", marker="o", markersize=3)
ax.plot(arima_forecast.index, arima_forecast, label=f"ARIMA{best_order} Forecast", color="red")
ax.fill_between(conf_int.index, conf_int.iloc[:, 0], conf_int.iloc[:, 1],color="red", alpha=0.15, label="95% CI")
ax.set_title(f"ARIMA{best_order} Forecast vs Actual")
ax.set_xlabel("Date")
ax.set_ylabel("USD to AUD Rate")
ax.legend()
plt.tight_layout()
plt.show()

# Fit expotential smoothing (damped hot)
ets_model = ExponentialSmoothing(train,trend="add",damped_trend=True,seasonal=None,initialization_method="estimated")
ets_fit = ets_model.fit(optimized=True)
print(f"Optimized smoothing level (alpha):{ets_fit.params['smoothing_level']:.4f}")
print(f"Optimized smoothing trend (beta):{ets_fit.params['smoothing_trend']:.4f}")
print(f"Damping trend (phi):{ets_fit.params['damping_trend']:.4f}")

# ETS forecast vs actual
ets_forecast = ets_fit.forecast(H)
ets_forecast.index = test.index
fig, ax = plt.subplots()
ax.plot(train.index[-90:], train.iloc[-90:], label="Train (last 90 days)", color="steelblue")
ax.plot(test.index, test, label="Actual (test)", color="black", marker="o", markersize=3)
ax.plot(ets_forecast.index, ets_forecast, label="Exponential Smoothing (Holt) Forecast", color="seagreen")
ax.set_title("Exponential Smoothing Forecast vs Actual")
ax.set_xlabel("Date")
ax.set_ylabel("USD to AUD Rate")
ax.legend()
plt.tight_layout()
plt.show()

# Combined comparision plot
fig, ax = plt.subplots()
ax.plot(train.index[-90:], train.iloc[-90:], label="Train (last 90 days)", color="steelblue")
ax.plot(test.index, test, label="Actual", color="black", marker="o", markersize=3)
ax.plot(arima_forecast.index, arima_forecast, label=f"ARIMA{best_order}", color="crimson")
ax.plot(ets_forecast.index, ets_forecast, label="Exponential Smoothing", color="seagreen")
ax.set_title("ARIMA vs Exponential Smoothing — Forecast Comparison")
ax.set_xlabel("Date")
ax.set_ylabel("USD to AUD Rate")
ax.legend()
plt.tight_layout()
plt.show()

# Erorr metrics
def evaluate(actual, predicted, label):
    mae = mean_absolute_error(actual, predicted)
    rmse = np.sqrt(mean_squared_error(actual, predicted))
    mape = np.mean(np.abs((actual - predicted) / actual)) * 100
    return {"Model": label, "MAE": mae, "RMSE": rmse, "MAPE (%)": mape}
metrics = pd.DataFrame([
    evaluate(test.values, arima_forecast.values, f"ARIMA{best_order}"),
    evaluate(test.values, ets_forecast.values, "Exponential Smoothing (Holt, damped)"),
]).set_index("Model")
metrics.round(5)

# navie baseline
naive_forecast = pd.Series(np.repeat(train.iloc[-1], H), index=test.index)
naive_metrics = evaluate(test.values, naive_forecast.values, "Naive (Random Walk) Baseline")
metrics_full = pd.concat([metrics, pd.DataFrame([naive_metrics]).set_index("Model")])
metrics_full.round(5)

"""## Conclusion

* The Time Series Analysis was successfully performed on the **USD/AUD exchange-rate dataset**.
* The dataset contained **7,588 observations**, and the data was prepared using business-day frequency.
* The original time series was found to be **non-stationary**, while first differencing made the series stationary.
* **ARIMA(0,1,0)** was selected as the best ARIMA model based on AIC.
* Residual analysis and the **Ljung-Box test** indicated that the ARIMA model adequately captured the time-dependent patterns.
* **Holt’s Damped Exponential Smoothing** performed slightly better than ARIMA, with **MAE = 0.01003, RMSE = 0.01102, and MAPE = 1.36%**.
* ARIMA achieved **MAE = 0.01030, RMSE = 0.01125, and MAPE = 1.40%**.
* Overall, **Holt’s Damped Exponential Smoothing was the best-performing forecasting model** among the models tested.
* The analysis demonstrates that time-series forecasting techniques can effectively predict exchange-rate movements based on historical patterns.

"""