# -*- coding: utf-8 -*-
"""XGBM & LGBM assessment.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1MxAiucv3PQPY1asOJL-NMXyK7u357M0X
"""

!pip install lightgbm xgboost

# Import required libraries
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

from sklearn.model_selection import train_test_split
from sklearn.metrics import accuracy_score, precision_score, recall_score, f1_score
from sklearn.metrics import confusion_matrix, classification_report
from sklearn.model_selection import cross_val_score, StratifiedKFold

from lightgbm import LGBMClassifier
from xgboost import XGBClassifier

df=pd.read_csv('diabetes.csv')
df

df.shape

df.size

df.info()

df.describe()

df.isnull().sum()

df.duplicated().sum()

zero_values=(df == 0).sum()
print(zero_values)

## Handle invalida zero values
columns_to_replace = [
    'Glucose',
    'BloodPressure',
    'SkinThickness',
    'Insulin',
    'BMI'
]
df[columns_to_replace] = df[columns_to_replace].replace(0, np.nan)

df.isnull().sum()

# Impute Missing Values
# We will use the median to fill missing values.
for column in columns_to_replace:
    df[column] = df[column].fillna(df[column].median())

df.isnull().sum()

# Outcome distrubution
sns.countplot(x='Outcome', data=df)
plt.title("Diabetes Outcome Distribution")
plt.xlabel("Outcome")
plt.ylabel("Number of Patients")
plt.show()

# Histrogram
df.hist(figsize=(15, 12), bins=20)
plt.suptitle("Distribution of Diabetes Dataset Features")
plt.tight_layout()
plt.show()

# Box plots
for i in df.select_dtypes(include=['int','float']).columns:
  sns.boxplot(df[i])
  plt.show()

# Correlation Heatmap
plt.figure(figsize=(10, 7))
sns.heatmap(
    df.corr(),
    annot=True,
    cmap='coolwarm',
    fmt='.2f'
)
plt.title("Correlation Heatmap")
plt.show()

# Relation Between feature and outcomes
plt.figure(figsize=(7, 5))
sns.scatterplot(
    x='Glucose',
    y='BMI',
    hue='Outcome',
    data=df
)
plt.title("Glucose vs BMI by Diabetes Outcome")
plt.show()

# bar plot average glucose vs outcome
plt.figure(figsize=(7, 5))
sns.barplot(
    x='Outcome',
    y='Glucose',
    data=df
)
plt.title("Average Glucose Level by Diabetes Outcome")
plt.xlabel("Outcome")
plt.ylabel("Average Glucose")
plt.show()

numeric_columns = [
    'Pregnancies',
    'Glucose',
    'BloodPressure',
    'SkinThickness',
    'Insulin',
    'BMI',
    'DiabetesPedigreeFunction',
    'Age'
]

# Average feature vs outcomes
df.groupby('Outcome')[numeric_columns].mean()

# separate features and target
X = df.drop('Outcome', axis=1)
y = df['Outcome']
print("Feature shape:", X.shape)
print("Target shape:", y.shape)

# Train test split
X_train, X_test, y_train, y_test = train_test_split(X,y,test_size=0.20,random_state=42,stratify=y)
print("Training data:", X_train.shape)
print("Testing data:", X_test.shape)

"""# LightGBM model"""

# create LGBM classifier
lgb_model = LGBMClassifier(
    n_estimators=100,
    learning_rate=0.05,
    max_depth=5,
    random_state=42,
    verbosity=-1
)

# Train the model
lgb_model.fit(X_train, y_train)

# predict the model
lgb_pred = lgb_model.predict(X_test)

# Evaluate LGBM
lgb_accuracy = accuracy_score(y_test, lgb_pred)
lgb_precision = precision_score(y_test, lgb_pred)
lgb_recall = recall_score(y_test, lgb_pred)
lgb_f1 = f1_score(y_test, lgb_pred)
print("LightGBM Performance")
print("Accuracy :", lgb_accuracy)
print("Precision:", lgb_precision)
print("Recall   :", lgb_recall)
print("F1 Score :", lgb_f1)

# LGBM classification report
print(classification_report(y_test, lgb_pred))

# LGBM confusion matrix
cm_lgb = confusion_matrix(y_test, lgb_pred)
plt.figure(figsize=(6, 5))
sns.heatmap(
    cm_lgb,
    annot=True,
    fmt='d',
    cmap='Blues'
)
plt.title("LightGBM Confusion Matrix")
plt.xlabel("Predicted")
plt.ylabel("Actual")
plt.show()

"""# XGBoost mode"""

# Now we build XGBM model and train this and predict
xgb_model = XGBClassifier(
    n_estimators=100,
    learning_rate=0.05,
    max_depth=5,
    random_state=42,
    eval_metric='logloss'
)

xgb_model.fit(X_train, y_train)

xgb_pred = xgb_model.predict(X_test)

# Evaluate XGBoost
xgb_accuracy = accuracy_score(y_test, xgb_pred)
xgb_precision = precision_score(y_test, xgb_pred)
xgb_recall = recall_score(y_test, xgb_pred)
xgb_f1 = f1_score(y_test, xgb_pred)
print("XGBoost Performance")
print("Accuracy :", xgb_accuracy)
print("Precision:", xgb_precision)
print("Recall   :", xgb_recall)
print("F1 Score :", xgb_f1)

# XGBoost classifiaction report
print(classification_report(y_test, xgb_pred))

# XGBoost confusion matrix
cm_xgb = confusion_matrix(y_test, xgb_pred)
plt.figure(figsize=(6, 5))
sns.heatmap(
    cm_xgb,
    annot=True,
    fmt='d',
    cmap='Greens'
)
plt.title("XGBoost Confusion Matrix")
plt.xlabel("Predicted")
plt.ylabel("Actual")
plt.show()

# Compare LGBM AND XGBM
results = pd.DataFrame({
    'Model': ['LightGBM', 'XGBoost'],
    'Accuracy': [lgb_accuracy, xgb_accuracy],
    'Precision': [lgb_precision, xgb_precision],
    'Recall': [lgb_recall, xgb_recall],
    'F1 Score': [lgb_f1, xgb_f1]
})
results

# Visualize models
results.set_index('Model').plot(
    kind='bar',
    figsize=(10, 6)
)
plt.title("LightGBM vs XGBoost Performance")
plt.ylabel("Score")
plt.ylim(0, 1)
plt.xticks(rotation=0)
plt.legend()
plt.show()

# Cross Validation
from sklearn.model_selection import cross_val_score, StratifiedKFold
cv = StratifiedKFold(
    n_splits=5,
    shuffle=True,
    random_state=42
)
# LightGBM Cross Validation
lgb_cv_scores = cross_val_score(
    lgb_model,
    X,
    y,
    cv=cv,
    scoring='accuracy'
)
print("LightGBM CV Scores:", lgb_cv_scores)
print("LightGBM Mean CV Accuracy:", lgb_cv_scores.mean())
# XGBoost Cross Validation
xgb_cv_scores = cross_val_score(
    xgb_model,
    X,
    y,
    cv=cv,
    scoring='accuracy'
)
print("XGBoost CV Scores:", xgb_cv_scores)
print("XGBoost Mean CV Accuracy:", xgb_cv_scores.mean())

cv_results = pd.DataFrame({
    'Model': ['LightGBM', 'XGBoost'],
    'Mean CV Accuracy': [
        lgb_cv_scores.mean(),
        xgb_cv_scores.mean()
    ]
})
print(cv_results)

cv_results.set_index('Model').plot(
    kind='bar',
    figsize=(8, 5),
    legend=False
)
plt.title("Cross Validation Accuracy Comparison")
plt.ylabel("Mean Accuracy")
plt.ylim(0, 1)
plt.xticks(rotation=0)
plt.show()

lgb_cv_scores.mean()

# Hyperparameter tuning XGBoost
xgb_results = []
for n_estimators in [50, 100, 150]:
    for learning_rate in [0.01, 0.05, 0.1]:
        model = XGBClassifier(
            n_estimators=n_estimators,
            learning_rate=learning_rate,
            max_depth=5,
            random_state=42,
            eval_metric='logloss'
        )
        scores = cross_val_score(
            model,
            X_train,
            y_train,
            cv=5,
            scoring='accuracy'
        )
        xgb_results.append({
            'n_estimators': n_estimators,
            'learning_rate': learning_rate,
            'accuracy': scores.mean()
        })
xgb_tuning = pd.DataFrame(xgb_results)
xgb_tuning.sort_values(
    by='accuracy',
    ascending=False
)

# LightGBM Hyperparameter Tuning
lgb_results = []
for n_estimators in [50, 100, 150]:
    for learning_rate in [0.01, 0.05, 0.1]:
        model = LGBMClassifier(
            n_estimators=n_estimators,
            learning_rate=learning_rate,
            max_depth=5,
            random_state=42,
            verbosity=-1
        )
        scores = cross_val_score(
            model,
            X_train,
            y_train,
            cv=5,
            scoring='accuracy'
        )
        lgb_results.append({
            'n_estimators': n_estimators,
            'learning_rate': learning_rate,
            'accuracy': scores.mean()
        })
# Create DataFrame
lgb_tuning = pd.DataFrame(lgb_results)
print(lgb_tuning)

# Find best LGBM tuning
best_lgb = lgb_tuning.sort_values(
    by='accuracy',
    ascending=False
).iloc[0]
print("Best LightGBM Parameters:")
print(best_lgb)

best_xgb = xgb_tuning.sort_values(
    by='accuracy',
    ascending=False
).iloc[0]
print("Best XGBoost Parameters:")
print(best_xgb)

lgb_importance = pd.Series(
    lgb_model.feature_importances_,
    index=X.columns
).sort_values(ascending=False)
lgb_importance

plt.figure(figsize=(10, 6))
lgb_importance.plot(kind='bar')
plt.title("LightGBM Feature Importance")
plt.xlabel("Features")
plt.ylabel("Importance")
plt.xticks(rotation=45)
plt.show()

# Find XGBM
xgb_importance = pd.Series(
    xgb_model.feature_importances_,
    index=X.columns
).sort_values(ascending=False)
xgb_importance

plt.figure(figsize=(10, 6))
xgb_importance.plot(kind='bar')
plt.title("XGBoost Feature Importance")
plt.xlabel("Features")
plt.ylabel("Importance")
plt.xticks(rotation=45)
plt.show()

# FinalModeL Comparision
final_results = pd.DataFrame({
    'Model': ['LightGBM', 'XGBoost'],
    'Accuracy': [lgb_accuracy, xgb_accuracy],
    'Precision': [lgb_precision, xgb_precision],
    'Recall': [lgb_recall, xgb_recall],
    'F1 Score': [lgb_f1, xgb_f1],
    'CV Accuracy': [
        lgb_cv_scores.mean(),
        xgb_cv_scores.mean()
    ]
})
final_results

# Find the best fit model
best_model = final_results.loc[
    final_results['F1 Score'].idxmax(),
    'Model'
]
print("Best Model based on F1 Score:", best_model)

best_accuracy_model = final_results.loc[
    final_results['Accuracy'].idxmax(),
    'Model'
]
print("Best Model based on Accuracy:", best_accuracy_model)

"""# LightGBM and XGBoost – Diabetes Prediction Report

## 1. Objective

The objective of this project is to develop and compare two powerful gradient-boosting algorithms, **LightGBM and XGBoost**, for predicting diabetes.

The analysis aims to:

* Explore and understand the diabetes dataset.
* Handle invalid zero values.
* Perform missing-value treatment.
* Analyze relationships between features and diabetes outcome.
* Train LightGBM and XGBoost models.
* Evaluate both models using classification metrics.
* Compare their cross-validation performance.
* Perform hyperparameter tuning.
* Identify important features.
* Select the best-performing model.

---

# 2. Dataset Description

The dataset contains **768 observations and 9 variables**.

There are **8 input features** and one target variable, `Outcome`.

### Input Features

1. Pregnancies
2. Glucose
3. BloodPressure
4. SkinThickness
5. Insulin
6. BMI
7. DiabetesPedigreeFunction
8. Age

### Target Variable

`Outcome`

* **0 → No Diabetes**
* **1 → Diabetes**

The dataset contains **500 observations with Outcome = 0** and **268 observations with Outcome = 1**, indicating some class imbalance.

---

# 3. Data Exploration

The dataset was examined using:

* Dataset shape
* Data types
* Descriptive statistics
* Missing-value analysis
* Zero-value analysis
* Histograms
* Box plots
* Correlation heatmap
* Scatter plots
* Grouped feature averages

Initially, the dataset contained no technically missing values. However, several medical variables contained zero values that are not medically meaningful, particularly Glucose, BloodPressure, SkinThickness, Insulin, and BMI.

For example:

* Glucose → 5 zero values
* BloodPressure → 35 zero values
* SkinThickness → 227 zero values
* Insulin → 374 zero values
* BMI → 11 zero values

These values were therefore treated as missing rather than valid measurements.

---

# 4. Data Preprocessing

The zero values in the following columns were replaced with `NaN`:

* Glucose
* BloodPressure
* SkinThickness
* Insulin
* BMI

Median imputation was then used to replace these missing values.

After imputation, the dataset contained **zero missing values**.

The dataset also contained **no duplicate records**.

The features and target were then separated:

**X:** 8 predictor variables
**y:** Outcome

An **80:20 stratified train-test split** was used.

### Training Data

**614 observations**

### Testing Data

**154 observations**

---

# 5. Exploratory Data Analysis Insights

The average values of the main features were compared between the two outcome groups.

| Feature                  | No Diabetes | Diabetes |
| ------------------------ | ----------: | -------: |
| Pregnancies              |        3.30 |     4.87 |
| Glucose                  |      110.68 |   142.13 |
| BloodPressure            |       70.92 |    75.12 |
| SkinThickness            |       27.73 |    31.69 |
| Insulin                  |      127.79 |   164.70 |
| BMI                      |       30.89 |    35.38 |
| DiabetesPedigreeFunction |        0.43 |     0.55 |
| Age                      |       31.19 |    37.07 |

### Key observation

The diabetes group has higher average values across all the listed features.

In particular, **Glucose shows a substantial difference**:

* No Diabetes: approximately **110.68**
* Diabetes: approximately **142.13**

This makes glucose an especially informative feature for the classification models.

---

# 6. LightGBM Model

A LightGBM classifier was created with:

* `n_estimators = 100`
* `learning_rate = 0.05`
* `max_depth = 5`
* `random_state = 42`

The model was trained on the training data and predictions were generated for the test set.

---

# 7. LightGBM Performance

The LightGBM model achieved:

| Metric    |      Score |
| --------- | ---------: |
| Accuracy  | **77.27%** |
| Precision | **69.39%** |
| Recall    | **62.96%** |
| F1 Score  | **66.02%** |

### Classification Performance

For the diabetes class:

* Precision = **69%**
* Recall = **63%**
* F1-score = **66%**

For the no-diabetes class:

* Precision = **81%**
* Recall = **85%**
* F1-score = **83%**

Therefore, the model performs better at identifying the **No Diabetes** class than the **Diabetes** class.

---

# 8. XGBoost Model

An XGBoost classifier was trained using:

* `n_estimators = 100`
* `learning_rate = 0.05`
* `max_depth = 5`
* `random_state = 42`
* `eval_metric = logloss`

The model was trained on the same training and testing datasets as LightGBM.

---

# 9. XGBoost Performance

The XGBoost model achieved:

| Metric    |      Score |
| --------- | ---------: |
| Accuracy  | **75.32%** |
| Precision | **67.39%** |
| Recall    | **57.41%** |
| F1 Score  | **62.00%** |

For the diabetes class:

* Precision = **67%**
* Recall = **57%**
* F1-score = **62%**

For the no-diabetes class:

* Precision = **79%**
* Recall = **85%**
* F1-score = **82%**

---

# 10. LightGBM vs XGBoost

The direct test-set comparison is:

| Model        |   Accuracy |  Precision |     Recall |   F1 Score |
| ------------ | ---------: | ---------: | ---------: | ---------: |
| **LightGBM** | **77.27%** | **69.39%** | **62.96%** | **66.02%** |
| **XGBoost**  |     75.32% |     67.39% |     57.41% |     62.00% |

### Interpretation

LightGBM outperformed XGBoost on all four test-set metrics.

The biggest difference is in recall:

**LightGBM = 62.96%**
**XGBoost = 57.41%**

Therefore, LightGBM was better at identifying positive diabetes cases on the test dataset.

---

# 11. Cross-Validation

Five-fold Stratified Cross-Validation was performed to evaluate the models across multiple subsets of the dataset.

### LightGBM

Mean Cross-Validation Accuracy:

**75.26%**

### XGBoost

Mean Cross-Validation Accuracy:

**76.30%**

Interestingly, XGBoost achieved a slightly higher **mean cross-validation accuracy** than LightGBM.

| Model       | Mean CV Accuracy |
| ----------- | ---------------: |
| LightGBM    |           75.26% |
| **XGBoost** |       **76.30%** |

This indicates that XGBoost had slightly better average accuracy across the five validation folds, even though LightGBM performed better on the single held-out test set.

---

# 12. Hyperparameter Tuning

Hyperparameter tuning was performed by testing different combinations of:

* `n_estimators`
* `learning_rate`

The maximum depth was maintained at 5.

## Best XGBoost Parameters

The best combination found was:

* **n_estimators = 150**
* **learning_rate = 0.05**
* Accuracy = **75.41%**

## Best LightGBM Parameters

The best combination found was:

* **n_estimators = 150**
* **learning_rate = 0.01**
* Accuracy = **76.72%**

Therefore, within the tested parameter combinations, the best LightGBM configuration produced a higher cross-validation accuracy than the best XGBoost configuration.

---

# 13. Feature Importance

Feature importance was extracted from both models.

## LightGBM Feature Importance

The most important features were:

| Feature                  | Importance |
| ------------------------ | ---------: |
| Glucose                  |    **271** |
| BMI                      |    **240** |
| DiabetesPedigreeFunction |    **225** |
| Age                      |    **173** |
| Pregnancies              |    **120** |
| Insulin                  |    **108** |
| BloodPressure            |     **96** |
| SkinThickness            |     **86** |

### LightGBM Insight

**Glucose** was the most important feature, followed by **BMI** and **DiabetesPedigreeFunction**.

---

## XGBoost Feature Importance

| Feature                  | Importance |
| ------------------------ | ---------: |
| Glucose                  | **35.30%** |
| BMI                      | **15.97%** |
| Age                      | **11.24%** |
| Insulin                  |  **8.60%** |
| DiabetesPedigreeFunction |  **8.46%** |
| Pregnancies              |  **8.43%** |
| BloodPressure            |  **6.39%** |
| SkinThickness            |  **5.62%** |

### XGBoost Insight

XGBoost also identified **Glucose as the most important feature**, accounting for approximately **35.3%** of the model's feature importance.

---

# 14. Key Insights

### Insight 1 – Glucose is the strongest predictor

Both LightGBM and XGBoost identified **Glucose** as the most important feature.

This is also supported by the EDA, where the average glucose level was considerably higher in the diabetes group.

### Insight 2 – BMI is highly influential

BMI was the second most important feature in both models.

The average BMI increased from approximately **30.89** in the no-diabetes group to **35.38** in the diabetes group.

### Insight 3 – Age contributes to prediction

Age was also an important predictor.

The average age was:

* No Diabetes: **31.19**
* Diabetes: **37.07**

### Insight 4 – LightGBM performs better on the test set

LightGBM achieved:

**77.27% accuracy**

compared with:

**75.32% accuracy for XGBoost**

It also achieved better precision, recall, and F1-score.

### Insight 5 – XGBoost has slightly higher CV accuracy

Despite performing worse on the held-out test set, XGBoost achieved a mean five-fold CV accuracy of **76.30%**, compared with **75.26% for LightGBM**.

This shows why evaluating a model using only one metric or one data split can be misleading.

### Insight 6 – LightGBM is selected by F1-score

The notebook selects **LightGBM as the best model based on F1-score**.

LightGBM:

**F1 = 66.02%**

XGBoost:

**F1 = 62.00%**

### Insight 7 – Both models struggle more with the positive class

Both models have substantially lower recall for the diabetes class than for the no-diabetes class.

This suggests that the models miss a considerable number of positive diabetes cases.

For a diabetes-screening application, this is an important limitation because false negatives can be particularly significant.

---

# 15. Final Model Comparison

| Evaluation             |   LightGBM |    XGBoost | Better   |
| ---------------------- | ---------: | ---------: | -------- |
| Test Accuracy          | **77.27%** |     75.32% | LightGBM |
| Test Precision         | **69.39%** |     67.39% | LightGBM |
| Test Recall            | **62.96%** |     57.41% | LightGBM |
| Test F1                | **66.02%** |     62.00% | LightGBM |
| Mean CV Accuracy       |     75.26% | **76.30%** | XGBoost  |
| Best tuned CV accuracy | **76.72%** |     75.41% | LightGBM |

---

# 16. Final Conclusion

The project successfully implemented and compared **LightGBM and XGBoost** for diabetes prediction.

After data preprocessing, invalid zero values in medical variables were treated as missing values and replaced using median imputation. The cleaned dataset was then divided into training and testing sets using stratified sampling.

Both gradient-boosting algorithms produced reasonable classification performance. However, on the held-out test set, **LightGBM performed better than XGBoost across accuracy, precision, recall, and F1-score**.

LightGBM achieved:

**77.27% Accuracy**
**69.39% Precision**
**62.96% Recall**
**66.02% F1-score**

XGBoost achieved:

**75.32% Accuracy**
**67.39% Precision**
**57.41% Recall**
**62.00% F1-score**

The cross-validation results showed a slightly different picture, with XGBoost achieving **76.30% mean accuracy** compared with **75.26% for LightGBM**. Therefore, the difference between the models is not extremely large, and model selection depends on the evaluation criterion.

Based on the notebook's final selection criteria, **LightGBM is the best-fit model because it achieved the highest test accuracy and F1-score**.

Feature-importance analysis from both models consistently identified **Glucose and BMI as highly influential features**, with Glucose being the strongest predictor.

Overall, this project demonstrates that gradient-boosting algorithms can effectively model diabetes outcomes, while also highlighting the importance of preprocessing, cross-validation, hyperparameter tuning, and feature-importance analysis.

**Important limitation:** This model is an educational machine-learning prediction system and should not be treated as a medical diagnostic tool. A clinical diagnosis should always involve qualified healthcare professionals.
"""